import React,{useEffect,useRef,useState}from'react';
import{useNavigate}from'react-router-dom';
import{deleteField,doc,updateDoc}from'firebase/firestore';
import{Fingerprint,KeyRound,ShieldCheck}from'lucide-react';
import toast from'react-hot-toast';
import{useAuthStore}from'../../store/authStore';
import{db}from'../../firebase/config';
import{getHomeRouteByRole}from'../../lib/roleNavigation';
import{deviceSecurityService}from'../../services/deviceSecurityService';
import LogoutModal from'../../components/LogoutModal';

async function hashPin(value:string){const encoded=new TextEncoder().encode(value);const buffer=await crypto.subtle.digest('SHA-256',encoded);return Array.from(new Uint8Array(buffer)).map(b=>b.toString(16).padStart(2,'0')).join('')}
type Mode='temporary'|'setup'|'verify';
const PIN_MIN=4;const PIN_MAX=10;
const validPin=(value:string)=>/^\d{4,10}$/.test(value);

export default function PinScreen(){
  const navigate=useNavigate();
  const{user,setUser,setPinVerified}=useAuthStore();
  const[pin,setPin]=useState('');const[confirmPin,setConfirmPin]=useState('');const[mode,setMode]=useState<Mode>('verify');const[loading,setLoading]=useState(false);const[showLogoutModal,setShowLogoutModal]=useState(false);const[biometricReady,setBiometricReady]=useState(false);const autoBioAttempted=useRef(false);
  const forcedChange=Boolean(user?.mustChangePin);
  const clientSetup=Boolean(user?.role==='client'&&!user?.pinHash&&!forcedChange);

  useEffect(()=>{if(!user){navigate('/login');return;}if(forcedChange){setMode('temporary');return;}if(user.role==='client'){setMode(clientSetup?'setup':'verify');return;}navigate(getHomeRouteByRole(user.role),{replace:true});},[user,forcedChange,clientSetup,navigate]);
  useEffect(()=>{if(!user?.uid||!user.useBiometrics){setBiometricReady(false);return}void deviceSecurityService.platformAvailable().then(setBiometricReady)},[user?.uid,user?.useBiometrics]);

  const clean=(value:string)=>value.replace(/\D/g,'').slice(0,PIN_MAX);
  const goHome=()=>{if(!user)return;setPinVerified(true);sessionStorage.setItem('marketcash_security_verified_at',String(Date.now()));navigate(getHomeRouteByRole(user.role),{replace:true})};
  const biometricUnlock=async()=>{if(!user)return;setLoading(true);try{await deviceSecurityService.verify(user.uid);goHome();toast.success('Biométrie confirmée.')}catch(error:any){toast.error(error?.message||'Vérification biométrique impossible.')}finally{setLoading(false)}};
  useEffect(()=>{if(mode!=='verify'||!biometricReady||!user?.uid||autoBioAttempted.current)return;autoBioAttempted.current=true;const timer=setTimeout(()=>void biometricUnlock(),120);return()=>clearTimeout(timer)},[mode,biometricReady,user?.uid]);
  const completeSetup=async()=>{if(!user)return;if(!validPin(pin)||!validPin(confirmPin))return toast.error(`Le PIN doit contenir entre ${PIN_MIN} et ${PIN_MAX} chiffres.`);if(pin!==confirmPin)return toast.error('Les deux codes PIN ne correspondent pas.');if(forcedChange&&pin==='1234')return toast.error('Choisissez un code différent du code temporaire.');setLoading(true);try{const pinHash=await hashPin(pin);const now=Date.now();await updateDoc(doc(db,'users',user.uid),{pinHash,temporaryPinHash:deleteField(),mustChangePin:false,pinChangedAt:now,updatedAt:now});setUser({...user,pinHash,temporaryPinHash:undefined,mustChangePin:false,pinChangedAt:now,updatedAt:now});goHome();toast.success(forcedChange?'Nouveau PIN enregistré.':'PIN créé.');}catch(error:any){console.error('[PIN_SAVE_ERROR]',error);toast.error(error?.code==='permission-denied'?'Permission refusée pendant l’enregistrement du PIN.':'Impossible d’enregistrer le PIN.');}finally{setLoading(false)}};
  const verifyTemporary=async(e:React.FormEvent)=>{e.preventDefault();if(!user||!validPin(pin))return void toast.error(`Entrez un PIN de ${PIN_MIN} à ${PIN_MAX} chiffres.`);setLoading(true);try{const entered=await hashPin(pin);const expected=user.temporaryPinHash||user.pinHash;if(!expected||entered!==expected){toast.error('Code temporaire incorrect.');setPin('');return;}setPin('');setConfirmPin('');setMode('setup');}finally{setLoading(false)}};
  const verifyExisting=async(e:React.FormEvent)=>{e.preventDefault();if(!user||!validPin(pin))return void toast.error(`Entrez un PIN de ${PIN_MIN} à ${PIN_MAX} chiffres.`);setLoading(true);try{const entered=await hashPin(pin);if(user.pinHash===entered)goHome();else{toast.error('PIN incorrect.');setPin('')}}finally{setLoading(false)}};
  const skipForNow=()=>{if(!user||user.role!=='client'||user.pinHash||forcedChange)return;setPinVerified(true);sessionStorage.setItem('marketcash_pin_setup_deferred','1');toast('Vous pourrez créer votre PIN depuis Paramètres > Sécurité.');navigate('/client/home',{replace:true});};

  if(mode==='setup')return <div className="flex min-h-screen items-center justify-center bg-slate-50 p-4"><div className="w-full max-w-sm rounded-[2rem] border bg-white p-7 shadow-xl"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-blue-950"><ShieldCheck/></div><h1 className="mt-5 text-center text-2xl font-black text-blue-950">{forcedChange?'Créer votre nouveau PIN':'Sécuriser Market-Cash'}</h1><p className="mt-2 text-center text-sm leading-5 text-slate-500">Choisissez un PIN personnel de <b>4 à 10 chiffres</b>, puis confirmez-le.</p><div className="mt-6 space-y-3"><input autoFocus type="password" inputMode="numeric" autoComplete="new-password" minLength={PIN_MIN} maxLength={PIN_MAX} value={pin} onChange={e=>setPin(clean(e.target.value))} className="w-full rounded-2xl border-2 bg-slate-50 px-5 py-4 text-center text-2xl font-black tracking-[.25em]" placeholder="Nouveau PIN (4 à 10 chiffres)"/><input type="password" inputMode="numeric" autoComplete="new-password" minLength={PIN_MIN} maxLength={PIN_MAX} value={confirmPin} onChange={e=>setConfirmPin(clean(e.target.value))} className="w-full rounded-2xl border-2 bg-slate-50 px-5 py-4 text-center text-2xl font-black tracking-[.25em]" placeholder="Confirmer le PIN"/></div><button onClick={()=>void completeSetup()} disabled={loading||!validPin(pin)||!validPin(confirmPin)} className="mt-4 w-full rounded-2xl bg-blue-950 py-4 font-black text-white disabled:opacity-40">{loading?'Création…':'Créer le PIN'}</button>{!forcedChange&&<button onClick={skipForNow} disabled={loading} className="mt-3 w-full rounded-2xl border bg-white py-3.5 text-sm font-black text-slate-600">Faire plus tard</button>}<button onClick={()=>setShowLogoutModal(true)} className="mt-6 w-full text-xs font-black uppercase text-red-500">Déconnexion</button><LogoutModal isOpen={showLogoutModal} onClose={()=>setShowLogoutModal(false)}/></div></div>;
  if(mode==='temporary')return <div className="flex min-h-screen items-center justify-center bg-slate-50 p-4"><div className="w-full max-w-sm rounded-[2rem] border bg-white p-7 text-center shadow-xl"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-amber-50 text-amber-800"><ShieldCheck/></div><h1 className="mt-5 text-2xl font-black text-blue-950">Code temporaire</h1><p className="mt-2 text-sm text-slate-500">Entrez le code temporaire remis par l’administrateur, puis choisissez votre nouveau PIN de 4 à 10 chiffres.</p><form onSubmit={verifyTemporary} className="mt-6"><input autoFocus type="password" inputMode="numeric" maxLength={PIN_MAX} value={pin} onChange={e=>setPin(clean(e.target.value))} className="w-full rounded-2xl border-2 bg-slate-50 px-5 py-5 text-center text-3xl font-black tracking-[.3em]" placeholder="PIN temporaire"/><button disabled={loading||!validPin(pin)} className="mt-4 w-full rounded-2xl bg-blue-950 py-4 font-black text-white disabled:opacity-40">{loading?'Vérification…':'Continuer'}</button></form><button onClick={()=>setShowLogoutModal(true)} className="mt-7 text-xs font-black uppercase text-red-500">Déconnexion</button><LogoutModal isOpen={showLogoutModal} onClose={()=>setShowLogoutModal(false)}/></div></div>;
  return <div className="flex min-h-screen items-center justify-center bg-slate-50 p-4"><div className="w-full max-w-sm rounded-[2rem] border bg-white p-7 text-center shadow-xl"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-blue-950"><KeyRound/></div><h1 className="mt-5 text-2xl font-black text-blue-950">Code PIN</h1><p className="mt-2 text-sm text-slate-500">Entrez votre PIN Market-Cash de 4 à 10 chiffres.</p><form onSubmit={verifyExisting} className="mt-6"><input autoFocus type="password" inputMode="numeric" maxLength={PIN_MAX} value={pin} onChange={e=>setPin(clean(e.target.value))} className="w-full rounded-2xl border-2 bg-slate-50 px-5 py-5 text-center text-3xl font-black tracking-[.3em]" placeholder="Votre PIN"/><button disabled={loading||!validPin(pin)} className="mt-4 w-full rounded-2xl bg-blue-950 py-4 font-black text-white disabled:opacity-40">{loading?'Vérification…':'Déverrouiller'}</button></form>{biometricReady&&<button onClick={()=>void biometricUnlock()} disabled={loading} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl border border-blue-100 bg-blue-50 py-3.5 text-sm font-black text-blue-900"><Fingerprint size={18}/>Empreinte / Face ID</button>}<button onClick={()=>setShowLogoutModal(true)} className="mt-7 text-xs font-black uppercase text-red-500">Déconnexion</button><LogoutModal isOpen={showLogoutModal} onClose={()=>setShowLogoutModal(false)}/></div></div>;
}
