import { createHash, randomInt } from 'node:crypto';
import { getApps, initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { HttpsError, onCall } from 'firebase-functions/v2/https';
import { cardAccountId, getOwnedLocalCard, type LocalCardCurrency } from './localCardPair';

if (!getApps().length) initializeApp();
const db=getFirestore();
const REGION='europe-west1';
const sha256=(v:string)=>createHash('sha256').update(v).digest('hex');
const walletId=(uid:string,c:LocalCardCurrency)=>`wallet_${c.toLowerCase()}_${uid}`;
const requireAuth=(r:any)=>{const uid=String(r.auth?.uid||'');if(!uid)throw new HttpsError('unauthenticated','Connexion requise.');return uid};
const amountOf=(v:any)=>{const n=Math.round(Number(v)*100)/100;if(!Number.isFinite(n)||n<=0)throw new HttpsError('invalid-argument','Montant invalide.');return n};
const keyOf=(v:any,p:string,uid:string)=>{const raw=String(v||'').replace(/[^A-Za-z0-9_-]/g,'').slice(0,120);return raw||`${p}_${uid}_${Date.now()}_${randomInt(1000,9999)}`};
async function requireCvv(uid:string,raw:any){const cvv=String(raw||'').replace(/\D/g,'');if(!/^\d{3}$/.test(cvv))throw new HttpsError('invalid-argument','CVV Market-Cash invalide.');const s=await db.doc(`user_security/${uid}`).get();const hash=String(s.data()?.localTransactionCvvHash||'');const clear=String(s.data()?.localTransactionCvv||'');if((hash&&hash!==sha256(cvv))||(!hash&&clear!==cvv))throw new HttpsError('permission-denied','CVV Market-Cash incorrect.');}
async function activeAgent(uid:string){const [u,p]=await Promise.all([db.doc(`users/${uid}`).get(),db.doc(`agent_profiles/${uid}`).get()]);if(!u.exists||u.data()?.role!=='agent'||!p.exists||p.data()?.status!=='active'||['blocked','suspended','banned','deleted'].includes(String(u.data()?.accountStatus||'')))throw new HttpsError('failed-precondition','Agent Market-Cash indisponible.');return u;}
async function resolveAgent(raw:any){const value=String(raw||'').trim().toUpperCase();let uid='';if(/^MCW-[A-F0-9]{10}$/.test(value)){const s=await db.doc(`wallet_public_ids/${value}`).get();uid=String(s.data()?.userId||'')}else{const digits=value.replace(/\D/g,'');if(digits.length>=6){const s=await db.doc(`wallet_recharge_numbers/${digits}`).get();uid=String(s.data()?.userId||'')}}if(!uid)throw new HttpsError('not-found','Agent Market-Cash introuvable.');await activeAgent(uid);return uid;}
async function ensureAgentWallet(uid:string,c:LocalCardCurrency){const ref=db.doc(`wallet_accounts/${walletId(uid,c)}`);const s=await ref.get();if(!s.exists)await ref.set({id:ref.id,userId:uid,accountType:'agent',currency:c,availableBalance:0,ledgerBalance:0,heldBalance:0,status:'active',createdAt:Date.now(),updatedAt:Date.now()});return ref;}

export const agentDepositWithCvvV3=onCall({region:REGION},async request=>{
 const agentUid=requireAuth(request);await activeAgent(agentUid);await requireCvv(agentUid,request.data?.cvv);
 const currency=String(request.data?.currency||'').toUpperCase() as LocalCardCurrency;if(!['USD','CDF'].includes(currency))throw new HttpsError('invalid-argument','Devise invalide.');
 const amount=amountOf(request.data?.amount);const target=String(request.data?.marketCashId||'').trim().toUpperCase();const map=await db.doc(`wallet_public_ids/${target}`).get();const clientUid=String(map.data()?.userId||'');if(!clientUid||clientUid===agentUid)throw new HttpsError('not-found','Client Market-Cash introuvable.');const client=await db.doc(`users/${clientUid}`).get();if(!client.exists||client.data()?.role!=='client')throw new HttpsError('failed-precondition','Compte client invalide.');
 const agentRef=await ensureAgentWallet(agentUid,currency);const clientRef=db.doc(`wallet_accounts/${walletId(clientUid,currency)}`);if(!(await clientRef.get()).exists)await clientRef.set({id:clientRef.id,userId:clientUid,accountType:'client',currency,availableBalance:0,ledgerBalance:0,heldBalance:0,status:'active',createdAt:Date.now(),updatedAt:Date.now()});const txId=keyOf(request.data?.idempotencyKey,'agentdep',agentUid);
 return db.runTransaction(async tx=>{const [prior,a,c]=await Promise.all([tx.get(db.doc(`wallet_transactions/${txId}`)),tx.get(agentRef),tx.get(clientRef)]);if(prior.exists)return{ok:true,duplicate:true,reference:prior.data()?.reference,transactionId:txId};if(a.data()?.status!=='active'||Number(a.data()?.availableBalance||0)<amount)throw new HttpsError('failed-precondition','Float agent insuffisant.');if(c.data()?.status!=='active')throw new HttpsError('failed-precondition','Wallet client indisponible.');const now=Date.now(),reference=`MC-DEP-${now}`;tx.update(agentRef,{availableBalance:Number(a.data()?.availableBalance||0)-amount,ledgerBalance:Number(a.data()?.ledgerBalance||0)-amount,updatedAt:now});tx.update(clientRef,{availableBalance:Number(c.data()?.availableBalance||0)+amount,ledgerBalance:Number(c.data()?.ledgerBalance||0)+amount,updatedAt:now});tx.set(db.doc(`wallet_transactions/${txId}`),{id:txId,reference,type:'cash_in',status:'settled',currency,amount,agentId:agentUid,clientId:clientUid,userIds:[agentUid,clientUid],sourceWalletId:agentRef.id,destinationWalletId:clientRef.id,rail:'agent_cvv_v3',authenticatedBy:'agent_local_cvv',createdAt:now,updatedAt:now});tx.set(db.collection('notifications').doc(),{userId:clientUid,title:'Dépôt reçu',message:`Un Agent Market-Cash a déposé ${amount} ${currency} sur votre wallet.`,type:'success',category:'general',read:false,transactionId:txId,createdAt:now});return{ok:true,reference,transactionId:txId}});
});

export const clientWithdrawLocalCardToAgentV3=onCall({region:REGION},async request=>{
 const clientUid=requireAuth(request);const card=await getOwnedLocalCard(clientUid,String(request.data?.cardId||''));if(card.status!=='active')throw new HttpsError('failed-precondition','Carte locale bloquée.');await requireCvv(clientUid,request.data?.cvv);const currency=String(card.currency||'') as LocalCardCurrency;const amount=amountOf(request.data?.amount);const agentUid=await resolveAgent(request.data?.agentId);const agentRef=await ensureAgentWallet(agentUid,currency);const cardRef=db.doc(`card_wallet_accounts/${cardAccountId(card.cardId,currency)}`);const txId=keyOf(request.data?.idempotencyKey,'cardwithdraw',clientUid);
 return db.runTransaction(async tx=>{const [prior,b,a]=await Promise.all([tx.get(db.doc(`wallet_transactions/${txId}`)),tx.get(cardRef),tx.get(agentRef)]);if(prior.exists)return{ok:true,duplicate:true,reference:prior.data()?.reference,transactionId:txId};if(b.data()?.status!=='active'||Number(b.data()?.availableBalance||0)<amount)throw new HttpsError('failed-precondition','Solde de la carte locale insuffisant.');if(a.data()?.status!=='active')throw new HttpsError('failed-precondition','Float Agent indisponible.');const now=Date.now(),reference=`MC-RET-${now}`;tx.update(cardRef,{availableBalance:Number(b.data()?.availableBalance||0)-amount,ledgerBalance:Number(b.data()?.ledgerBalance||0)-amount,updatedAt:now});tx.update(agentRef,{availableBalance:Number(a.data()?.availableBalance||0)+amount,ledgerBalance:Number(a.data()?.ledgerBalance||0)+amount,updatedAt:now});tx.set(db.doc(`wallet_transactions/${txId}`),{id:txId,reference,type:'cash_out',status:'settled',currency,amount,agentId:agentUid,clientId:clientUid,userIds:[clientUid,agentUid],cardId:card.cardId,sourceCardWalletId:cardRef.id,destinationWalletId:agentRef.id,rail:'client_local_card_to_agent_v3',authenticatedBy:'client_local_cvv',createdAt:now,updatedAt:now});tx.set(db.collection('notifications').doc(),{userId:agentUid,title:'Retrait client confirmé',message:`${amount} ${currency} ont été crédités sur votre float. Remettez le cash au client.`,type:'success',category:'general',read:false,transactionId:txId,createdAt:now});tx.set(db.collection('notifications').doc(),{userId:clientUid,title:'Retrait confirmé',message:`${amount} ${currency} ont été débités de votre carte locale Market-Cash.`,type:'success',category:'general',read:false,transactionId:txId,createdAt:now});return{ok:true,reference,transactionId:txId,agentId:agentUid,currency,amount}});
});