import { createHash, randomBytes } from 'node:crypto';
import { getApps, initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { onRequest } from 'firebase-functions/v2/https';
import { localCardId, type LocalCardCurrency } from './localCardPair';

if (!getApps().length) initializeApp();
const db = getFirestore();
const REGION = 'europe-west1';
const PAYMENT_ENDPOINT = 'https://europe-west1-automarket-fintech.cloudfunctions.net/marketCashApiCardPayment';
type Currency = 'USD' | 'CDF';

const sha256=(value:string)=>createHash('sha256').update(value).digest('hex');
const normalize=(value:unknown)=>String(value||'').trim();
const normalizeUpper=(value:unknown)=>normalize(value).toUpperCase();
const roundMoney=(value:number)=>Math.round(value*100)/100;
const cardAccountId=(cardId:string,currency:string)=>`card_${currency.toLowerCase()}_${cardId}`;
const developerWalletId=(developerId:string,currency:string)=>`dev_${currency.toLowerCase()}_${developerId}`;
const billingAccountId=(developerId:string)=>`billing_${developerId}`;
const apiRevenueId='market_cash_api_revenue_usd';

function readApiKey(req:any){const authorization=normalize(req.header('authorization')),headerKey=normalize(req.header('x-market-cash-api-key'));return authorization.toLowerCase().startsWith('bearer ')?authorization.slice(7).trim():headerKey}
function parseCurrency(value:unknown):Currency{const currency=normalizeUpper(value)as Currency;if(currency!=='USD'&&currency!=='CDF')throw new Error('CURRENCY_INVALID');return currency}
function parseAmount(value:unknown){const amount=Number(value);if(!Number.isFinite(amount)||amount<=0)throw new Error('AMOUNT_INVALID');return roundMoney(amount)}
function parseExternalReference(value:unknown){const reference=normalize(value);if(reference.length<6||reference.length>120)throw new Error('REFERENCE_INVALID');return reference}
function expiryIsCurrent(expiry:string){const match=String(expiry||'').trim().match(/^(\d{2})\/(\d{2})$/);if(!match)return false;const month=Number(match[1]),year=2000+Number(match[2]);if(month<1||month>12)return false;return new Date(Date.UTC(year,month,1)).getTime()>Date.now()}
async function apiUnitPrice(partner:boolean){const configured=(await db.doc('app_settings/developer_api_pricing').get()).data()||{},value=Number(partner?configured.wholesaleUsd:configured.directUsd);return roundMoney(Number.isFinite(value)&&value>=0?value:(partner?0.05:0.10))}

async function resolveActiveDeveloperApp(apiKey:string){
 const hash=sha256(apiKey),snapshot=await db.collection('developer_apps').where('apiKeyHash','==',hash).limit(3).get(),active=snapshot.docs.filter(doc=>doc.data()?.status==='active'&&doc.data()?.apiEnabled!==false);
 if(active.length!==1)throw new Error('UNAUTHORIZED');const appDoc=active[0],app=appDoc.data()||{},appId=String(app.appId||appDoc.id).trim().toUpperCase(),developerId=String(app.developerId||'').trim();if(!appId||!developerId)throw new Error('UNAUTHORIZED');
 const features=Array.isArray(app.enabledFeatures)?app.enabledFeatures:(Array.isArray(app.scopes)?app.scopes:[]);if(!features.includes('payments.create'))throw new Error('API_SCOPE_DENIED');
 const developerDoc=await db.doc(`developer_accounts/${developerId}`).get();if(!developerDoc.exists||developerDoc.data()?.status!=='active')throw new Error('DEVELOPER_INACTIVE');return{appId,app,developerId,developer:developerDoc.data()||{}}
}
function ensureCurrencyAllowed(app:any,currency:Currency){const allowed=Array.isArray(app.allowedCurrencies)&&app.allowedCurrencies.length?app.allowedCurrencies:['USD','CDF'];if(!allowed.includes(currency))throw new Error('CURRENCY_NOT_ALLOWED')}
function normalizeCardReference(value:unknown){const raw=normalize(value);if(!raw)return'';const native=raw.match(/(?:MARKET-CASH-CARD\s*:\s*)?(MCL-[A-Z0-9_-]{4,120})/i);return native?.[1]?.toUpperCase()||''}

async function canonicalCardIdentity(cardNumber:string){
 if(!/^5585020002\d{6}$/.test(cardNumber))return null;const registry=await db.doc(`card_number_registry/${cardNumber}`).get();if(!registry.exists)return null;const uid=String(registry.data()?.userId||'').trim();if(!uid)return null;const currency=String(registry.data()?.currency||'').toUpperCase() as LocalCardCurrency;if(currency!=='USD'&&currency!=='CDF')return null;const cardId=localCardId(uid,currency),cardDoc=await db.doc(`local_cards/${cardId}`).get();if(!cardDoc.exists)return null;const card=cardDoc.data()||{};return{uid,cardId,holder:normalize(card.cardHolder||card.cardHolderName||card.userName||'CLIENT MARKET-CASH'),last4:cardNumber.slice(-4),expiry:normalize(card.expiryEnd),cardIdentifier:normalizeCardReference(card.cardIdentifier),status:String(card.status||''),program:String(card.program||'')}
}
async function resolveCardCapture(cardReference:unknown){
 const identifier=normalizeCardReference(cardReference);if(!identifier)return null;const cards=await db.collection('local_cards').where('cardIdentifier','==',identifier).limit(1).get();if(cards.empty)return null;const cardDoc=cards.docs[0],card=cardDoc.data()||{};if(String(card.program||'')!=='market_cash_local'||String(card.status||'')!=='active')return null;const cardNumber=normalize(card.cardNumber).replace(/\D/g,'');if(!/^5585020002\d{6}$/.test(cardNumber))return null;const cardHolder=normalize(card.cardHolder||card.cardHolderName||card.userName||'CLIENT MARKET-CASH'),expiry=normalize(card.expiryEnd);if(!/^\d{2}\/\d{2}$/.test(expiry))return null;return{cardId:String(card.cardId||cardDoc.id),userId:String(card.userId||''),cardIdentifier:identifier,cardNumber,cardHolder,expiry,cardLast4:cardNumber.slice(-4)}
}

function createMandateToken(){const mandateId=`md_${randomBytes(10).toString('hex')}`,secret=randomBytes(24).toString('hex');return{mandateId,secretHash:sha256(secret),token:`mcm_${mandateId}.${secret}`}}
function parseMandateToken(value:unknown){const token=normalize(value),match=token.match(/^mcm_(md_[a-f0-9]{20})\.([a-f0-9]{48})$/i);if(!match)throw new Error('MANDATE_INVALID');return{mandateId:match[1].toLowerCase(),secret:match[2].toLowerCase(),token}}
async function loadMandate(tokenValue:unknown,appId:string){const parsed=parseMandateToken(tokenValue),ref=db.doc(`payment_mandates/${parsed.mandateId}`),snap=await ref.get();if(!snap.exists)throw new Error('MANDATE_NOT_FOUND');const mandate=snap.data()||{};if(mandate.appId!==appId||mandate.secretHash!==sha256(parsed.secret))throw new Error('MANDATE_INVALID');return{ref,mandateId:parsed.mandateId,mandate}}

async function resolveCardForMandate(body:Record<string,any>,appId:string){
 const cardReference=normalizeCardReference(body.cardReference);if(cardReference){const card=await resolveCardCapture(cardReference);if(!card)throw new Error('CARD_REFERENCE_NOT_FOUND');const originalExternalReference=normalize(body.originalExternalReference);if(originalExternalReference.length<6||originalExternalReference.length>120)throw new Error('REFERENCE_INVALID');const originalTxId=`devpay_${sha256(`${appId}:${originalExternalReference}`).slice(0,36)}`,originalTx=await db.doc(`wallet_transactions/${originalTxId}`).get();if(!originalTx.exists||originalTx.data()?.status!=='settled')throw new Error('ORIGINAL_PAYMENT_NOT_FOUND');if(String(originalTx.data()?.appId||'')!==appId||String(originalTx.data()?.cardId||'')!==card.cardId)throw new Error('ORIGINAL_PAYMENT_MISMATCH');const createdAt=Number(originalTx.data()?.createdAt||0);if(!createdAt||Date.now()-createdAt>2*60*60*1000)throw new Error('ORIGINAL_PAYMENT_TOO_OLD');if(!expiryIsCurrent(card.expiry))throw new Error('CARD_EXPIRED');return card}
 const cardNumber=normalize(body.cardNumber).replace(/\D/g,''),holder=normalizeUpper(body.cardHolder),expiry=normalize(body.expiry),cvv=normalize(body.cvv);if(!/^5585020002\d{6}$/.test(cardNumber))throw new Error('CARD_INVALID');if(!/^\d{3}$/.test(cvv))throw new Error('CVV_INVALID');if(!/^\d{2}\/\d{2}$/.test(expiry))throw new Error('EXPIRY_INVALID');const identity=await canonicalCardIdentity(cardNumber);if(!identity)throw new Error('CARD_NOT_FOUND');if(identity.status!=='active'||identity.program!=='market_cash_local')throw new Error('CARD_INACTIVE');if(!identity.cardIdentifier)throw new Error('CARD_REFERENCE_NOT_FOUND');if(normalizeUpper(identity.holder)!==holder)throw new Error('HOLDER_MISMATCH');if(identity.expiry.replace(/\s/g,'')!==expiry.replace(/\s/g,''))throw new Error('EXPIRY_MISMATCH');if(!expiryIsCurrent(identity.expiry))throw new Error('CARD_EXPIRED');const security=await db.doc(`user_security/${identity.uid}`).get();if(security.data()?.localTransactionCvvHash!==sha256(cvv))throw new Error('CVV_INVALID');return{cardId:identity.cardId,userId:identity.uid,cardIdentifier:identity.cardIdentifier,cardNumber,cardHolder:identity.holder,expiry:identity.expiry,cardLast4:identity.last4}
}

async function createMandate(params:{appId:string;app:any;developerId:string;body:Record<string,any>}){const card=await resolveCardForMandate(params.body,params.appId),token=createMandateToken(),recurringAllowed=params.body.allowRecurring===true,consentVersion=normalize(params.body.consentVersion||'billing-v1').slice(0,80),now=Date.now();await db.doc(`payment_mandates/${token.mandateId}`).set({mandateId:token.mandateId,secretHash:token.secretHash,appId:params.appId,developerId:params.developerId,clientId:card.userId,cardId:card.cardId,cardIdentifier:card.cardIdentifier,cardLast4:card.cardLast4,cardHolder:card.cardHolder,expiry:card.expiry,status:'active',recurringAllowed,consentVersion,consentSource:'developer_app',consentAt:now,createdAt:now,updatedAt:now});await db.collection('audit_events').add({actorId:params.developerId||params.appId,actorType:'developer_app',action:'MARKET_CASH_PAYMENT_MANDATE_CREATED',resourceId:token.mandateId,appId:params.appId,cardLast4:card.cardLast4,recurringAllowed,createdAt:now}).catch(()=>undefined);return{status:'created',mandateCreated:true,mandateId:token.mandateId,mandateToken:token.token,cardReference:card.cardIdentifier,cardLast4:card.cardLast4,cardHolder:card.cardHolder,expiry:card.expiry,recurringAllowed}}
async function updateMandateConsent(params:{appId:string;developerId:string;body:Record<string,any>}){const loaded=await loadMandate(params.body.mandateToken,params.appId);if(loaded.mandate.status!=='active')throw new Error('MANDATE_INACTIVE');const recurringAllowed=params.body.allowRecurring===true,now=Date.now();await loaded.ref.set({recurringAllowed,consentVersion:normalize(params.body.consentVersion||loaded.mandate.consentVersion||'billing-v1').slice(0,80),consentAt:now,updatedAt:now},{merge:true});return{status:'updated',mandateId:loaded.mandateId,recurringAllowed}}
async function revokeMandate(params:{appId:string;developerId:string;body:Record<string,any>}){const loaded=await loadMandate(params.body.mandateToken,params.appId),now=Date.now();await loaded.ref.set({status:'revoked',recurringAllowed:false,revokedAt:now,updatedAt:now},{merge:true});return{status:'revoked',mandateId:loaded.mandateId}}

async function chargeMandate(params:{appId:string;app:any;developerId:string;developer:any;body:Record<string,any>}){
 const loaded=await loadMandate(params.body.mandateToken,params.appId);if(loaded.mandate.status!=='active')throw new Error('MANDATE_INACTIVE');if(loaded.mandate.recurringAllowed!==true)throw new Error('RECURRING_NOT_AUTHORIZED');
 const currency=parseCurrency(params.body.currency),amount=parseAmount(params.body.amount);ensureCurrencyAllowed(params.app,currency);const externalReference=parseExternalReference(params.body.externalReference),reason=normalize(params.body.reason||`Paiement automatique ${params.app.appName}`),partner=params.developer.businessType==='api_provider',usageFeeUsd=await apiUnitPrice(partner),txId=`devpay_${sha256(`${params.appId}:${externalReference}`).slice(0,36)}`,txRef=db.doc(`wallet_transactions/${txId}`),cardRef=db.doc(`local_cards/${loaded.mandate.cardId}`),cardWalletRef=db.doc(`card_wallet_accounts/${cardAccountId(loaded.mandate.cardId,currency)}`),developerWalletRef=db.doc(`developer_wallet_accounts/${developerWalletId(params.developerId,currency)}`),billingRef=db.doc(`developer_billing_accounts/${billingAccountId(params.developerId)}`),apiRevenueRef=db.doc(`platform_revenue_accounts/${apiRevenueId}`);
 return db.runTransaction(async tx=>{const[existing,mandateSnap,cardSnap,cardWallet,developerWallet,billing,apiRevenue]=await Promise.all([tx.get(txRef),tx.get(loaded.ref),tx.get(cardRef),tx.get(cardWalletRef),tx.get(developerWalletRef),tx.get(billingRef),tx.get(apiRevenueRef)]);if(existing.exists){const data=existing.data()||{};if(data.status!=='settled')throw new Error('PAYMENT_CONFLICT');return{approved:true,status:'approved',duplicate:true,reference:data.reference,externalReference,amount:Number(data.amount||amount),currency,feeAmount:0,totalDebited:Number(data.totalDebited||amount),apiUsageFeeUsd:Number(data.apiUsageFeeUsd||usageFeeUsd),cardBalanceAfter:Number(data.cardBalanceAfter||data.balanceAfter||0)}}
  const currentMandate=mandateSnap.data()||{};if(currentMandate.status!=='active'||currentMandate.recurringAllowed!==true)throw new Error('MANDATE_INACTIVE');if(!cardSnap.exists||cardSnap.data()?.status!=='active')throw new Error('CARD_INACTIVE');const card=cardSnap.data()||{},currentIdentifier=normalizeCardReference(card.cardIdentifier);if(!currentIdentifier||currentIdentifier!==currentMandate.cardIdentifier)throw new Error('CARD_INVALID');const expiry=normalize(card.expiryEnd);if(!expiryIsCurrent(expiry))throw new Error('CARD_EXPIRED');if(expiry.replace(/\s/g,'')!==String(currentMandate.expiry||'').replace(/\s/g,''))throw new Error('EXPIRY_MISMATCH');if(!cardWallet.exists||cardWallet.data()?.status!=='active')throw new Error('CARD_ACCOUNT_INACTIVE');if(!developerWallet.exists||developerWallet.data()?.status!=='active')throw new Error('DEVELOPER_WALLET_INACTIVE');if(!billing.exists||billing.data()?.status!=='active')throw new Error('API_BILLING_ACCOUNT_INACTIVE');const billingBalance=Number(billing.data()?.availableBalance||0);if(billingBalance<usageFeeUsd)throw new Error('API_BILLING_BALANCE_LOW');const cardBalance=Number(cardWallet.data()?.availableBalance||0);if(cardBalance<amount)throw new Error('INSUFFICIENT_FUNDS');const developerBalance=Number(developerWallet.data()?.availableBalance||0),apiRevenueBalance=Number(apiRevenue.data()?.availableBalance||0),now=Date.now(),reference=`MC-REC-${now}-${randomBytes(3).toString('hex').toUpperCase()}`,cardBalanceAfter=roundMoney(cardBalance-amount),developerBalanceAfter=roundMoney(developerBalance+amount),billingAfter=roundMoney(billingBalance-usageFeeUsd),apiRevenueAfter=roundMoney(apiRevenueBalance+usageFeeUsd);
  tx.update(cardWalletRef,{availableBalance:cardBalanceAfter,ledgerBalance:roundMoney(Number(cardWallet.data()?.ledgerBalance||cardBalance)-amount),updatedAt:now});tx.update(developerWalletRef,{availableBalance:developerBalanceAfter,ledgerBalance:roundMoney(Number(developerWallet.data()?.ledgerBalance||developerBalance)+amount),updatedAt:now});tx.update(billingRef,{availableBalance:billingAfter,ledgerBalance:roundMoney(Number(billing.data()?.ledgerBalance||billingBalance)-usageFeeUsd),lastUsageAt:now,updatedAt:now});tx.set(apiRevenueRef,{id:apiRevenueRef.id,currency:'USD',availableBalance:apiRevenueAfter,ledgerBalance:apiRevenueAfter,updatedAt:now,createdAt:apiRevenue.data()?.createdAt||now},{merge:true});
  const record={id:txId,reference,externalReference,type:'developer_card_payment',status:'settled',currency,amount,feeAmount:0,clientFeeAmount:0,totalDebited:amount,netAmount:amount,apiUsageFeeUsd:usageFeeUsd,billingModel:'flat_per_successful_payment_request',clientId:currentMandate.clientId,userId:currentMandate.clientId,userIds:[currentMandate.clientId],cardId:currentMandate.cardId,developerId:params.developerId,appId:params.appId,developerName:String(params.developer.companyName||params.app.appName||'Application partenaire'),appName:String(params.app.appName||''),reason,rail:'market_cash_api',source:'MARKET_CASH_RECURRING',recurring:true,storedCredential:true,mandateId:loaded.mandateId,pricingTier:partner?'wholesale':'direct',cardLast4:currentMandate.cardLast4,balanceBefore:cardBalance,balanceAfter:cardBalanceAfter,cardBalanceBefore:cardBalance,cardBalanceAfter,developerBalanceAfter,billingBalanceAfter:billingAfter,adminVisible:true,createdAt:now,updatedAt:now};
  tx.set(txRef,record);tx.update(loaded.ref,{lastUsedAt:now,updatedAt:now});tx.set(db.collection('ledger_entries').doc(),{transactionId:txId,cardWalletId:cardWalletRef.id,userId:currentMandate.clientId,direction:'debit',amount,currency,entryType:'client_card_recurring_payment',createdAt:now});tx.set(db.collection('ledger_entries').doc(),{transactionId:txId,developerWalletId:developerWalletRef.id,developerId:params.developerId,direction:'credit',amount,currency,entryType:'developer_recurring_sale',createdAt:now});tx.set(db.collection('developer_billing_transactions').doc(),{developerId:params.developerId,appId:params.appId,transactionId:txId,type:'api_usage',status:'settled',currency:'USD',amount:usageFeeUsd,direction:'debit',balanceAfter:billingAfter,createdAt:now});tx.set(db.collection('ledger_entries').doc(),{transactionId:txId,revenueWalletId:apiRevenueRef.id,direction:'credit',amount:usageFeeUsd,currency:'USD',entryType:'market_cash_api_usage_revenue',createdAt:now});tx.set(db.collection('notifications').doc(),{userId:currentMandate.clientId,title:'Paiement automatique Market-Cash',message:`${amount} ${currency} payé automatiquement à ${String(params.developer.companyName||params.app.appName||'Application partenaire')}. Aucun frais API prélevé sur votre paiement. Réf: ${reference}.`,type:'success',category:'transaction',transactionId:txId,read:false,createdAt:now});tx.set(db.collection('audit_events').doc(),{actorId:params.developerId||params.appId,actorType:'developer_app',action:'MARKET_CASH_RECURRING_PAYMENT',resourceId:txId,result:'success',clientId:currentMandate.clientId,appId:params.appId,mandateId:loaded.mandateId,amount,currency,apiUsageFeeUsd:usageFeeUsd,billingModel:'flat_per_successful_payment_request',createdAt:now});return{approved:true,status:'approved',duplicate:false,reference,externalReference,amount,currency,feeAmount:0,totalDebited:amount,apiUsageFeeUsd:usageFeeUsd,cardBalanceAfter}}
 )
}

const failureLabel=(code:string)=>({INSUFFICIENT_FUNDS:'Solde insuffisant',CARD_INVALID:'Carte invalide',CARD_NOT_FOUND:'Carte introuvable',CARD_INACTIVE:'Carte inactive',CARD_ACCOUNT_INACTIVE:'Compte carte inactif',CVV_INVALID:'Code de sécurité incorrect',EXPIRY_INVALID:'Date d’expiration invalide',EXPIRY_MISMATCH:'Date d’expiration incorrecte',CARD_EXPIRED:'Carte expirée',DEVELOPER_WALLET_INACTIVE:'Compte bénéficiaire indisponible',MANDATE_INVALID:'Autorisation de paiement invalide',MANDATE_INACTIVE:'Autorisation de paiement inactive',RECURRING_NOT_AUTHORIZED:'Paiement automatique non autorisé',API_BILLING_ACCOUNT_INACTIVE:'Compte de facturation API inactif',API_BILLING_BALANCE_LOW:'Crédit API insuffisant',API_SCOPE_DENIED:'Autorisation API manquante',CURRENCY_NOT_ALLOWED:'Devise non autorisée'}as Record<string,string>)[code]||'Paiement refusé';

async function recordPaymentOutcome(params:{appId:string;app:any;body:Record<string,any>;identity:any;payload:any;approved:boolean}){const{appId,app,body,identity,payload,approved}=params;if(!identity?.uid)return;const externalReference=normalize(body.externalReference);if(!externalReference)return;const currency=String(body.currency||'USD').toUpperCase()==='CDF'?'CDF':'USD',amount=Number(body.amount||0),canonicalTxId=`devpay_${sha256(`${appId}:${externalReference}`).slice(0,36)}`,now=Date.now();if(approved){const ref=db.doc(`wallet_transactions/${canonicalTxId}`),snap=await ref.get();if(!snap.exists)return;const current=snap.data()||{},userIds=Array.from(new Set([...(Array.isArray(current.userIds)?current.userIds:[]),identity.uid]));await ref.set({userIds,balanceAfter:current.balanceAfter??current.cardBalanceAfter,updatedAt:Number(current.updatedAt||now)},{merge:true});return}const code=String(payload?.code||'MARKET_CASH_PAYMENT_DECLINED'),failureId=`devfail_${sha256(`${appId}:${externalReference}`).slice(0,36)}`,wallet=await db.doc(`card_wallet_accounts/${cardAccountId(identity.cardId,currency)}`).get(),balance=Number(wallet.data()?.availableBalance||0),developerId=String(app.developerId||''),developer=developerId?await db.doc(`developer_accounts/${developerId}`).get():null,developerName=String(developer?.data()?.companyName||app.appName||'Application partenaire'),message=`${amount} ${currency} chez ${developerName} : ${failureLabel(code)}. Aucun débit effectué. Solde carte : ${currency==='CDF'?balance.toLocaleString('fr-FR',{maximumFractionDigits:0}):balance.toFixed(2)} ${currency}.`,record={id:failureId,attemptOf:canonicalTxId,externalReference,type:'developer_card_payment',status:'failed',failureCode:code,currency,amount,clientId:identity.uid,userId:identity.uid,userIds:[identity.uid],cardId:identity.cardId,cardLast4:identity.last4,developerId,appId,developerName,appName:String(app.appName||''),reason:normalize(body.reason),rail:'market_cash_api',source:'API_KEY',balanceBefore:balance,balanceAfter:balance,cardBalanceBefore:balance,cardBalanceAfter:balance,adminVisible:true,createdAt:now,updatedAt:now};const batch=db.batch();batch.set(db.doc(`wallet_transactions/${failureId}`),record,{merge:true});batch.set(db.doc(`notifications/payment_${failureId}`),{userId:identity.uid,title:'Paiement Market-Cash refusé',message,type:'error',category:'transaction',transactionId:failureId,read:false,createdAt:now},{merge:true});batch.set(db.doc(`audit_events/payment_${failureId}`),{actorId:developerId||appId,actorType:'developer_app',action:'MARKET_CASH_API_CARD_PAYMENT',resourceId:failureId,result:'failed',failureCode:code,clientId:identity.uid,appId,amount,currency,createdAt:now},{merge:true});await batch.commit()}
function statusForError(code:string){if(code==='UNAUTHORIZED')return 401;if(['DEVELOPER_INACTIVE','API_SCOPE_DENIED','RECURRING_NOT_AUTHORIZED'].includes(code))return 403;if(['MANDATE_NOT_FOUND','CARD_REFERENCE_NOT_FOUND','ORIGINAL_PAYMENT_NOT_FOUND'].includes(code))return 404;if(['INSUFFICIENT_FUNDS','CARD_INACTIVE','CARD_ACCOUNT_INACTIVE','CARD_EXPIRED','DEVELOPER_WALLET_INACTIVE','MANDATE_INACTIVE','API_BILLING_ACCOUNT_INACTIVE','API_BILLING_BALANCE_LOW'].includes(code))return 402;if(['CURRENCY_INVALID','CURRENCY_NOT_ALLOWED','AMOUNT_INVALID','REFERENCE_INVALID','CARD_INVALID','CVV_INVALID','EXPIRY_INVALID','EXPIRY_MISMATCH','HOLDER_MISMATCH','MANDATE_INVALID','ORIGINAL_PAYMENT_MISMATCH','ORIGINAL_PAYMENT_TOO_OLD'].includes(code))return 400;return 500}

export const marketCashApiCardPaymentByKey=onRequest({region:REGION},async(req,res)=>{res.set('Cache-Control','no-store');res.set('X-Content-Type-Options','nosniff');if(req.method!=='POST'){res.status(405).json({status:'error',approved:false,code:'METHOD_NOT_ALLOWED'});return}try{const apiKey=readApiKey(req);if(!apiKey)throw new Error('UNAUTHORIZED');const{appId,app,developerId,developer}=await resolveActiveDeveloperApp(apiKey),body={...(req.body||{})}as Record<string,any>,operation=String(body.operation||'').trim();
 if(operation==='resolve-card'){const card=await resolveCardCapture(body.cardReference);if(!card){res.status(404).json({status:'error',resolved:false,code:'CARD_REFERENCE_NOT_FOUND'});return}res.status(200).json({status:'resolved',resolved:true,cardNumber:card.cardNumber,cardHolder:card.cardHolder,expiry:card.expiry,cardLast4:card.cardLast4});return}
 if(operation==='create-mandate'){res.status(200).json(await createMandate({appId,app,developerId,body}));return}if(operation==='update-mandate-consent'){res.status(200).json(await updateMandateConsent({appId,developerId,body}));return}if(operation==='revoke-mandate'){res.status(200).json(await revokeMandate({appId,developerId,body}));return}if(operation==='charge-mandate'){res.status(200).json(await chargeMandate({appId,app,developerId,developer,body}));return}
 const cardNumber=normalize(body.cardNumber).replace(/\D/g,''),identity=await canonicalCardIdentity(cardNumber);if(identity?.holder)body.cardHolder=identity.holder;const upstream=await fetch(PAYMENT_ENDPOINT,{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'x-market-cash-app-id':appId,'Content-Type':'application/json',Accept:'application/json','User-Agent':'market-cash/api-key-bridge'},body:JSON.stringify(body)}),text=await upstream.text();let payload:any={},parsed=false;try{payload=JSON.parse(text);parsed=true}catch{payload={}}const approved=upstream.ok&&payload?.approved===true&&payload?.status==='approved';await recordPaymentOutcome({appId,app,body,identity,payload,approved}).catch(error=>console.warn('[MARKET_CASH_PAYMENT_OUTCOME_AUDIT_ERROR]',String((error as any)?.message||error)));if(approved&&identity?.cardIdentifier){res.status(upstream.status).json({...payload,cardReference:identity.cardIdentifier,cardLast4:identity.last4,cardHolder:identity.holder,expiry:identity.expiry});return}if(parsed){res.status(upstream.status).json(payload);return}res.status(upstream.status);res.set('Content-Type',upstream.headers.get('content-type')||'text/plain; charset=utf-8');res.send(text)}catch(error:any){const code=String(error?.message||'INTERNAL_ERROR'),status=statusForError(code);console.warn('[MARKET_CASH_API_KEY_BRIDGE_ERROR]',code);res.status(status).json({status:'declined',approved:false,code,message:failureLabel(code)})}});
