import{createHash}from'node:crypto';
import{getApps,initializeApp}from'firebase-admin/app';
import{getFirestore}from'firebase-admin/firestore';
import{HttpsError,onCall}from'firebase-functions/v2/https';
if(!getApps().length)initializeApp();
const db=getFirestore();const REGION='europe-west1';
type UpgradeType='agent'|'marchand'|'developer_direct'|'api_partner';
const sha=(v:string)=>createHash('sha256').update(v).digest('hex');
const devId=(uid:string)=>`DEV-${sha(`developer:${uid}`).slice(0,10).toUpperCase()}`;
const devWalletId=(developerId:string,currency:'USD'|'CDF')=>`dev_${currency.toLowerCase()}_${developerId}`;
const clean=(v:any)=>String(v||'').trim();
function authUid(r:any){const uid=String(r.auth?.uid||'');if(!uid)throw new HttpsError('unauthenticated','Connexion requise.');return uid}
async function adminRole(uid:string){const s=await db.doc(`users/${uid}`).get();const role=String(s.data()?.role||'');if(!['admin_general','agent_administratif'].includes(role))throw new HttpsError('permission-denied','Accès administratif requis.');return role}
async function notify(userId:string,title:string,message:string,type:'success'|'error'|'info'='info'){await db.collection('notifications').add({userId,title,message,type,category:'general',read:false,createdAt:Date.now()}).catch(()=>{})}
async function ensureDevWallets(developerId:string,uid:string,status='active'){const now=Date.now(),batch=db.batch();for(const currency of ['USD','CDF']as const){const ref=db.doc(`developer_wallet_accounts/${devWalletId(developerId,currency)}`);batch.set(ref,{id:ref.id,developerId,userId:uid,currency,availableBalance:0,ledgerBalance:0,heldBalance:0,status,updatedAt:now,createdAt:now},{merge:true})}await batch.commit()}
export const submitBusinessUpgrade=onCall({region:REGION},async r=>{const uid=authUid(r);const u=await db.doc(`users/${uid}`).get();if(!u.exists)throw new HttpsError('not-found','Compte introuvable.');if(u.data()?.role!=='client')throw new HttpsError('failed-precondition','Ce compte est déjà professionnel.');if(u.data()?.kycStatus!=='approved')throw new HttpsError('failed-precondition','Votre identité KYC doit être approuvée.');const requestedType=clean(r.data?.requestedType)as UpgradeType;if(!['agent','marchand','developer_direct','api_partner'].includes(requestedType))throw new HttpsError('invalid-argument','Type de compte invalide.');const legalName=clean(r.data?.legalName),activity=clean(r.data?.activity),city=clean(r.data?.city),address=clean(r.data?.address);if(!legalName||!activity||!city||!address)throw new HttpsError('invalid-argument','Informations professionnelles incomplètes.');const now=Date.now();let developerId='';if(requestedType==='developer_direct'||requestedType==='api_partner'){developerId=devId(uid);await db.doc(`developer_accounts/${developerId}`).set({developerId,userId:uid,companyName:clean(r.data?.tradeName)||legalName,contactEmail:clean(r.data?.email)||clean(u.data()?.email),businessType:requestedType==='api_partner'?'api_provider':'direct_developer',pricingTier:requestedType==='api_partner'?'wholesale':'direct',status:'pending',partnerEnabled:false,createdAt:now,updatedAt:now},{merge:true})}
await db.doc(`account_upgrade_requests/${uid}`).set({...r.data,userId:uid,requestedType,developerId,status:'pending',rejectionReason:'',termsAcceptedAt:now,createdAt:now,updatedAt:now},{merge:true});await notify(uid,'Demande professionnelle reçue','Votre demande est en cours de vérification par Market-Cash.','info');return{ok:true,status:'pending',requestedType,developerId:developerId||undefined}});
export const reviewBusinessUpgrade=onCall({region:REGION},async r=>{const adminUid=authUid(r);const role=await adminRole(adminUid);const userId=clean(r.data?.userId);const decision=clean(r.data?.decision);if(!userId||!['approved','rejected'].includes(decision))throw new HttpsError('invalid-argument','Demande invalide.');const ref=db.doc(`account_upgrade_requests/${userId}`),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Demande introuvable.');const d=snap.data()!,type=String(d.requestedType||'')as UpgradeType;if((type==='developer_direct'||type==='api_partner')&&role!=='admin_general')throw new HttpsError('permission-denied','La validation Developer/API Partner est réservée à l’Administrateur Général.');const now=Date.now(),reason=clean(r.data?.rejectionReason);if(decision==='rejected'){if(!reason)throw new HttpsError('invalid-argument','Motif du rejet requis.');await ref.set({status:'rejected',rejectionReason:reason,reviewedAt:now,reviewedBy:adminUid,updatedAt:now},{merge:true});if(d.developerId)await db.doc(`developer_accounts/${d.developerId}`).set({status:'rejected',updatedAt:now},{merge:true});await notify(userId,'Demande professionnelle rejetée',`Votre demande a été rejetée. Motif : ${reason}`,'error');return{ok:true,status:'rejected'}}
if(type==='agent'){await db.doc(`users/${userId}`).set({role:'agent',businessAccountType:'agent',updatedAt:now},{merge:true});await db.doc(`agent_profiles/${userId}`).set({userId,status:'active',legalName:d.legalName||'',pointName:d.pointName||'',activity:d.activity||'',phone:d.phone||'',email:d.email||'',city:d.city||'',address:d.address||'',approvedBy:adminUid,approvedAt:now,updatedAt:now,createdAt:d.createdAt||now},{merge:true})}
else if(type==='marchand'){await db.doc(`users/${userId}`).set({role:'marchand',businessAccountType:'merchant',updatedAt:now},{merge:true});await db.doc(`merchant_profiles/${userId}`).set({userId,status:'active',legalName:d.legalName||'',tradeName:d.tradeName||'',activity:d.activity||'',phone:d.phone||'',email:d.email||'',city:d.city||'',address:d.address||'',approvedBy:adminUid,approvedAt:now,updatedAt:now,createdAt:d.createdAt||now},{merge:true})}
else{const developerId=d.developerId||devId(userId),businessType=type==='api_partner'?'api_provider':'direct_developer';await db.doc(`users/${userId}`).set({role:'marchand',businessAccountType:businessType,developerEnabled:true,apiProviderEnabled:type==='api_partner',updatedAt:now},{merge:true});await db.doc(`developer_accounts/${developerId}`).set({developerId,userId,businessType,pricingTier:type==='api_partner'?'wholesale':'direct',status:'active',partnerEnabled:type==='api_partner',approvedBy:adminUid,approvedAt:now,updatedAt:now},{merge:true});await ensureDevWallets(developerId,userId,'active')}
await ref.set({status:'approved',reviewedAt:now,reviewedBy:adminUid,updatedAt:now},{merge:true});await notify(userId,'Compte professionnel activé',type==='api_partner'?'Votre compte Partenaire API Market-Cash est actif.':type==='developer_direct'?'Votre Developer Console Market-Cash est active.':type==='agent'?'Votre compte Agent Market-Cash est actif.':'Votre compte Marchand Market-Cash est actif.','success');return{ok:true,status:'approved',requestedType:type}});
