import { createHash } from 'node:crypto';
import { initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { HttpsError, onCall } from 'firebase-functions/v2/https';

initializeApp();
const db = getFirestore();
const REGION = 'europe-west1';
const CURRENCIES = ['USD','CDF'] as const;
type Currency = typeof CURRENCIES[number];
const sha256=(v:string)=>createHash('sha256').update(v).digest('hex');
const walletId=(uid:string,c:Currency)=>`wallet_${c.toLowerCase()}_${uid}`;
const rechargeNumberForUid=(uid:string)=>(BigInt(`0x${sha256(uid).slice(0,15)}`)%100000000000n).toString().padStart(11,'0');
const requireAuth=(r:any)=>{if(!r.auth?.uid)throw new HttpsError('unauthenticated','Connexion requise.');return r.auth.uid as string};
const getRole=async(uid:string)=>(await db.doc(`users/${uid}`).get()).data()?.role as string|undefined;
const requireAdmin=async(uid:string)=>{if(await getRole(uid)!=='admin_general')throw new HttpsError('permission-denied','Administrateur requis.')};
const requireAgent=async(uid:string)=>{const s=await db.doc(`agent_profiles/${uid}`).get();if(!s.exists||s.data()?.status!=='active')throw new HttpsError('permission-denied','Compte agent non autorisé.');return s.data()!};
const parseCurrency=(v:any):Currency=>{if(!CURRENCIES.includes(v))throw new HttpsError('invalid-argument','Devise invalide.');return v};
const parseAmount=(v:any)=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new HttpsError('invalid-argument','Montant invalide.');return Math.round(n*100)/100};

async function ensureWalletDocs(uid:string,accountType:'client'|'agent'|'business'='client'){
  const rechargeNumber=rechargeNumberForUid(uid),now=Date.now(),batch=db.batch();
  for(const currency of CURRENCIES){const ref=db.doc(`wallet_accounts/${walletId(uid,currency)}`);if(!(await ref.get()).exists)batch.set(ref,{id:ref.id,userId:uid,accountType,currency,availableBalance:0,ledgerBalance:0,heldBalance:0,status:'active',rechargeNumber,createdAt:now,updatedAt:now});}
  const map=db.doc(`wallet_recharge_numbers/${rechargeNumber}`);if(!(await map.get()).exists)batch.set(map,{userId:uid,rechargeNumber,createdAt:now});await batch.commit();return rechargeNumber;
}

export const ensureWalletProfile=onCall({region:REGION},async r=>{const uid=requireAuth(r);const isAgent=(await db.doc(`agent_profiles/${uid}`).get()).exists;const rechargeNumber=await ensureWalletDocs(uid,isAgent?'agent':'client');return{ok:true,rechargeNumber,isAgent}});

export const adminRegisterAgent=onCall({region:REGION},async r=>{const adminUid=requireAuth(r);await requireAdmin(adminUid);const agentUid=String(r.data?.agentUid||'');const user=await db.doc(`users/${agentUid}`).get();if(!user.exists)throw new HttpsError('not-found','Utilisateur introuvable.');const now=Date.now();await db.doc(`agent_profiles/${agentUid}`).set({userId:agentUid,status:'active',createdBy:adminUid,createdAt:now,updatedAt:now},{merge:true});await ensureWalletDocs(agentUid,'agent');return{ok:true}});

export const lookupRechargeClient=onCall({region:REGION},async r=>{const agentUid=requireAuth(r);await requireAgent(agentUid);const rechargeNumber=String(r.data?.rechargeNumber||'').replace(/\D/g,'');const map=await db.doc(`wallet_recharge_numbers/${rechargeNumber}`).get();if(!map.exists)throw new HttpsError('not-found','Client introuvable.');const userId=map.data()!.userId;const user=(await db.doc(`users/${userId}`).get()).data();if(!user)throw new HttpsError('not-found','Profil client introuvable.');const balances:any={};for(const c of CURRENCIES){balances[c]=(await db.doc(`wallet_accounts/${walletId(userId,c)}`).get()).data()?.availableBalance??0}return{userId,displayName:user.displayName||'Client',phone:user.phone||'',rechargeNumber,balances}});

async function executeAgentTransfer(input:{agentUid:string;clientUid:string;currency:Currency;amount:number;direction:'cash_in'|'cash_out';pin:string;idempotencyKey:string}){
 const{agentUid,clientUid,currency,amount,direction,pin,idempotencyKey}=input;const txRef=db.doc(`wallet_transactions/${idempotencyKey}`);
 return db.runTransaction(async tx=>{const existing=await tx.get(txRef);if(existing.exists)return{duplicate:true,...existing.data()};const agentUserRef=db.doc(`users/${agentUid}`),clientUserRef=db.doc(`users/${clientUid}`),agentWalletRef=db.doc(`wallet_accounts/${walletId(agentUid,currency)}`),clientWalletRef=db.doc(`wallet_accounts/${walletId(clientUid,currency)}`);const[agentUser,clientUser,agentWallet,clientWallet]=await Promise.all([tx.get(agentUserRef),tx.get(clientUserRef),tx.get(agentWalletRef),tx.get(clientWalletRef)]);if(!agentUser.exists||!clientUser.exists)throw new HttpsError('not-found','Compte introuvable.');if(agentUser.data()?.pinHash!==sha256(pin))throw new HttpsError('permission-denied','Code secret agent incorrect.');if(!agentWallet.exists||!clientWallet.exists)throw new HttpsError('failed-precondition','Portefeuille non initialisé.');const a=agentWallet.data()!,c=clientWallet.data()!;if(a.status!=='active'||c.status!=='active')throw new HttpsError('failed-precondition','Portefeuille indisponible.');const debitRef=direction==='cash_in'?agentWalletRef:clientWalletRef,creditRef=direction==='cash_in'?clientWalletRef:agentWalletRef,debit=direction==='cash_in'?a:c,credit=direction==='cash_in'?c:a;if(Number(debit.availableBalance||0)<amount)throw new HttpsError('failed-precondition',direction==='cash_in'?'Solde agent insuffisant.':'Solde client insuffisant.');const now=Date.now(),reference=`MC-${direction==='cash_in'?'DEP':'RET'}-${now}`;tx.update(debitRef,{availableBalance:Number(debit.availableBalance)-amount,ledgerBalance:Number(debit.ledgerBalance)-amount,updatedAt:now});tx.update(creditRef,{availableBalance:Number(credit.availableBalance)+amount,ledgerBalance:Number(credit.ledgerBalance)+amount,updatedAt:now});tx.set(txRef,{id:idempotencyKey,reference,type:direction,status:'settled',currency,amount,agentId:agentUid,clientId:clientUid,sourceWalletId:debitRef.id,destinationWalletId:creditRef.id,rail:'agent_terminal',createdAt:now,updatedAt:now});tx.set(db.collection('ledger_entries').doc(),{transactionId:idempotencyKey,walletId:debitRef.id,direction:'debit',amount,currency,createdAt:now});tx.set(db.collection('ledger_entries').doc(),{transactionId:idempotencyKey,walletId:creditRef.id,direction:'credit',amount,currency,createdAt:now});tx.set(db.collection('audit_events').doc(),{actorId:agentUid,actorType:'agent',action:direction==='cash_in'?'AGENT_CASH_IN':'AGENT_CASH_OUT',resourceId:idempotencyKey,result:'success',clientId:clientUid,amount,currency,createdAt:now});return{ok:true,reference,transactionId:idempotencyKey}})}

async function resolveClient(rechargeNumber:string){const map=await db.doc(`wallet_recharge_numbers/${rechargeNumber}`).get();if(!map.exists)throw new HttpsError('not-found','Client introuvable.');return map.data()!.userId as string}
export const agentCashIn=onCall({region:REGION},async r=>{const agentUid=requireAuth(r);await requireAgent(agentUid);const recharge=String(r.data?.rechargeNumber||'').replace(/\D/g,'');return executeAgentTransfer({agentUid,clientUid:await resolveClient(recharge),currency:parseCurrency(r.data?.currency),amount:parseAmount(r.data?.amount),direction:'cash_in',pin:String(r.data?.pin||''),idempotencyKey:String(r.data?.idempotencyKey||`cashin_${agentUid}_${Date.now()}`)})});
export const agentCashOut=onCall({region:REGION},async r=>{const agentUid=requireAuth(r);await requireAgent(agentUid);const recharge=String(r.data?.rechargeNumber||'').replace(/\D/g,'');return executeAgentTransfer({agentUid,clientUid:await resolveClient(recharge),currency:parseCurrency(r.data?.currency),amount:parseAmount(r.data?.amount),direction:'cash_out',pin:String(r.data?.pin||''),idempotencyKey:String(r.data?.idempotencyKey||`cashout_${agentUid}_${Date.now()}`)})});

export const adminFundAgentFloat=onCall({region:REGION},async r=>{const adminUid=requireAuth(r);await requireAdmin(adminUid);const agentUid=String(r.data?.agentUid||''),currency=parseCurrency(r.data?.currency),amount=parseAmount(r.data?.amount),reason=String(r.data?.reason||'').trim();if(reason.length<5)throw new HttpsError('invalid-argument','Motif obligatoire.');await requireAgent(agentUid);await ensureWalletDocs(agentUid,'agent');const ref=db.doc(`wallet_accounts/${walletId(agentUid,currency)}`),id=`fund_${agentUid}_${Date.now()}`;await db.runTransaction(async tx=>{const snap=await tx.get(ref),w=snap.data()!,now=Date.now();tx.update(ref,{availableBalance:Number(w.availableBalance||0)+amount,ledgerBalance:Number(w.ledgerBalance||0)+amount,updatedAt:now});tx.set(db.doc(`wallet_transactions/${id}`),{id,reference:`MC-FLOAT-${now}`,type:'agent_float_funding',status:'settled',currency,amount,agentId:agentUid,approvedBy:adminUid,reason,createdAt:now,updatedAt:now});tx.set(db.collection('audit_events').doc(),{actorId:adminUid,action:'AGENT_FLOAT_FUNDED',agentId:agentUid,amount,currency,reason,createdAt:now})});return{ok:true,transactionId:id}});
