import React,{useState}from'react';
import{Link,Outlet,useLocation}from'react-router-dom';
import{Bell,Code2,History,Home,LogOut,Menu,QrCode,User,X}from'lucide-react';
import{cn}from'../../lib/utils';
import{useAuthStore}from'../../store/authStore';
import LogoutModal from'../LogoutModal';

export default function BusinessLayout(){
 const location=useLocation();const{user}=useAuthStore();const[logout,setLogout]=useState(false);const[drawer,setDrawer]=useState(false);
 const role=String(user?.role||'');const mode=role==='api_partner'?'api_provider':role==='developer'?'direct_developer':user?.businessAccountType||'merchant';const developer=role==='developer'||role==='api_partner'||mode==='direct_developer'||mode==='api_provider';
 const nav=developer?[{name:'Accueil',path:'/business/developer-home',icon:Home},{name:'APIs',path:'/business/developer',icon:Code2},{name:'Transactions',path:'/business/developer-transactions',icon:History},{name:'Profil',path:'/business/profile',icon:User}]:[{name:'Accueil',path:'/business/home',icon:Home},{name:'Encaisser',path:'/business/collect',icon:QrCode},{name:'Transactions',path:'/business/history',icon:History},{name:'Profil',path:'/business/profile',icon:User}];
 const home=developer?'/business/developer-home':'/business/home';const title=developer?(mode==='api_provider'||role==='api_partner'?'PARTNER':'DEVELOPER'):'BUSINESS';
 return <div className="min-h-screen bg-slate-50 text-slate-800"><header className="sticky top-0 z-40 flex h-16 items-center justify-between border-b bg-white px-4"><Link to={home} className="font-black text-blue-950">MARKET-<span className="text-amber-500">CASH</span> {title}</Link><div className="flex items-center gap-1"><Link to="/business/notifications" className="rounded-xl p-2 text-blue-950" aria-label="Notifications"><Bell size={21}/></Link><button onClick={()=>setDrawer(true)} className="rounded-xl p-2 text-blue-950" aria-label="Menu"><Menu size={23}/></button></div></header><main className="pb-20"><Outlet/></main><nav className="fixed inset-x-0 bottom-0 z-50 grid h-16 grid-cols-4 border-t bg-white">{nav.map(item=>{const Icon=item.icon;const active=location.pathname.startsWith(item.path);return <Link key={item.name} to={item.path} className={cn('flex flex-col items-center justify-center gap-1 text-[9px] font-black',active?'text-blue-950':'text-slate-400')}><Icon size={19}/><span>{item.name}</span></Link>})}</nav>{drawer&&<div className="fixed inset-0 z-[80] bg-slate-950/40" onClick={()=>setDrawer(false)}><aside className="ml-auto h-full w-[82%] max-w-sm bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><b className="text-lg">Menu Market-Cash</b><button onClick={()=>setDrawer(false)} className="p-2"><X/></button></div><div className="mt-6 space-y-2"><Link onClick={()=>setDrawer(false)} to={home} className="block rounded-2xl bg-slate-50 p-4 font-black">Accueil</Link><Link onClick={()=>setDrawer(false)} to="/business/notifications" className="block rounded-2xl bg-slate-50 p-4 font-black">Notifications</Link><Link onClick={()=>setDrawer(false)} to="/business/profile" className="block rounded-2xl bg-slate-50 p-4 font-black">Profil & paramètres</Link><button onClick={()=>{setDrawer(false);setLogout(true)}} className="flex w-full items-center gap-2 rounded-2xl bg-red-50 p-4 font-black text-red-700"><LogOut size={18}/>Se déconnecter</button></div></aside></div>}<LogoutModal isOpen={logout} onClose={()=>setLogout(false)}/></div>
}
