import React,{useEffect,useMemo,useState}from'react';
import{Banknote,CreditCard,Plus,RefreshCw,ShieldCheck,Sparkles,Store,WalletCards}from'lucide-react';
import{QRCodeSVG}from'qrcode.react';
import toast from'react-hot-toast';
import CardProductFace,{CardProductVariant}from'../../components/CardProductFace';
import SecurityConfirmModal from'../../components/SecurityConfirmModal';
import{agentWalletService,InternalCardSummary,LocalCardSecureData}from'../../services/agentWalletService';
import{developerBusinessService}from'../../services/developerBusinessService';
import{cardSecurityService,VisaCardSummary,VisaSecureData}from'../../services/cardSecurityService';
import{cardCache,cardCacheKeys}from'../../services/cardCache';
import{useAuthStore}from'../../store/authStore';

type RevealTarget={kind:CardProductVariant;id:string}|null;
type Action='topup'|'pay'|'withdraw'|null;
const idem=(scope:string)=>`DEV-${scope}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const friendly=(e:any,fallback:string)=>{const raw=String(e?.message||'').trim();const message=raw.replace(/^FirebaseError:\s*/i,'').replace(/^functions\//i,'');return !message||message.toLowerCase().includes('internal [0]')?fallback:message};

export default function BusinessDeveloperCards(){
 const{user}=useAuthStore();const uid=user?.uid||'';
 const initialLocal=uid?cardCache.get<InternalCardSummary[]>(cardCacheKeys.local(uid)):null;const initialVisa=uid?cardCache.get<VisaCardSummary[]>(cardCacheKeys.visa(uid)):null;
 const[localCard,setLocalCard]=useState<InternalCardSummary|null>(initialLocal?.[0]||null);const[localSecure,setLocalSecure]=useState<LocalCardSecureData|null>(null);const[visaCards,setVisaCards]=useState<VisaCardSummary[]>(initialVisa||[]);const[visaSecure,setVisaSecure]=useState<Record<string,VisaSecureData>>({});const[loadingLocal,setLoadingLocal]=useState(!initialLocal);const[loadingVisa,setLoadingVisa]=useState(!initialVisa);const[revealed,setRevealed]=useState<Record<string,boolean>>({});const[pendingReveal,setPendingReveal]=useState<RevealTarget>(null);const[securityBusy,setSecurityBusy]=useState(false);const[action,setAction]=useState<Action>(null);const[currency,setCurrency]=useState<'USD'|'CDF'>('USD');const[amount,setAmount]=useState('');const[target,setTarget]=useState('');const[cvv,setCvv]=useState('');const[busy,setBusy]=useState(false);
 const loadLocal=async()=>{setLoadingLocal(true);try{const cards=await agentWalletService.getMyInternalCards().catch(()=>[]);setLocalCard(cards[0]||initialLocal?.[0]||null);if(uid&&cards.length)cardCache.set(cardCacheKeys.local(uid),cards)}finally{setLoadingLocal(false)}};
 const loadVisa=async()=>{setLoadingVisa(true);try{const cards=await cardSecurityService.getMyVisaCards();setVisaCards(cards);if(uid)cardCache.set(cardCacheKeys.visa(uid),cards)}catch(e){console.warn('[DEV_VISA_LOAD]',e)}finally{setLoadingVisa(false)}};
 useEffect(()=>{void Promise.allSettled([loadLocal(),loadVisa()])},[uid]);
 const standardCards=useMemo(()=>visaCards.filter(card=>card.tier==='standard').slice(0,4),[visaCards]);const goldCard=useMemo(()=>visaCards.find(card=>card.tier==='gold')||null,[visaCards]);const localKey=localCard?.cardId||'local';
 const askReveal=(kind:CardProductVariant,id:string)=>{if(revealed[id]){setRevealed(current=>({...current,[id]:false}));if(kind==='local')setLocalSecure(null);else setVisaSecure(current=>{const next={...current};delete next[id];return next});return}setPendingReveal({kind,id})};
 const confirmReveal=async(pin:string)=>{if(!pendingReveal)return;setSecurityBusy(true);try{if(pendingReveal.kind==='local'){const secure=await developerBusinessService.revealLocalCard(pin);setLocalSecure(secure);}else{const secure=await cardSecurityService.revealVisaCard(pendingReveal.id,pin);setVisaSecure(current=>({...current,[pendingReveal.id]:secure}));}setRevealed(current=>({...current,[pendingReveal.id]:true}));setPendingReveal(null);toast.success('Informations sécurisées affichées.')}catch(e:any){toast.error(friendly(e,'Code secret incorrect ou fonction momentanément indisponible.'))}finally{setSecurityBusy(false)}};
 const resetAction=()=>{setAction(null);setAmount('');setTarget('');setCvv('')};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const value=Number(String(amount).replace(',','.'));if(!localCard?.cardId)return toast.error('Carte locale indisponible.');if(!Number.isFinite(value)||value<=0)return toast.error('Montant invalide.');if(!/^\d{3}$/.test(cvv))return toast.error('CVV Market-Cash à 3 chiffres requis.');setBusy(true);try{if(action==='topup'){const r=await developerBusinessService.topupLocalCard({currency,amount:value,cvv,idempotencyKey:idem('TOPUP')});toast.success(`Carte locale rechargée · ${r.reference}`);}else if(action==='pay'){if(!target.trim())throw new Error('ID marchand requis.');const r=await developerBusinessService.payMerchant({marketCashId:target.trim().toUpperCase(),currency,amount:value,cvv,idempotencyKey:idem('PAY')});toast.success(`Paiement effectué · ${r.reference}`);}resetAction();await loadLocal()}catch(e:any){toast.error(friendly(e,'Opération momentanément indisponible.'))}finally{setBusy(false)}};
 const withdrawalQr=localCard?.qrData||`MARKET-CASH-CARD:${localCard?.cardIdentifier||''}`;
 return <div className="mx-auto max-w-4xl px-3.5 pb-28 pt-4 sm:px-6"><h1 className="mb-6 text-2xl font-black">Cartes</h1>
  <section className="mb-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black uppercase tracking-[.12em] text-blue-950">Market-Cash Locale</h2>{loadingLocal&&<RefreshCw size={15} className="animate-spin text-slate-400"/>}</div>{localCard?<><div className="rounded-[1.65rem]"><CardProductFace variant="local" holder={localSecure?.cardHolder||localCard.cardHolder||user?.displayName} number={localSecure?.cardNumber||localCard.maskedNumber} expiryStart={localSecure?.expiryStart||localCard.expiryStart} expiryEnd={localSecure?.expiryEnd||localCard.expiryEnd} cvv={localSecure?.cvv} qrData={localCard.qrData} revealed={!!revealed[localKey]} onToggleReveal={()=>askReveal('local',localKey)}/></div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>askReveal('local',localKey)} className="flex items-center justify-center gap-2 rounded-2xl border bg-white px-4 py-3 text-sm font-black text-blue-950"><ShieldCheck size={16}/>Détails</button><button onClick={()=>setAction('topup')} className="flex items-center justify-center gap-2 rounded-2xl bg-blue-950 px-4 py-3 text-sm font-black text-white"><Plus size={16}/>Recharger</button></div><div className="mt-3 grid grid-cols-3 gap-2"><button onClick={()=>setAction('topup')} className="rounded-2xl border bg-white px-2 py-4 text-center shadow-sm"><WalletCards className="mx-auto text-blue-700" size={22}/><span className="mt-2 block text-[11px] font-black">Recharger</span></button><button onClick={()=>setAction('pay')} className="rounded-2xl border bg-white px-2 py-4 text-center shadow-sm"><Store className="mx-auto text-blue-700" size={22}/><span className="mt-2 block text-[11px] font-black">Payer</span></button><button onClick={()=>setAction('withdraw')} className="rounded-2xl border bg-white px-2 py-4 text-center shadow-sm"><Banknote className="mx-auto text-blue-700" size={22}/><span className="mt-2 block text-[11px] font-black">Retrait</span></button></div></>:!loadingLocal?<EmptyState icon={<CreditCard size={24}/>} title="Carte locale en synchronisation" text="Votre carte locale Market-Cash n’est pas encore disponible dans cette session. Actualisez ou contactez le support si le problème persiste."/>:null}</section>
  <section className="mb-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black uppercase tracking-[.12em] text-slate-700">Market-Cash Visa Standard</h2>{loadingVisa&&<RefreshCw size={15} className="animate-spin text-slate-400"/>}</div>{standardCards.length?<div className="flex gap-3 overflow-x-auto">{standardCards.map(card=><div key={card.cardId} className="w-[88%] shrink-0"><CardProductFace variant="standard" holder={visaSecure[card.cardId]?.cardHolder||card.cardHolder||user?.displayName} number={visaSecure[card.cardId]?.cardNumber||card.maskedNumber} cvv={visaSecure[card.cardId]?.cvv} revealed={!!revealed[card.cardId]} onToggleReveal={()=>askReveal('standard',card.cardId)}/></div>)}</div>:!loadingVisa?<EmptyState icon={<CreditCard size={24}/>} title="Aucune Visa Standard active" text="Même offre Market-Cash que pour un compte client : jusqu’à quatre Visa Standard."/>:null}</section>
  <section><h2 className="mb-3 text-sm font-black uppercase tracking-[.12em] text-amber-800">Market-Cash Visa Gold</h2>{goldCard?<CardProductFace variant="gold" holder={visaSecure[goldCard.cardId]?.cardHolder||goldCard.cardHolder||user?.displayName} number={visaSecure[goldCard.cardId]?.cardNumber||goldCard.maskedNumber} cvv={visaSecure[goldCard.cardId]?.cvv} revealed={!!revealed[goldCard.cardId]} onToggleReveal={()=>askReveal('gold',goldCard.cardId)}/>:!loadingVisa?<EmptyState icon={<Sparkles size={24}/>} title="Visa Gold non émise" text="Émission via partenaire connecté, avec le même branding Market-Cash." gold/>:null}</section>
  <SecurityConfirmModal open={!!pendingReveal} busy={securityBusy} onClose={()=>!securityBusy&&setPendingReveal(null)} onConfirm={confirmReveal} title="Afficher les informations de la carte" subtitle="Entrez votre code secret actuel de l’application Market-Cash."/>
  {action&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-5">{action==='withdraw'?<><h2 className="text-xl font-black">Retrait Market-Cash</h2><p className="mt-2 text-sm text-slate-500">Présentez cette carte à un Agent Market-Cash. Le retrait est débité uniquement de la carte locale et confirmé avec votre CVV Market-Cash.</p><div className="mt-4 text-center"><div className="inline-block rounded-2xl border bg-white p-3"><QRCodeSVG value={withdrawalQr} size={170}/></div><p className="mt-3 font-mono text-sm font-black text-blue-950">{localCard?.cardIdentifier}</p></div><div className="mt-4 rounded-2xl bg-amber-50 p-3 text-xs leading-5 text-amber-900">Ne communiquez pas votre code secret d’application. Pour le retrait, utilisez seulement le CVV de la carte locale lorsque l’Agent vous le demande.</div><button onClick={resetAction} className="mt-5 w-full rounded-2xl bg-blue-950 p-3 font-black text-white">Fermer</button></>:<form onSubmit={submit}><h2 className="text-xl font-black">{action==='topup'?'Recharger la carte':'Payer un marchand'}</h2><div className="mt-4 flex rounded-xl bg-slate-100 p-1">{(['USD','CDF']as const).map(c=><button type="button" key={c} onClick={()=>setCurrency(c)} className={`flex-1 rounded-lg p-2 font-black ${currency===c?'bg-blue-950 text-white':''}`}>{c}</button>)}</div>{action==='pay'&&<input value={target} onChange={e=>setTarget(e.target.value)} placeholder="ID marchand Market-Cash" className="mt-3 w-full rounded-2xl border p-4"/>}<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Montant" className="mt-3 w-full rounded-2xl border p-4"/><input value={cvv} onChange={e=>setCvv(e.target.value.replace(/\D/g,'').slice(0,3))} inputMode="numeric" type="password" autoComplete="off" placeholder="CVV Market-Cash · 3 chiffres" className="mt-3 w-full rounded-2xl border p-4"/><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={resetAction} className="rounded-2xl border p-3 font-black">Annuler</button><button disabled={busy} className="rounded-2xl bg-blue-950 p-3 font-black text-white disabled:opacity-40">{busy?'Traitement…':'Confirmer'}</button></div></form>}</div></div>}
 </div>;
}
function EmptyState({icon,title,text,gold=false}:{icon:React.ReactNode;title:string;text:string;gold?:boolean}){return <div className={`rounded-[1.75rem] border p-5 ${gold?'border-amber-200 bg-amber-50/70':'bg-white'} shadow-sm`}><div className="grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-blue-950">{icon}</div><h3 className="mt-4 text-lg font-black">{title}</h3><p className="mt-2 text-sm text-slate-500">{text}</p></div>}
