import React,{useEffect,useState}from'react';
import{KeyRound,MoreVertical,RefreshCw,ShieldCheck,Trash2,Users}from'lucide-react';
import toast from'react-hot-toast';
import{developerBusinessService,DeveloperDashboard}from'../../services/developerBusinessService';
import{useAuthStore}from'../../store/authStore';

const FEATURE_LABELS:Record<string,string>={
 'payments.create':'Créer des paiements',
 'transactions.read':'Lire les transactions',
 'balance.read':'Lire les soldes',
 'developers.create':'Créer des sous-développeurs',
 'developers.read':'Lire les sous-développeurs',
};
const DEFAULT_DIRECT=['payments.create','transactions.read','balance.read'];
const DEFAULT_PROVIDER=[...DEFAULT_DIRECT,'developers.create','developers.read'];

type Draft={apiEnabled:boolean;enabledFeatures:string[];allowedCurrencies:string[]};

export default function BusinessDeveloper(){
 const{user}=useAuthStore();const[data,setData]=useState<DeveloperDashboard|null>(null);const[loading,setLoading]=useState(true);const[appName,setAppName]=useState('');const[newKey,setNewKey]=useState('');const[busy,setBusy]=useState(false);const[menuOpen,setMenuOpen]=useState('');const[settingsOpen,setSettingsOpen]=useState('');const[drafts,setDrafts]=useState<Record<string,Draft>>({});const[subDevelopers,setSubDevelopers]=useState<any[]>([]);const[subCompany,setSubCompany]=useState('');const[subEmail,setSubEmail]=useState('');
 const load=async(force=false)=>{try{const d=await developerBusinessService.dashboard(force);setData(d);const next:Record<string,Draft>={};(d.apps||[]).filter((a:any)=>a.status!=='deleted').forEach((a:any)=>{const provider=a.businessType==='api_provider';next[a.appId]={apiEnabled:a.apiEnabled!==false&&a.status!=='disabled',enabledFeatures:Array.isArray(a.enabledFeatures)&&a.enabledFeatures.length?a.enabledFeatures:(a.scopes?.length?a.scopes:(provider?DEFAULT_PROVIDER:DEFAULT_DIRECT)),allowedCurrencies:a.allowedCurrencies?.length?a.allowedCurrencies:['USD','CDF']}});setDrafts(next);if(d.developer?.businessType==='api_provider'){const s=await developerBusinessService.listSubDevelopers();setSubDevelopers(s.developers||[])}}catch(e:any){toast.error(e?.message||'Console API indisponible.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[user?.uid]);
 const createApp=async(e:React.FormEvent)=>{e.preventDefault();const name=appName.trim();if(name.length<2)return;setBusy(true);const wait=toast.loading('Création de la clé API…');try{const r=await developerBusinessService.registerApp(name);setNewKey(r.apiKey);setAppName('');toast.success('Clé API créée. Copiez-la maintenant.',{id:wait});await load(true)}catch(e:any){toast.error(e?.message||'Création impossible.',{id:wait})}finally{setBusy(false)}};
 const save=async(appId:string)=>{const d=drafts[appId];if(!d)return;setBusy(true);try{await developerBusinessService.updateAppSettings({appId,...d});toast.success('Autorisations enregistrées.');setSettingsOpen('');await load(true)}catch(e:any){toast.error(e?.message||'Enregistrement impossible.')}finally{setBusy(false)}};
 const remove=async(appId:string,name:string)=>{setMenuOpen('');if(!window.confirm(`Supprimer définitivement l’accès API de « ${name} » ? La clé cessera immédiatement de fonctionner.`))return;setBusy(true);try{await developerBusinessService.deleteApp(appId);toast.success('Application API supprimée.');if(settingsOpen===appId)setSettingsOpen('');await load(true)}catch(e:any){toast.error(e?.message||'Suppression impossible.')}finally{setBusy(false)}};
 const toggleFeature=(appId:string,f:string)=>setDrafts(p=>{const d=p[appId];return{...p,[appId]:{...d,enabledFeatures:d.enabledFeatures.includes(f)?d.enabledFeatures.filter(x=>x!==f):[...d.enabledFeatures,f]}}});
 const toggleCurrency=(appId:string,c:string)=>setDrafts(p=>{const d=p[appId];return{...p,[appId]:{...d,allowedCurrencies:d.allowedCurrencies.includes(c)?d.allowedCurrencies.filter(x=>x!==c):[...d.allowedCurrencies,c]}}});
 const createSub=async(e:React.FormEvent)=>{e.preventDefault();if(!subCompany.trim()||!subEmail.trim())return;setBusy(true);try{await developerBusinessService.createSubDeveloper({companyName:subCompany.trim(),contactEmail:subEmail.trim()});setSubCompany('');setSubEmail('');toast.success('Sous-développeur créé.');await load(true)}catch(e:any){toast.error(e?.message||'Création impossible.')}finally{setBusy(false)}};
 if(loading)return <div className="mx-auto max-w-3xl p-5"><div className="h-36 animate-pulse rounded-[2rem] bg-slate-200"/></div>;
 const dev=data?.developer;const provider=dev?.businessType==='api_provider';if(!dev)return <div className="mx-auto max-w-2xl p-5"><div className="rounded-[2rem] border bg-white p-6"><ShieldCheck className="text-blue-900"/><h1 className="mt-4 text-2xl font-black">Console Developer en synchronisation</h1><button onClick={()=>load(true)} className="mt-5 flex items-center gap-2 rounded-xl bg-blue-950 px-4 py-3 font-black text-white"><RefreshCw size={16}/>Actualiser</button></div></div>;
 const apps=(data?.apps||[]).filter((a:any)=>a.status!=='deleted');
 return <div className="mx-auto max-w-4xl space-y-5 p-4 pb-28 md:p-8">
  <header><p className="text-xs font-black uppercase tracking-widest text-blue-700">{provider?'Partner APIs':'Developer APIs'}</p><h1 className="text-3xl font-black">Applications & clés API</h1><p className="mt-2 text-sm text-slate-500">Une clé par application. La clé est affichée une seule fois et les autorisations restent modifiables à tout moment.</p></header>
  <div className="rounded-2xl bg-blue-50 p-4 text-sm text-blue-950">{provider?<><b>Facturation Partenaire API :</b> fonds API prépayés, débités selon l’utilisation au tarif partenaire configuré par Market-Cash.</>:<><b>Facturation Developer direct :</b> aucun crédit API à précharger. Market-Cash prélève automatiquement un pourcentage sur chaque paiement reçu, sans supplément pour le client.</>}</div>
  <section className="rounded-[2rem] border bg-white p-5">
   <form onSubmit={createApp} className="flex gap-2"><input value={appName} onChange={e=>setAppName(e.target.value)} placeholder="Nom de l’application" className="min-w-0 flex-1 rounded-2xl border p-3"/><button disabled={busy||appName.trim().length<2} className="rounded-2xl bg-blue-950 px-5 font-black text-white disabled:opacity-40">Créer</button></form>
   {newKey&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-black text-amber-800">CLÉ À COPIER MAINTENANT</p><p className="mt-2 break-all font-mono text-xs">{newKey}</p><button onClick={async()=>{await navigator.clipboard?.writeText(newKey);toast.success('Clé copiée.')}} className="mt-3 rounded-xl bg-white px-3 py-2 text-xs font-black">Copier</button></div>}
   <div className="mt-5 space-y-3">{apps.map((a:any)=>{const d=drafts[a.appId]||{apiEnabled:true,enabledFeatures:DEFAULT_DIRECT,allowedCurrencies:['USD','CDF']};const features=a.businessType==='api_provider'?DEFAULT_PROVIDER:DEFAULT_DIRECT;const open=settingsOpen===a.appId;return <article key={a.appId} className="relative rounded-2xl border p-4">
    <div className="flex items-start justify-between gap-3"><div><h2 className="font-black">{a.appName}</h2><p className="mt-1 font-mono text-[10px] text-slate-500">{a.appId}</p><p className="mt-1 text-xs font-bold text-slate-500">{d.apiEnabled?'API active':'API désactivée'} · {a.businessType==='api_provider'?'partenaire':'direct'}</p></div><button onClick={()=>setMenuOpen(menuOpen===a.appId?'':a.appId)} className="rounded-xl p-2 text-slate-700" aria-label="Actions API"><MoreVertical size={22}/></button></div>
    {menuOpen===a.appId&&<div className="absolute right-4 top-12 z-20 w-48 rounded-2xl border bg-white p-2 shadow-xl"><button onClick={()=>{setSettingsOpen(open?'':a.appId);setMenuOpen('')}} className="w-full rounded-xl px-3 py-3 text-left text-sm font-black hover:bg-slate-50">Paramètres & autorisations</button><button onClick={()=>remove(a.appId,a.appName)} className="flex w-full items-center gap-2 rounded-xl px-3 py-3 text-left text-sm font-black text-red-700 hover:bg-red-50"><Trash2 size={16}/>Supprimer la clé</button></div>}
    {open&&<div className="mt-4 space-y-4 border-t pt-4"><div className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><div><b className="text-sm">Activer cette API</b><p className="text-xs text-slate-500">Désactive immédiatement les appels avec cette clé.</p></div><button onClick={()=>setDrafts(p=>({...p,[a.appId]:{...d,apiEnabled:!d.apiEnabled}}))} className={`h-7 w-12 rounded-full p-1 ${d.apiEnabled?'bg-emerald-500':'bg-slate-300'}`}><span className={`block h-5 w-5 rounded-full bg-white transition ${d.apiEnabled?'translate-x-5':''}`}/></button></div><div><p className="text-xs font-black uppercase text-slate-500">Autorisations</p><div className="mt-2 grid gap-2">{features.map(f=><label key={f} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={d.enabledFeatures.includes(f)} onChange={()=>toggleFeature(a.appId,f)}/>{FEATURE_LABELS[f]}</label>)}</div></div><div><p className="text-xs font-black uppercase text-slate-500">Devises</p><div className="mt-2 flex gap-2">{['USD','CDF'].map(c=><label key={c} className="flex items-center gap-2 rounded-xl border px-4 py-3 font-bold"><input type="checkbox" checked={d.allowedCurrencies.includes(c)} onChange={()=>toggleCurrency(a.appId,c)}/>{c}</label>)}</div></div><button disabled={busy} onClick={()=>save(a.appId)} className="w-full rounded-2xl bg-blue-950 p-3 font-black text-white">Enregistrer</button></div>}
   </article>})}{!apps.length&&<p className="py-6 text-center text-sm text-slate-400">Aucune application API.</p>}</div>
  </section>
  {provider&&<section className="rounded-[2rem] border bg-white p-5"><div className="flex items-center gap-2"><Users className="text-blue-800"/><h2 className="font-black">Développeurs distribués</h2></div><form onSubmit={createSub} className="mt-4 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input value={subCompany} onChange={e=>setSubCompany(e.target.value)} placeholder="Entreprise" className="rounded-2xl border p-3"/><input value={subEmail} onChange={e=>setSubEmail(e.target.value)} type="email" placeholder="Email" className="rounded-2xl border p-3"/><button disabled={busy} className="rounded-2xl bg-blue-950 px-4 font-black text-white">Ajouter</button></form><div className="mt-3 divide-y">{subDevelopers.map((s:any)=><div key={s.subDeveloperId} className="py-3"><b className="text-sm">{s.companyName}</b><p className="text-xs text-slate-500">{s.contactEmail}</p></div>)}</div></section>}
 </div>;
}
