import React,{useEffect,useState}from'react';
import{Copy,CreditCard,Landmark,ReceiptText,Send,WalletCards}from'lucide-react';
import{Link}from'react-router-dom';
import toast from'react-hot-toast';
import{developerBusinessService,DeveloperDashboard}from'../../services/developerBusinessService';
import{agentWalletService,InternalCardSummary,WalletServerSnapshot}from'../../services/agentWalletService';
import{professionalBusinessService}from'../../services/professionalBusinessService';

const money=(n:any,c:string)=>`${Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:c==='CDF'?0:2})} ${c}`;
const opKey=(scope:string)=>`${scope}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
const friendly=(e:any,fallback:string)=>{const text=String(e?.message||'');return !text||text.toLowerCase().includes('internal [0]')?fallback:text};

type Action='send'|'card-topup'|null;
export default function BusinessDeveloperHome(){
 const[data,setData]=useState<DeveloperDashboard|null>(null);const[wallet,setWallet]=useState<WalletServerSnapshot|null>(null);const[card,setCard]=useState<InternalCardSummary|null>(null);const[billing,setBilling]=useState<any>(null);const[loading,setLoading]=useState(true);const[transferOpen,setTransferOpen]=useState(false);const[billingOpen,setBillingOpen]=useState(false);const[action,setAction]=useState<Action>(null);const[currency,setCurrency]=useState<'USD'|'CDF'>('USD');const[amount,setAmount]=useState('');const[billingAmount,setBillingAmount]=useState('');const[target,setTarget]=useState('');const[cvv,setCvv]=useState('');const[busy,setBusy]=useState(false);
 const load=async(force=false)=>{setLoading(true);const results=await Promise.allSettled([developerBusinessService.dashboard(force),agentWalletService.getMyWallets(),agentWalletService.getMyInternalCards(),developerBusinessService.billing()]);const[d,w,cards,b]=results;if(d.status==='fulfilled')setData(d.value);if(w.status==='fulfilled')setWallet(w.value);if(cards.status==='fulfilled')setCard(cards.value[0]||null);if(b.status==='fulfilled')setBilling(b.value);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const resetAction=()=>{setAction(null);setAmount('');setTarget('');setCvv('')};
 const transfer=async(e:React.FormEvent)=>{e.preventDefault();const value=Number(amount);if(!Number.isFinite(value)||value<=0)return toast.error('Montant invalide.');setBusy(true);try{await professionalBusinessService.developerToLocalCard({currency,amount:value});developerBusinessService.invalidate();toast.success('Revenus transférés vers la carte locale.');setAmount('');setTransferOpen(false);await load(true)}catch(e:any){toast.error(friendly(e,'Transfert momentanément indisponible.'))}finally{setBusy(false)}};
 const fundBilling=async(e:React.FormEvent)=>{e.preventDefault();const value=Number(billingAmount);if(!Number.isFinite(value)||value<=0)return toast.error('Montant invalide.');setBusy(true);try{const r=await developerBusinessService.fundBilling(value);toast.success(`Compte API crédité : ${money(r.balance,'USD')}`);setBillingAmount('');setBillingOpen(false);await load(true)}catch(e:any){toast.error(friendly(e,'Crédit de facturation momentanément indisponible.'))}finally{setBusy(false)}};
 const runAction=async(e:React.FormEvent)=>{e.preventDefault();const value=Number(amount);if(!Number.isFinite(value)||value<=0)return toast.error('Montant invalide.');if(!/^\d{3}$/.test(cvv))return toast.error('CVV à 3 chiffres requis.');setBusy(true);try{if(action==='send'){if(!target.trim())throw new Error('Identifiant destinataire requis.');await agentWalletService.transferMarketCash({marketCashId:target.trim(),currency,amount:value,cvv,idempotencyKey:opKey('send')})}else{if(!card?.cardId)throw new Error('Carte locale indisponible.');await agentWalletService.fundInternalCard({cardId:card.cardId,currency,amount:value,cvv,idempotencyKey:opKey('card-topup')})}toast.success(action==='send'?'Transfert effectué.':'Carte locale alimentée.');resetAction();await load(true)}catch(e:any){toast.error(friendly(e,'Opération momentanément indisponible.'))}finally{setBusy(false)}};
 const copyId=async()=>{const id=wallet?.marketCashId||wallet?.rechargeNumber||'';if(!id)return toast('Identifiant en synchronisation.');await navigator.clipboard?.writeText(id);toast.success('Identifiant Market-Cash copié.')};
 const dev=data?.developer,provider=dev?.businessType==='api_provider';
 return <div className="mx-auto max-w-4xl space-y-5 p-4 pb-28 md:p-8">
  <header><p className="text-xs font-black uppercase tracking-widest text-blue-700">{provider?'Partner Home':'Developer Home'}</p><h1 className="text-3xl font-black">{dev?.companyName||'Market-Cash Developer'}</h1><p className="mt-2 text-sm text-slate-500">Vue financière claire : revenus, facturation API, wallet personnel puis carte locale.</p></header>
  <section className="rounded-[2rem] border bg-white p-5"><div className="flex items-center gap-2"><Landmark className="text-blue-800"/><div><h2 className="font-black">Compte revenus Developer</h2><p className="text-xs text-slate-500">Paiements reçus de vos applications.</p></div></div><div className="mt-4 grid grid-cols-2 gap-3">{['USD','CDF'].map(c=><div key={c} className="rounded-2xl bg-slate-50 p-4"><p className="text-[11px] font-black text-slate-400">DISPONIBLE {c}</p><p className="mt-1 text-2xl font-black">{loading&&!data?'—':money(data?.wallets?.[c]?.availableBalance,c)}</p></div>)}</div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setTransferOpen(true)} className="rounded-2xl bg-blue-950 p-3 text-sm font-black text-white">Vers carte locale</button><button onClick={()=>setBillingOpen(true)} className="rounded-2xl border p-3 text-sm font-black">Créditer API</button></div></section>
  <section className="rounded-[2rem] border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-slate-400">COMPTE FACTURATION API</p><p className="mt-1 text-2xl font-black">{billing?money(billing.balance,'USD'):'—'}</p></div><ReceiptText className="text-blue-800"/></div><p className="mt-3 text-sm text-slate-500">Compte séparé, débité uniquement pour l’usage API.</p><p className="mt-2 text-sm font-black text-blue-950">{billing?.unitPrice?.toFixed?.(2)||(provider?'0.05':'0.10')} USD / paiement réussi · ≈ {billing?.estimatedRequests||0} requêtes</p></section>
  <section className="rounded-[2rem] border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-slate-400">WALLET MARKET-CASH PERSONNEL</p><h2 className="mt-1 font-black">{wallet?.marketCashId||'Compte Market-Cash'}</h2></div><WalletCards className="text-blue-800"/></div><div className="mt-4 grid grid-cols-2 gap-3">{(['USD','CDF']as const).map(c=><div key={c} className="rounded-2xl bg-slate-50 p-4"><p className="text-[11px] font-black text-slate-400">SOLDE {c}</p><p className="mt-1 text-xl font-black">{money(wallet?.wallets?.[c]?.availableBalance,c)}</p></div>)}</div><div className="mt-3 grid grid-cols-3 gap-2"><button onClick={()=>setAction('send')} className="flex flex-col items-center gap-1 rounded-2xl border p-3 text-xs font-black"><Send size={17}/>Envoyer</button><button onClick={copyId} className="flex flex-col items-center gap-1 rounded-2xl border p-3 text-xs font-black"><Copy size={17}/>Recevoir</button><button onClick={()=>setAction('card-topup')} className="flex flex-col items-center gap-1 rounded-2xl border p-3 text-xs font-black"><CreditCard size={17}/>Vers carte</button></div></section>
  <section className="rounded-[2rem] border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-slate-400">CARTE LOCALE MARKET-CASH</p><h2 className="mt-1 text-lg font-black">{card?.maskedNumber||'Carte locale en synchronisation'}</h2><p className="mt-1 text-xs text-slate-500">Tous les retraits passent uniquement par cette carte.</p></div><CreditCard className="text-blue-800"/></div><div className="mt-4 grid grid-cols-2 gap-3">{(['USD','CDF']as const).map(c=><div key={c} className="rounded-2xl bg-blue-50 p-4"><p className="text-[11px] font-black text-blue-700">SOLDE {c}</p><p className="mt-1 text-xl font-black text-blue-950">{money(card?.balances?.[c]||0,c)}</p></div>)}</div><Link to="/business/developer-cards" className="mt-4 flex items-center justify-center rounded-2xl bg-blue-50 p-3 text-sm font-black text-blue-950">Ouvrir le module Cartes</Link></section>
  {transferOpen&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={transfer} className="w-full max-w-md rounded-3xl bg-white p-5"><h2 className="text-xl font-black">Revenus → carte locale</h2><div className="mt-4 flex rounded-xl bg-slate-100 p-1">{(['USD','CDF']as const).map(c=><button type="button" key={c} onClick={()=>setCurrency(c)} className={`flex-1 rounded-lg p-2 font-black ${currency===c?'bg-blue-950 text-white':''}`}>{c}</button>)}</div><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Montant" className="mt-3 w-full rounded-2xl border p-4"/><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setTransferOpen(false)} className="rounded-2xl border p-3 font-black">Annuler</button><button disabled={busy} className="rounded-2xl bg-blue-950 p-3 font-black text-white">Confirmer</button></div></form></div>}
  {billingOpen&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={fundBilling} className="w-full max-w-md rounded-3xl bg-white p-5"><h2 className="text-xl font-black">Créditer la facturation API</h2><p className="mt-2 text-sm text-slate-500">Le montant est prélevé uniquement sur le compte revenus USD.</p><input value={billingAmount} onChange={e=>setBillingAmount(e.target.value)} inputMode="decimal" placeholder="Montant USD" className="mt-4 w-full rounded-2xl border p-4"/><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setBillingOpen(false)} className="rounded-2xl border p-3 font-black">Annuler</button><button disabled={busy} className="rounded-2xl bg-blue-950 p-3 font-black text-white">Créditer</button></div></form></div>}
  {action&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={runAction} className="w-full max-w-md rounded-3xl bg-white p-5"><h2 className="text-xl font-black">{action==='send'?'Envoyer Market-Cash':'Wallet → carte locale'}</h2><div className="mt-4 flex rounded-xl bg-slate-100 p-1">{(['USD','CDF']as const).map(c=><button type="button" key={c} onClick={()=>setCurrency(c)} className={`flex-1 rounded-lg p-2 font-black ${currency===c?'bg-blue-950 text-white':''}`}>{c}</button>)}</div>{action==='send'&&<input value={target} onChange={e=>setTarget(e.target.value)} placeholder="ID Market-Cash destinataire" className="mt-3 w-full rounded-2xl border p-4"/>}<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Montant" className="mt-3 w-full rounded-2xl border p-4"/><input value={cvv} onChange={e=>setCvv(e.target.value.replace(/\D/g,'').slice(0,3))} inputMode="numeric" placeholder="CVV Market-Cash · 3 chiffres" className="mt-3 w-full rounded-2xl border p-4"/><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={resetAction} className="rounded-2xl border p-3 font-black">Annuler</button><button disabled={busy} className="rounded-2xl bg-blue-950 p-3 font-black text-white">Confirmer</button></div></form></div>}
 </div>;
}
