import React,{useEffect,useMemo,useState}from'react';
import{Banknote,CreditCard,Plus,RefreshCw,ShieldCheck,Sparkles,Store,WalletCards}from'lucide-react';
import toast from'react-hot-toast';
import CardProductFace,{CardProductVariant}from'../../components/CardProductFace';
import SecurityConfirmModal from'../../components/SecurityConfirmModal';
import{agentWalletService,InternalCardSummary,LocalCardSecureData}from'../../services/agentWalletService';
import{cardSecurityService,VisaCardSummary,VisaSecureData}from'../../services/cardSecurityService';
import{cardCache,cardCacheKeys}from'../../services/cardCache';
import{useAuthStore}from'../../store/authStore';

type RevealTarget={kind:CardProductVariant;id:string}|null;
type Action='topup'|'pay'|'withdraw'|null;
const money=(n:any,c:string)=>`${Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:c==='CDF'?0:2})} ${c}`;
const idem=(scope:string)=>`DEV-${scope}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const friendly=(e:any,fallback:string)=>{const message=String(e?.message||'');return !message||message.toLowerCase().includes('internal [0]')?fallback:message};

export default function BusinessDeveloperCards(){
 const{user}=useAuthStore();const uid=user?.uid||'';
 const initialLocal=uid?cardCache.get<InternalCardSummary[]>(cardCacheKeys.local(uid)):null;const initialVisa=uid?cardCache.get<VisaCardSummary[]>(cardCacheKeys.visa(uid)):null;
 const[localCard,setLocalCard]=useState<InternalCardSummary|null>(initialLocal?.[0]||null);const[localSecure,setLocalSecure]=useState<LocalCardSecureData|null>(null);const[visaCards,setVisaCards]=useState<VisaCardSummary[]>(initialVisa||[]);const[visaSecure,setVisaSecure]=useState<Record<string,VisaSecureData>>({});const[loadingLocal,setLoadingLocal]=useState(!initialLocal);const[loadingVisa,setLoadingVisa]=useState(!initialVisa);const[revealed,setRevealed]=useState<Record<string,boolean>>({});const[pendingReveal,setPendingReveal]=useState<RevealTarget>(null);const[securityBusy,setSecurityBusy]=useState(false);const[action,setAction]=useState<Action>(null);const[currency,setCurrency]=useState<'USD'|'CDF'>('USD');const[amount,setAmount]=useState('');const[target,setTarget]=useState('');const[cvv,setCvv]=useState('');const[busy,setBusy]=useState(false);
 const loadLocal=async()=>{setLoadingLocal(true);try{let cards=await agentWalletService.getMyInternalCards().catch(()=>[]);if(!cards.length){await agentWalletService.ensureLocalCard().catch(()=>null);cards=await agentWalletService.getMyInternalCards().catch(()=>[])}setLocalCard(cards[0]||null);if(uid)cardCache.set(cardCacheKeys.local(uid),cards)}finally{setLoadingLocal(false)}};
 const loadVisa=async()=>{setLoadingVisa(true);try{const cards=await cardSecurityService.getMyVisaCards();setVisaCards(cards);if(uid)cardCache.set(cardCacheKeys.visa(uid),cards)}catch(e){console.warn('[DEV_VISA_LOAD]',e)}finally{setLoadingVisa(false)}};
 useEffect(()=>{void Promise.allSettled([loadLocal(),loadVisa()])},[uid]);
 const standardCards=useMemo(()=>visaCards.filter(card=>card.tier==='standard').slice(0,4),[visaCards]);const goldCard=useMemo(()=>visaCards.find(card=>card.tier==='gold')||null,[visaCards]);
 const localKey=localCard?.cardId||'local';
 const askReveal=(kind:CardProductVariant,id:string)=>{if(revealed[id]){setRevealed(current=>({...current,[id]:false}));if(kind==='local')setLocalSecure(null);else setVisaSecure(current=>{const next={...current};delete next[id];return next});return}setPendingReveal({kind,id})};
 const confirmReveal=async(pin:string)=>{if(!pendingReveal)return;setSecurityBusy(true);try{if(pendingReveal.kind==='local')setLocalSecure(await agentWalletService.revealLocalCardSecureData(pin));else setVisaSecure(current=>({...current,[pendingReveal.id]:await cardSecurityService.revealVisaCard(pendingReveal.id,pin)}));setRevealed(current=>({...current,[pendingReveal.id]:true}));setPendingReveal(null)}catch(e:any){toast.error(e?.message||'Code secret incorrect.')}finally{setSecurityBusy(false)}};
 const resetAction=()=>{setAction(null);setAmount('');setTarget('');setCvv('')};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const value=Number(amount);if(!localCard?.cardId)return toast.error('Carte locale indisponible.');if(!Number.isFinite(value)||value<=0)return toast.error('Montant invalide.');if(!/^\d{3}$/.test(cvv))return toast.error('CVV à 3 chiffres requis.');setBusy(true);try{if(action==='topup'){await agentWalletService.fundInternalCard({cardId:localCard.cardId,currency,amount:value,cvv,idempotencyKey:idem('TOPUP')});toast.success('Carte locale rechargée.')}else if(action==='pay'){if(!target.trim())throw new Error('ID marchand requis.');await agentWalletService.payMerchant({cardId:localCard.cardId,marketCashId:target.trim(),currency,amount:value,cvv,idempotencyKey:idem('PAY')});toast.success('Paiement effectué.')}else{toast('Retrait uniquement via Agent Market-Cash avec validation CVV.');}resetAction();await loadLocal()}catch(e:any){toast.error(friendly(e,'Opération momentanément indisponible.'))}finally{setBusy(false)}};
 return <div className="mx-auto max-w-4xl px-3.5 pb-28 pt-4 sm:px-6"><h1 className="mb-6 text-2xl font-black">Cartes</h1>
  <section className="mb-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black uppercase tracking-[.12em] text-blue-950">Market-Cash Locale</h2>{loadingLocal&&<RefreshCw size={15} className="animate-spin text-slate-400"/>}</div>{localCard?<><div className="rounded-[1.65rem]"><CardProductFace variant="local" holder={localSecure?.cardHolder||localCard.cardHolder||user?.displayName} number={localSecure?.cardNumber||localCard.maskedNumber} expiryStart={localSecure?.expiryStart||localCard.expiryStart} expiryEnd={localSecure?.expiryEnd||localCard.expiryEnd} cvv={localSecure?.cvv} qrData={localCard.qrData} revealed={!!revealed[localKey]} onToggleReveal={()=>askReveal('local',localKey)}/></div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>askReveal('local',localKey)} className="flex items-center justify-center gap-2 rounded-2xl border bg-white px-4 py-3 text-sm font-black text-blue-950"><ShieldCheck size={16}/>Détails</button><button onClick={()=>setAction('topup')} className="flex items-center justify-center gap-2 rounded-2xl bg-blue-950 px-4 py-3 text-sm font-black text-white"><Plus size={16}/>Recharger</button></div><div className="mt-3 grid grid-cols-3 gap-2"><button onClick={()=>setAction('topup')} className="rounded-2xl border bg-white px-2 py-4 text-center shadow-sm"><WalletCards className="mx-auto text-blue-700" size={22}/><span className="mt-2 block text-[11px] font-black">Recharger</span></button><button onClick={()=>setAction('pay')} className="rounded-2xl border bg-white px-2 py-4 text-center shadow-sm"><Store className="mx-auto text-blue-700" size={22}/><span className="mt-2 block text-[11px] font-black">Payer</span></button><button onClick={()=>setAction('withdraw')} className="rounded-2xl border bg-white px-2 py-4 text-center shadow-sm"><Banknote className="mx-auto text-blue-700" size={22}/><span className="mt-2 block text-[11px] font-black">Retrait</span></button></div></>:!loadingLocal?<EmptyState icon={<CreditCard size={24}/>} title="Carte locale en synchronisation" text="Votre carte locale gratuite est créée automatiquement pour votre compte Market-Cash."/>:null}</section>
  <section className="mb-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black uppercase tracking-[.12em] text-slate-700">Market-Cash Visa Standard</h2>{loadingVisa&&<RefreshCw size={15} className="animate-spin text-slate-400"/>}</div>{standardCards.length?<div className="flex gap-3 overflow-x-auto">{standardCards.map(card=><div key={card.cardId} className="w-[88%] shrink-0"><CardProductFace variant="standard" holder={visaSecure[card.cardId]?.cardHolder||card.cardHolder||user?.displayName} number={visaSecure[card.cardId]?.cardNumber||card.maskedNumber} cvv={visaSecure[card.cardId]?.cvv} revealed={!!revealed[card.cardId]} onToggleReveal={()=>askReveal('standard',card.cardId)}/></div>)}</div>:!loadingVisa?<EmptyState icon={<CreditCard size={24}/>} title="Aucune Visa Standard active" text="Même offre Market-Cash que pour un compte client : jusqu’à quatre Visa Standard."/>:null}</section>
  <section><h2 className="mb-3 text-sm font-black uppercase tracking-[.12em] text-amber-800">Market-Cash Visa Gold</h2>{goldCard?<CardProductFace variant="gold" holder={visaSecure[goldCard.cardId]?.cardHolder||goldCard.cardHolder||user?.displayName} number={visaSecure[goldCard.cardId]?.cardNumber||goldCard.maskedNumber} cvv={visaSecure[goldCard.cardId]?.cvv} revealed={!!revealed[goldCard.cardId]} onToggleReveal={()=>askReveal('gold',goldCard.cardId)}/>:!loadingVisa?<EmptyState icon={<Sparkles size={24}/>} title="Visa Gold non émise" text="Émission via partenaire connecté, avec le même branding Market-Cash." gold/>:null}</section>
  <SecurityConfirmModal open={!!pendingReveal} busy={securityBusy} onClose={()=>!securityBusy&&setPendingReveal(null)} onConfirm={confirmReveal} title="Afficher les informations de la carte" subtitle="Entrez le code secret de l’application."/>
  {action&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-5"><h2 className="text-xl font-black">{action==='topup'?'Recharger la carte':action==='pay'?'Payer un marchand':'Retrait Market-Cash'}</h2>{action==='withdraw'?<p className="mt-3 text-sm text-slate-500">Le retrait passe uniquement par votre carte locale chez un Agent Market-Cash. L’agent initie l’opération et vous confirmez avec le CVV.</p>:<><div className="mt-4 flex rounded-xl bg-slate-100 p-1">{(['USD','CDF']as const).map(c=><button type="button" key={c} onClick={()=>setCurrency(c)} className={`flex-1 rounded-lg p-2 font-black ${currency===c?'bg-blue-950 text-white':''}`}>{c}</button>)}</div>{action==='pay'&&<input value={target} onChange={e=>setTarget(e.target.value)} placeholder="ID marchand Market-Cash" className="mt-3 w-full rounded-2xl border p-4"/>}<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Montant" className="mt-3 w-full rounded-2xl border p-4"/><input value={cvv} onChange={e=>setCvv(e.target.value.replace(/\D/g,'').slice(0,3))} inputMode="numeric" placeholder="CVV · 3 chiffres" className="mt-3 w-full rounded-2xl border p-4"/></>}</form><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={resetAction} className="rounded-2xl border p-3 font-black">Fermer</button>{action!=='withdraw'&&<button disabled={busy} onClick={submit as any} className="rounded-2xl bg-blue-950 p-3 font-black text-white">Confirmer</button>}</div></div>}
 </div>;
}
function EmptyState({icon,title,text,gold=false}:{icon:React.ReactNode;title:string;text:string;gold?:boolean}){return <div className={`rounded-[1.75rem] border p-5 ${gold?'border-amber-200 bg-amber-50/70':'bg-white'} shadow-sm`}><div className="grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-blue-950">{icon}</div><h3 className="mt-4 text-lg font-black">{title}</h3><p className="mt-2 text-sm text-slate-500">{text}</p></div>}
