import React,{useEffect,useState}from'react';
import{Building2,Edit3,Fingerprint,KeyRound,LogOut,ShieldCheck,WalletCards}from'lucide-react';
import{doc,updateDoc}from'firebase/firestore';
import toast from'react-hot-toast';
import LogoutModal from'../../components/LogoutModal';
import{db}from'../../firebase/config';
import{agentWalletService}from'../../services/agentWalletService';
import{useAuthStore}from'../../store/authStore';
import{WalletCurrency}from'../../types/wallet';

export default function BusinessProfile(){
  const{user,setUser}=useAuthStore();
  const[identity,setIdentity]=useState('');
  const[showEdit,setShowEdit]=useState(false);
  const[showPin,setShowPin]=useState(false);
  const[showLogout,setShowLogout]=useState(false);
  const[busy,setBusy]=useState(false);
  const[name,setName]=useState(user?.displayName||'');
  const[phone,setPhone]=useState(user?.phone||'');
  const[currentPin,setCurrentPin]=useState('');
  const[nextPin,setNextPin]=useState('');
  const[confirmPin,setConfirmPin]=useState('');
  const[useBiometrics,setUseBiometrics]=useState(!!user?.useBiometrics);
  const[currency,setCurrency]=useState<WalletCurrency>(()=>localStorage.getItem('marketcash_wallet_currency')==='CDF'?'CDF':'USD');
  useEffect(()=>{agentWalletService.getMyMarketCashIdentity().then(x=>setIdentity(x.marketCashId)).catch(()=>setIdentity(''))},[user?.uid]);
  if(!user)return null;
  const saveProfile=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await updateDoc(doc(db,'users',user.uid),{displayName:name.trim(),phone:phone.trim(),updatedAt:Date.now()});setUser({...user,displayName:name.trim(),phone:phone.trim()});setShowEdit(false);toast.success('Profil Business mis à jour.')}catch{toast.error('Modification impossible.')}finally{setBusy(false)}};
  const changePin=async(e:React.FormEvent)=>{e.preventDefault();if(currentPin.length<4||nextPin.length<4)return toast.error('Le code doit contenir 4 à 6 chiffres.');if(nextPin!==confirmPin)return toast.error('Les nouveaux codes ne correspondent pas.');setBusy(true);try{const result=await agentWalletService.changeApplicationPin({currentPin,newPin:nextPin});setUser({...user,pinChangedAt:result.pinChangedAt,updatedAt:result.pinChangedAt});setShowPin(false);setCurrentPin('');setNextPin('');setConfirmPin('');toast.success("Code secret de l'application modifié.")}catch(error:any){toast.error(error?.message||'Modification refusée.')}finally{setBusy(false)}};
  const toggleBio=async()=>{const next=!useBiometrics;try{await updateDoc(doc(db,'users',user.uid),{useBiometrics:next,updatedAt:Date.now()});setUseBiometrics(next);setUser({...user,useBiometrics:next});toast.success(next?'Biométrie activée.':'Biométrie désactivée.')}catch{toast.error('Modification impossible.')}};
  const setPreferred=(value:WalletCurrency)=>{setCurrency(value);localStorage.setItem('marketcash_wallet_currency',value);toast.success(`Devise préférée : ${value}`)};
  return <div className="mx-auto max-w-2xl space-y-5 p-4 pb-28 md:p-8">
    <header><p className="text-sm font-semibold text-slate-500">Compte professionnel & paramètres</p><h1 className="mt-1 text-3xl font-black text-slate-950">Paramètres Business</h1></header>
    <section className="overflow-hidden rounded-[2rem] border bg-white shadow-sm"><div className="bg-gradient-to-br from-blue-950 to-blue-800 p-6 text-white"><Building2 size={30} className="text-amber-300"/><h2 className="mt-4 text-xl font-black">{user.displayName}</h2><p className="text-sm text-blue-200">{user.email}</p><div className="mt-4 rounded-2xl bg-white/10 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-blue-200">ID Marchand Market-Cash</p><p className="mt-1 font-mono text-lg font-black">{identity||'Chargement…'}</p></div></div><button onClick={()=>setShowEdit(true)} className="flex w-full items-center gap-3 p-4 text-left"><Edit3 size={18} className="text-blue-800"/><span className="text-sm font-black">Modifier mes informations</span></button></section>
    <section className="rounded-[2rem] border bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-50 text-blue-900"><ShieldCheck/></div><div><h2 className="text-lg font-black">Sécurité</h2><p className="mt-1 text-xs leading-5 text-slate-500">Le code secret protège soldes, historique, identifiants et réglages Business. Les paiements clients sont confirmés par le CVV du client.</p></div></div><div className="mt-5 divide-y overflow-hidden rounded-2xl border"><button onClick={()=>setShowPin(true)} className="flex w-full items-center justify-between p-4 text-left"><span className="flex items-center gap-3"><KeyRound size={20} className="text-blue-800"/><span><b className="block text-sm">Code secret de l'application</b><small className="text-slate-500">Accès aux informations sensibles</small></span></span><span className="text-xs font-black text-blue-700">Modifier</span></button><button onClick={toggleBio} className="flex w-full items-center justify-between p-4 text-left"><span className="flex items-center gap-3"><Fingerprint size={20} className="text-blue-800"/><span><b className="block text-sm">Biométrie</b><small className="text-slate-500">Protection rapide sur cet appareil</small></span></span><span className={`h-7 w-12 rounded-full p-1 ${useBiometrics?'bg-blue-950':'bg-slate-300'}`}><span className={`block h-5 w-5 rounded-full bg-white transition ${useBiometrics?'translate-x-5':''}`}/></span></button></div></section>
    <section className="rounded-[2rem] border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><WalletCards className="text-blue-800"/><div><h2 className="font-black">Préférences</h2><p className="text-xs text-slate-500">Devise d'affichage du compte Business</p></div></div><div className="mt-4 inline-flex rounded-xl bg-slate-100 p-1">{(['USD','CDF']as WalletCurrency[]).map(value=><button key={value} onClick={()=>setPreferred(value)} className={`rounded-lg px-4 py-2 text-xs font-black ${currency===value?'bg-blue-950 text-white':'text-slate-500'}`}>{value}</button>)}</div></section>
    <button onClick={()=>setShowLogout(true)} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-red-200 bg-white p-4 font-black text-red-700"><LogOut size={18}/>Se déconnecter</button>
    {showEdit&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={saveProfile} className="w-full max-w-md rounded-3xl bg-white p-5 shadow-xl"><h2 className="text-xl font-black">Modifier le profil Business</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom / raison commerciale" className="mt-4 w-full rounded-2xl border p-4"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Téléphone" className="mt-3 w-full rounded-2xl border p-4"/><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setShowEdit(false)} className="rounded-2xl border p-3 font-black">Annuler</button><button disabled={busy} className="rounded-2xl bg-blue-950 p-3 font-black text-white disabled:opacity-40">Enregistrer</button></div></form></div>}
    {showPin&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={changePin} className="w-full max-w-md rounded-3xl bg-white p-5 shadow-xl"><h2 className="text-xl font-black">Modifier le code secret</h2><p className="mt-1 text-xs text-slate-500">4 à 6 chiffres. Ce code sert à protéger l'application, jamais à confirmer une transaction client.</p><input type="password" inputMode="numeric" value={currentPin} onChange={e=>setCurrentPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="Code actuel" className="mt-4 w-full rounded-2xl border p-4"/><input type="password" inputMode="numeric" value={nextPin} onChange={e=>setNextPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="Nouveau code" className="mt-3 w-full rounded-2xl border p-4"/><input type="password" inputMode="numeric" value={confirmPin} onChange={e=>setConfirmPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="Confirmer le nouveau code" className="mt-3 w-full rounded-2xl border p-4"/><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setShowPin(false)} className="rounded-2xl border p-3 font-black">Annuler</button><button disabled={busy} className="rounded-2xl bg-blue-950 p-3 font-black text-white disabled:opacity-40">Modifier</button></div></form></div>}
    <LogoutModal isOpen={showLogout} onClose={()=>setShowLogout(false)}/>
  </div>;
}
