import React,{useEffect,useState}from'react';
import{RefreshCw}from'lucide-react';
import{developerBusinessService}from'../../services/developerBusinessService';
const money=(n:any,c:string)=>`${Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:c==='CDF'?0:2})} ${c}`;
const labels:Record<string,string>={developer_card_payment:'Paiement API reçu',developer_to_local_card:'Virement revenus vers carte locale',developer_personal_transfer:'Transfert Market-Cash envoyé',developer_wallet_to_local_card:'Recharge carte locale',developer_api_billing_topup:'Recharge crédit API',developer_merchant_payment:'Paiement marchand'};
const label=(t:any)=>labels[String(t.type||'')]||t.reason||t.type||'Transaction Market-Cash';
const outgoing=new Set(['developer_to_local_card','developer_personal_transfer','developer_wallet_to_local_card','developer_api_billing_topup','developer_merchant_payment']);
const friendly=(e:any)=>{const text=String(e?.message||'');return !text||text.toLowerCase().includes('internal [0]')?'Historique momentanément en synchronisation.':text};
export default function BusinessDeveloperTransactions(){const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=async(force=false)=>{setLoading(true);setError('');try{const d=await developerBusinessService.dashboard(force);setItems((d.transactions||[]).sort((a:any,b:any)=>Number(b.createdAt||0)-Number(a.createdAt||0)))}catch(e:any){setError(friendly(e))}finally{setLoading(false)}};useEffect(()=>{void load()},[]);return <div className="mx-auto max-w-3xl p-4 pb-28 md:p-8"><header className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-blue-700">Developer</p><h1 className="text-3xl font-black">Transactions</h1><p className="mt-2 text-sm text-slate-500">Paiements reçus, transferts, carte locale et crédit API.</p></div><button onClick={()=>void load(true)} className="rounded-xl border bg-white p-3" aria-label="Actualiser"><RefreshCw size={18} className={loading?'animate-spin':''}/></button></header>{error&&<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Synchronisation</b><p className="mt-1">{error}</p><button onClick={()=>void load(true)} className="mt-3 rounded-xl bg-blue-950 px-4 py-2 text-xs font-black text-white">Réessayer</button></div>}<div className="mt-5 space-y-3">{loading&&items.length===0?<><div className="h-28 animate-pulse rounded-3xl bg-slate-200"/><div className="h-28 animate-pulse rounded-3xl bg-slate-100"/></>:items.map(t=>{const debit=outgoing.has(String(t.type||''));return <article key={t.id||t.reference} className="rounded-[2rem] border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black">{label(t)}</h2><p className="mt-1 font-mono text-[10px] text-slate-400">{t.reference||t.id}</p></div><b className={debit?'text-amber-700':'text-emerald-700'}>{debit?'-':'+'}{money(t.amount,t.currency||'USD')}</b></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs text-slate-500"><p>Statut : <b className="text-slate-800">{t.status||'settled'}</b></p><p>Application : <b className="text-slate-800">{t.appName||'—'}</b></p><p>Référence externe : <b className="text-slate-800">{t.externalReference||'—'}</b></p><p>Date : <b className="text-slate-800">{t.createdAt?new Date(t.createdAt).toLocaleString('fr-FR'):'—'}</b></p></div></article>})}{!loading&&!error&&!items.length&&<div className="rounded-3xl border bg-white p-8 text-center text-sm text-slate-400">Aucune transaction pour le moment.</div>}</div></div>}
