import React,{useEffect,useState}from'react';
import{ArrowDownToLine,CreditCard,RefreshCw,Store}from'lucide-react';
import toast from'react-hot-toast';
import{agentWalletService,InternalCardSummary}from'../../services/agentWalletService';

const money=(n:any,c:string)=>`${Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:c==='CDF'?0:2})} ${c}`;
type Action='topup'|'pay'|null;
const idem=()=>`DEV-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;

export default function BusinessDeveloperCards(){
 const[card,setCard]=useState<InternalCardSummary|null>(null);const[loading,setLoading]=useState(true);const[action,setAction]=useState<Action>(null);const[currency,setCurrency]=useState<'USD'|'CDF'>('USD');const[amount,setAmount]=useState('');const[target,setTarget]=useState('');const[cvv,setCvv]=useState('');const[busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);try{let cards=await agentWalletService.getMyInternalCards().catch(()=>[]);if(!cards.length){await agentWalletService.ensureLocalCard().catch(()=>null);cards=await agentWalletService.getMyInternalCards().catch(()=>[])}setCard(cards[0]||null)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const reset=()=>{setAction(null);setAmount('');setTarget('');setCvv('')};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const value=Number(amount);if(!card?.cardId)return toast.error('Carte locale indisponible.');if(!Number.isFinite(value)||value<=0)return toast.error('Montant invalide.');if(!/^\d{3}$/.test(cvv))return toast.error('CVV à 3 chiffres requis.');setBusy(true);try{if(action==='topup'){await agentWalletService.fundInternalCard({cardId:card.cardId,currency,amount:value,cvv,idempotencyKey:idem()});toast.success('Carte locale rechargée.')}else{if(!target.trim())throw new Error('ID marchand requis.');await agentWalletService.payMerchant({cardId:card.cardId,marketCashId:target.trim(),currency,amount:value,cvv,idempotencyKey:idem()});toast.success('Paiement marchand effectué.')}reset();await load()}catch(e:any){toast.error(e?.message&&e.message!=='internal [0]'?e.message:'Opération momentanément indisponible.')}finally{setBusy(false)}};
 return <div className="mx-auto max-w-3xl p-4 pb-28 md:p-8"><header className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-blue-700">Market-Cash Developer</p><h1 className="text-3xl font-black">Cartes</h1><p className="mt-2 text-sm text-slate-500">Votre carte locale reste l’instrument de paiement et l’unique moyen de retrait.</p></div><button onClick={()=>void load()} className="rounded-xl border bg-white p-3" aria-label="Actualiser"><RefreshCw size={18} className={loading?'animate-spin':''}/></button></header>
 <section className="mt-5 rounded-[2rem] border bg-gradient-to-br from-blue-700 to-blue-950 p-6 text-white shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-black tracking-widest text-blue-100">MARKET-CASH</p><h2 className="mt-1 text-xl font-black">LOCAL · USD / CDF</h2></div><CreditCard/></div><p className="mt-10 font-mono text-xl tracking-[.18em]">{loading?'•••• •••• •••• ••••':card?.maskedNumber||'Carte en synchronisation'}</p><div className="mt-6 grid grid-cols-2 gap-3"><div><p className="text-[10px] font-black text-blue-200">SOLDE USD</p><p className="mt-1 text-xl font-black">{money(card?.balances?.USD||0,'USD')}</p></div><div><p className="text-[10px] font-black text-blue-200">SOLDE CDF</p><p className="mt-1 text-xl font-black">{money(card?.balances?.CDF||0,'CDF')}</p></div></div></section>
 <div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>setAction('topup')} className="flex flex-col items-center gap-2 rounded-2xl border bg-white p-4 text-xs font-black"><ArrowDownToLine size={20}/>Recharger</button><button onClick={()=>setAction('pay')} className="flex flex-col items-center gap-2 rounded-2xl border bg-white p-4 text-xs font-black"><Store size={20}/>Payer</button><button onClick={()=>toast('Pour retirer, présentez cette carte à un Agent Market-Cash. Le retrait est confirmé avec le CVV de la carte.')} className="flex flex-col items-center gap-2 rounded-2xl border bg-white p-4 text-xs font-black"><CreditCard size={20}/>Retrait</button></div>
 <section className="mt-5 rounded-[2rem] border bg-white p-5"><h2 className="font-black">Règle de retrait</h2><p className="mt-2 text-sm text-slate-500">Aucun retrait ne part directement du wallet ou du compte revenus Developer. Les fonds sont d’abord transférés vers la carte locale Market-Cash.</p></section>
 {action&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-5"><h2 className="text-xl font-black">{action==='topup'?'Recharger la carte':'Payer un marchand'}</h2><div className="mt-4 flex rounded-xl bg-slate-100 p-1">{(['USD','CDF']as const).map(c=><button type="button" key={c} onClick={()=>setCurrency(c)} className={`flex-1 rounded-lg p-2 font-black ${currency===c?'bg-blue-950 text-white':''}`}>{c}</button>)}</div>{action==='pay'&&<input value={target} onChange={e=>setTarget(e.target.value)} placeholder="ID marchand Market-Cash" className="mt-3 w-full rounded-2xl border p-4"/>}<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Montant" className="mt-3 w-full rounded-2xl border p-4"/><input value={cvv} onChange={e=>setCvv(e.target.value.replace(/\D/g,'').slice(0,3))} inputMode="numeric" placeholder="CVV · 3 chiffres" className="mt-3 w-full rounded-2xl border p-4"/><p className="mt-2 text-xs text-slate-500">Le CVV est toujours saisi manuellement.</p><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={reset} className="rounded-2xl border p-3 font-black">Annuler</button><button disabled={busy} className="rounded-2xl bg-blue-950 p-3 font-black text-white">Confirmer</button></div></form></div>}
 </div>;
}
