import React,{useEffect,useState}from'react';
import{ArrowDownToLine,Copy,CreditCard,Landmark,ReceiptText,WalletCards}from'lucide-react';
import toast from'react-hot-toast';
import{developerBusinessService,DeveloperDashboard}from'../../services/developerBusinessService';
import{agentWalletService,InternalCardSummary,WalletServerSnapshot}from'../../services/agentWalletService';
import{professionalBusinessService}from'../../services/professionalBusinessService';
const money=(n:any,c:string)=>`${Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:c==='CDF'?0:2})} ${c}`;
export default function BusinessDeveloperHome(){
 const[data,setData]=useState<DeveloperDashboard|null>(null);const[wallet,setWallet]=useState<WalletServerSnapshot|null>(null);const[card,setCard]=useState<InternalCardSummary|null>(null);const[billing,setBilling]=useState<any>(null);const[loading,setLoading]=useState(true);const[transferOpen,setTransferOpen]=useState(false);const[billingOpen,setBillingOpen]=useState(false);const[currency,setCurrency]=useState<'USD'|'CDF'>('USD');const[amount,setAmount]=useState('');const[billingAmount,setBillingAmount]=useState('');const[busy,setBusy]=useState(false);
 const load=async(force=false)=>{try{const[d,w,cards,b]=await Promise.all([developerBusinessService.dashboard(force),agentWalletService.getMyWallets(),agentWalletService.getMyInternalCards(),developerBusinessService.billing()]);setData(d);setWallet(w);setCard(cards[0]||null);setBilling(b)}catch(e:any){toast.error(e?.message||'Accueil Developer indisponible.')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const transfer=async(e:React.FormEvent)=>{e.preventDefault();const value=Number(amount);if(!Number.isFinite(value)||value<=0)return toast.error('Montant invalide.');setBusy(true);try{await professionalBusinessService.developerToLocalCard({currency,amount:value});developerBusinessService.invalidate();toast.success('Revenus transférés vers la carte locale.');setAmount('');setTransferOpen(false);await load(true)}catch(e:any){toast.error(e?.message||'Transfert impossible.')}finally{setBusy(false)}};
 const fundBilling=async(e:React.FormEvent)=>{e.preventDefault();const value=Number(billingAmount);if(!Number.isFinite(value)||value<=0)return toast.error('Montant invalide.');setBusy(true);try{const r=await developerBusinessService.fundBilling(value);toast.success(`Compte API crédité : ${money(r.balance,'USD')}`);setBillingAmount('');setBillingOpen(false);await load(true)}catch(e:any){toast.error(e?.message||'Crédit de facturation impossible.')}finally{setBusy(false)}};
 const copyId=async()=>{const id=wallet?.marketCashId||wallet?.rechargeNumber||'';if(!id)return;await navigator.clipboard?.writeText(id);toast.success('Identifiant Market-Cash copié.')} ;
 const dev=data?.developer,provider=dev?.businessType==='api_provider';
 return <div className="mx-auto max-w-4xl space-y-5 p-4 pb-28 md:p-8">
  <header><p className="text-xs font-black uppercase tracking-widest text-blue-700">{provider?'Partner Home':'Developer Home'}</p><h1 className="text-3xl font-black">{dev?.companyName||'Market-Cash Developer'}</h1><p className="mt-2 text-sm text-slate-500">Revenus, facturation API, wallet personnel et carte locale sont volontairement séparés.</p></header>
  <section className="rounded-[2rem] border bg-white p-5"><div className="flex items-center gap-2"><Landmark className="text-blue-800"/><div><h2 className="font-black">Compte revenus Developer</h2><p className="text-xs text-slate-500">Paiements reçus de vos applications. Aucun frais API n’est retiré ici.</p></div></div><div className="mt-4 grid grid-cols-2 gap-3">{['USD','CDF'].map(c=><div key={c} className="rounded-2xl bg-slate-50 p-4"><p className="text-[11px] font-black text-slate-400">DISPONIBLE {c}</p><p className="mt-1 text-2xl font-black">{loading?'—':money(data?.wallets?.[c]?.availableBalance,c)}</p></div>)}</div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setTransferOpen(true)} className="rounded-2xl bg-blue-950 p-3 text-sm font-black text-white">Vers carte locale</button><button onClick={()=>setBillingOpen(true)} className="rounded-2xl border p-3 text-sm font-black">Créditer API</button></div></section>
  <section className="rounded-[2rem] border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-slate-400">COMPTE FACTURATION API</p><p className="mt-1 text-2xl font-black">{billing?money(billing.balance,'USD'):'—'}</p></div><ReceiptText className="text-blue-800"/></div><p className="mt-3 text-sm text-slate-500">Débité uniquement pour l’usage API. Tarif actuel : <b>{billing?.unitPrice?.toFixed?.(2)|| (provider?'0.05':'0.10')} USD</b> par requête de paiement réussie.</p><p className="mt-1 text-xs font-black text-blue-800">≈ {billing?.estimatedRequests||0} requêtes disponibles</p></section>
  <section className="rounded-[2rem] border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-slate-400">WALLET MARKET-CASH PERSONNEL</p><h2 className="mt-1 font-black">{wallet?.marketCashId||'Compte Market-Cash'}</h2></div><WalletCards className="text-blue-800"/></div><div className="mt-4 grid grid-cols-2 gap-3">{(['USD','CDF']as const).map(c=><div key={c} className="rounded-2xl bg-slate-50 p-4"><p className="text-[11px] font-black text-slate-400">SOLDE {c}</p><p className="mt-1 text-xl font-black">{money(wallet?.wallets?.[c]?.availableBalance,c)}</p></div>)}</div><button onClick={copyId} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl border p-3 text-sm font-black"><Copy size={16}/>Copier mon ID Market-Cash</button></section>
  <section className="rounded-[2rem] border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-slate-400">CARTE LOCALE MARKET-CASH</p><h2 className="mt-1 text-lg font-black">{card?.maskedNumber||'Carte locale active'}</h2><p className="mt-1 text-xs text-slate-500">Toutes vos opérations de retrait passent par cette carte.</p></div><CreditCard className="text-blue-800"/></div><div className="mt-4 grid grid-cols-2 gap-3">{(['USD','CDF']as const).map(c=><div key={c} className="rounded-2xl bg-blue-50 p-4"><p className="text-[11px] font-black text-blue-700">SOLDE CARTE {c}</p><p className="mt-1 text-xl font-black text-blue-950">{money(card?.balances?.[c]||0,c)}</p></div>)}</div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setTransferOpen(true)} className="flex items-center justify-center gap-2 rounded-2xl bg-blue-950 p-3 text-sm font-black text-white"><ArrowDownToLine size={16}/>Alimenter</button><button onClick={()=>toast('Présentez votre carte locale à un Agent Market-Cash pour effectuer le retrait.')} className="rounded-2xl border p-3 text-sm font-black">Retrait</button></div></section>
  {transferOpen&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={transfer} className="w-full max-w-md rounded-3xl bg-white p-5"><h2 className="text-xl font-black">Revenus → carte locale</h2><div className="mt-4 flex rounded-xl bg-slate-100 p-1">{(['USD','CDF']as const).map(c=><button type="button" key={c} onClick={()=>setCurrency(c)} className={`flex-1 rounded-lg p-2 font-black ${currency===c?'bg-blue-950 text-white':''}`}>{c}</button>)}</div><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Montant" className="mt-3 w-full rounded-2xl border p-4"/><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setTransferOpen(false)} className="rounded-2xl border p-3 font-black">Annuler</button><button disabled={busy} className="rounded-2xl bg-blue-950 p-3 font-black text-white">Confirmer</button></div></form></div>}
  {billingOpen&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={fundBilling} className="w-full max-w-md rounded-3xl bg-white p-5"><h2 className="text-xl font-black">Créditer la facturation API</h2><p className="mt-2 text-sm text-slate-500">Le montant est prélevé uniquement sur votre compte revenus USD. Il ne touche pas l’argent payé par vos clients.</p><input value={billingAmount} onChange={e=>setBillingAmount(e.target.value)} inputMode="decimal" placeholder="Montant USD" className="mt-4 w-full rounded-2xl border p-4"/><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setBillingOpen(false)} className="rounded-2xl border p-3 font-black">Annuler</button><button disabled={busy} className="rounded-2xl bg-blue-950 p-3 font-black text-white">Créditer</button></div></form></div>}
 </div>;
}
