import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,ChevronRight,CreditCard,Plus,RefreshCw,ShieldCheck,Sparkles,WalletCards}from'lucide-react';
import{Link,useNavigate,useSearchParams}from'react-router-dom';
import toast from'react-hot-toast';
import CardProductFace,{CardProductVariant}from'../../components/CardProductFace';
import SecurityConfirmModal from'../../components/SecurityConfirmModal';
import{agentWalletService,InternalCardSummary,LocalCardSecureData}from'../../services/agentWalletService';
import{cardSecurityService,VisaCardSummary,VisaSecureData}from'../../services/cardSecurityService';
import{cardCache,cardCacheKeys}from'../../services/cardCache';
import{useAuthStore}from'../../store/authStore';
import CardDetail from'./CardDetail';
import ClientCards from'./Cards';
import LocalCardTopup from'./LocalCardTopup';

type RevealTarget={kind:CardProductVariant;id:string}|null;
const friendlyLocalError=(error:any)=>{const code=String(error?.code||'').toLowerCase();const message=String(error?.message||'');if(code.includes('internal')||message.toLowerCase().includes('internal [0]'))return'Le service de carte locale est momentanément en cours de synchronisation.';if(code.includes('failed-precondition')&&message.toLowerCase().includes('kyc'))return'La validation KYC n’est pas encore synchronisée avec le service de carte.';return message||'Impossible de synchroniser la carte locale pour le moment.';};

export default function CardsHub(){
  const{user}=useAuthStore();const navigate=useNavigate();const[searchParams]=useSearchParams();const uid=user?.uid||'';
  const visaMode=searchParams.get('visa')==='buy';const selectedKind=searchParams.get('card')as CardProductVariant|null;const selectedCardId=searchParams.get('cardId');const selectedAction=searchParams.get('action');const topupChooser=selectedAction==='topup'&&!selectedKind;const requestedCurrency=searchParams.get('currency')==='CDF'?'CDF':'USD';
  const initialLocal=uid?cardCache.get<InternalCardSummary[]>(cardCacheKeys.local(uid)):null;const initialVisa=uid?cardCache.get<VisaCardSummary[]>(cardCacheKeys.visa(uid)):null;
  const[localCard,setLocalCard]=useState<InternalCardSummary|null>(initialLocal?.[0]||null);const[localSecure,setLocalSecure]=useState<LocalCardSecureData|null>(null);const[visaCards,setVisaCards]=useState<VisaCardSummary[]>(initialVisa||[]);const[visaSecure,setVisaSecure]=useState<Record<string,VisaSecureData>>({});const[loadingLocal,setLoadingLocal]=useState(!initialLocal);const[loadingVisa,setLoadingVisa]=useState(!initialVisa);const[localError,setLocalError]=useState('');const[localRetry,setLocalRetry]=useState(0);const[revealed,setRevealed]=useState<Record<string,boolean>>({});const[pendingReveal,setPendingReveal]=useState<RevealTarget>(null);const[securityBusy,setSecurityBusy]=useState(false);

  useEffect(()=>{if(!uid||visaMode||selectedKind)return;let active=true;if(!localCard)setLoadingLocal(true);setLocalError('');agentWalletService.getMyInternalCards().then(cards=>{if(!active)return;setLocalCard(cards[0]||null);cardCache.set(cardCacheKeys.local(uid),cards);if(!cards[0])setLocalError('Votre carte n’a pas encore pu être créée.')}).catch(error=>{console.warn('[LOCAL_CARD_LOAD_ERROR]',error);if(active&&!localCard)setLocalError(friendlyLocalError(error))}).finally(()=>active&&setLoadingLocal(false));return()=>{active=false}},[uid,visaMode,selectedKind,localRetry]);
  useEffect(()=>{if(!uid||visaMode||selectedKind)return;let active=true;if(!visaCards.length)setLoadingVisa(true);cardSecurityService.getMyVisaCards().then(cards=>{if(active){setVisaCards(cards);cardCache.set(cardCacheKeys.visa(uid),cards)}}).catch(error=>console.warn('[VISA_SUMMARIES_ERROR]',error)).finally(()=>active&&setLoadingVisa(false));return()=>{active=false}},[uid,visaMode,selectedKind]);

  const standardCards=useMemo(()=>visaCards.filter(card=>card.tier==='standard').slice(0,4),[visaCards]);const goldCard=useMemo(()=>visaCards.find(card=>card.tier==='gold')||null,[visaCards]);
  const askReveal=(kind:CardProductVariant,id:string)=>{if(revealed[id]){setRevealed(current=>({...current,[id]:false}));if(kind==='local')setLocalSecure(null);else setVisaSecure(current=>{const next={...current};delete next[id];return next});return}setPendingReveal({kind,id})};
  const confirmReveal=async(pin:string)=>{if(!pendingReveal)return;setSecurityBusy(true);try{if(pendingReveal.kind==='local'){setLocalSecure(await agentWalletService.revealLocalCardSecureData(pin));}else{const secure=await cardSecurityService.revealVisaCard(pendingReveal.id,pin);setVisaSecure(current=>({...current,[pendingReveal.id]:secure}));}setRevealed(current=>({...current,[pendingReveal.id]:true}));setPendingReveal(null)}catch(error:any){toast.error(error?.message||'Code secret incorrect.')}finally{setSecurityBusy(false)}};
  const openCard=(kind:CardProductVariant,id?:string)=>navigate(`/client/cards?card=${kind}${id?`&cardId=${encodeURIComponent(id)}`:''}`);

  if(visaMode)return <div className="pb-28"><div className="mx-auto max-w-4xl px-3.5 pt-4 sm:px-6"><Link to="/client/cards" className="inline-flex items-center gap-2 text-sm font-black text-slate-500"><ArrowLeft size={17}/>Mes cartes</Link></div><ClientCards/></div>;
  if(selectedKind==='local'&&selectedAction==='topup')return <LocalCardTopup/>;
  if(selectedKind&&['local','standard','gold'].includes(selectedKind))return <CardDetail kind={selectedKind} cardId={selectedCardId}/>;
  if(topupChooser)return <div className="mx-auto max-w-xl p-4 pb-28 md:p-8"><Link to="/client/home" className="inline-flex items-center gap-2 text-sm font-black text-slate-500"><ArrowLeft size={17}/>Accueil</Link><section className="mt-5 rounded-[2rem] border bg-white p-5 shadow-sm"><h1 className="text-2xl font-black">Quelle carte voulez-vous alimenter ?</h1><p className="mt-2 text-sm text-slate-500">Le Wallet est la source d’alimentation.</p><div className="mt-6 space-y-3">{localCard&&<Link to={`/client/cards?card=local&action=topup&currency=${requestedCurrency}`} className="flex items-center justify-between rounded-2xl border-2 border-blue-200 bg-blue-50 p-4"><div><p className="font-black text-blue-950">Market-Cash Locale</p><p className="mt-1 font-mono text-xs text-blue-700">{localCard.maskedNumber}</p></div><ChevronRight/></Link>}{standardCards.map(card=><div key={card.cardId} className="rounded-2xl border p-4"><p className="font-black">Visa Standard</p><p className="text-xs text-slate-500">{card.maskedNumber}</p></div>)}{goldCard&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="font-black">Visa Gold</p><p className="text-xs">{goldCard.maskedNumber}</p></div>}</div></section></div>;

  const localKey=localCard?.cardId||'local';const kycApproved=user?.kycStatus==='approved';
  return <div className="mx-auto max-w-4xl px-3.5 pb-28 pt-4 sm:px-6"><h1 className="mb-6 text-2xl font-black">Cartes</h1>
    <section className="mb-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black uppercase tracking-[.12em] text-blue-950">Market-Cash Locale</h2>{loadingLocal&&<RefreshCw size={15} className="animate-spin text-slate-400"/>}</div>{localCard?<><div role="button" tabIndex={0} onClick={()=>openCard('local',localCard.cardId)} className="cursor-pointer rounded-[1.65rem]"><CardProductFace variant="local" holder={localSecure?.cardHolder||localCard.cardHolder||user?.displayName} number={localSecure?.cardNumber||localCard.maskedNumber} expiryStart={localSecure?.expiryStart||localCard.expiryStart} expiryEnd={localSecure?.expiryEnd||localCard.expiryEnd} cvv={localSecure?.cvv} qrData={localCard.qrData} revealed={!!revealed[localKey]} onToggleReveal={()=>askReveal('local',localKey)}/></div><div className="mt-3 grid grid-cols-2 gap-2"><Link to={`/client/cards?card=local&cardId=${encodeURIComponent(localCard.cardId)}`} className="flex items-center justify-center gap-2 rounded-2xl border bg-white px-4 py-3 text-sm font-black text-blue-950"><ShieldCheck size={16}/>Détails</Link><Link to={`/client/cards?card=local&action=topup&currency=${requestedCurrency}`} className="flex items-center justify-center gap-2 rounded-2xl bg-blue-950 px-4 py-3 text-sm font-black text-white"><Plus size={16}/>Recharger</Link></div></>:!loadingLocal?<div className={`rounded-3xl border border-dashed p-5 ${kycApproved?'bg-blue-50':'bg-amber-50'}`}><p className="font-black">{kycApproved?'Activation de la carte locale':'Carte locale non encore active'}</p><p className="mt-1 text-sm">{localError}</p><button onClick={()=>setLocalRetry(v=>v+1)} className="mt-3 rounded-xl bg-blue-950 px-4 py-2 text-xs font-black text-white">Réessayer</button></div>:null}</section>
    <section className="mb-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black uppercase tracking-[.12em] text-slate-700">Market-Cash Visa Standard</h2>{loadingVisa&&<RefreshCw size={15} className="animate-spin text-slate-400"/>}</div>{standardCards.length?<div className="flex gap-3 overflow-x-auto">{standardCards.map(card=><div key={card.cardId} onClick={()=>openCard('standard',card.cardId)} className="w-[88%] shrink-0 cursor-pointer"><CardProductFace variant="standard" holder={card.cardHolder||user?.displayName} number={card.maskedNumber}/></div>)}</div>:!loadingVisa?<ProductEmptyState icon={<CreditCard size={24}/>} title="Aucune Visa Standard active" text="Vous pouvez en posséder jusqu'à quatre." action="Obtenir une Visa Standard" to="/client/cards?visa=buy"/>:null}</section>
    <section><h2 className="mb-3 text-sm font-black uppercase tracking-[.12em] text-amber-800">Market-Cash Visa Gold</h2>{goldCard?<div onClick={()=>openCard('gold',goldCard.cardId)} className="cursor-pointer"><CardProductFace variant="gold" holder={goldCard.cardHolder||user?.displayName} number={goldCard.maskedNumber}/></div>:!loadingVisa?<ProductEmptyState icon={<Sparkles size={24}/>} title="Visa Gold non émise" text="Émission via partenaire connecté." action="Voir les cartes Visa" to="/client/cards?visa=buy" gold/>:null}</section>
    <SecurityConfirmModal open={!!pendingReveal} busy={securityBusy} onClose={()=>!securityBusy&&setPendingReveal(null)} onConfirm={confirmReveal} title="Afficher les informations de la carte" subtitle="Entrez le code secret de l’application."/>
  </div>;
}
function ProductEmptyState({icon,title,text,action,to,gold=false}:{icon:React.ReactNode;title:string;text:string;action:string;to:string;gold?:boolean}){return <div className={`rounded-[1.75rem] border p-5 ${gold?'border-amber-200 bg-amber-50/70':'bg-white'} shadow-sm`}><div className="grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-blue-950">{icon}</div><h3 className="mt-4 text-lg font-black">{title}</h3><p className="mt-2 text-sm text-slate-500">{text}</p><Link to={to} className={`mt-4 flex items-center justify-between rounded-2xl px-4 py-3 text-sm font-black ${gold?'bg-amber-400 text-blue-950':'bg-blue-950 text-white'}`}><span>{action}</span><ChevronRight size={17}/></Link></div>}
