import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Banknote,Ban,Eye,EyeOff,RefreshCw,RotateCcw,ShieldCheck,Store,Trash2,Unlock,WalletCards}from'lucide-react';
import{Link,useNavigate}from'react-router-dom';
import toast from'react-hot-toast';
import CardProductFace,{CardProductVariant}from'../../components/CardProductFace';
import SecurityConfirmModal from'../../components/SecurityConfirmModal';
import{agentWalletService,InternalCardSummary,LocalCardSecureData}from'../../services/agentWalletService';
import{cardSecurityService,VisaCardSummary,VisaSecureData}from'../../services/cardSecurityService';
import{cardCache,cardCacheKeys}from'../../services/cardCache';
import{localCardManagementService}from'../../services/localCardManagementService';
import{useAuthStore}from'../../store/authStore';
import{WalletCurrency}from'../../types/wallet';

interface CardDetailProps{kind:CardProductVariant;cardId?:string|null}
const money=(value:number,currency:WalletCurrency)=>currency==='CDF'?`${Number(value||0).toLocaleString('fr-FR',{maximumFractionDigits:0})} CDF`:`${Number(value||0).toFixed(2)} USD`;
const transactionLabel=(type:string)=>{const n=String(type||'').toLowerCase();if(n.includes('wallet_to_local_card')||n.includes('cardtopup'))return'Recharge';if(n.includes('merchant'))return'Paiement marchand';if(n.includes('cash_out')||n.includes('cashout')||n.includes('withdraw'))return'Retrait';if(n.includes('refund'))return'Remboursement';return'Opération carte'};
const isDebit=(type:string)=>{const n=String(type||'').toLowerCase();return n.includes('merchant')||n.includes('cash_out')||n.includes('cashout')||n.includes('withdraw')};
const belongsToCard=(transaction:any,cardId?:string|null)=>{if(!cardId)return false;const direct=[transaction?.cardId,transaction?.sourceCardId,transaction?.destinationCardId].filter(Boolean).map(String);if(direct.includes(cardId))return true;return[transaction?.cardWalletId,transaction?.sourceCardWalletId,transaction?.destinationCardWalletId].filter(Boolean).map(String).some(v=>v.includes(cardId))};
type SecurityAction='balance'|'details'|null;

export default function CardDetail({kind,cardId}:CardDetailProps){
  const{user}=useAuthStore();const navigate=useNavigate();const uid=user?.uid||'';
  const cachedLocal=uid?cardCache.get<InternalCardSummary[]>(cardCacheKeys.local(uid)):null;const cachedHistory=uid?cardCache.get<any[]>(cardCacheKeys.history(uid)):null;
  const[currency,setCurrency]=useState<WalletCurrency>('USD');const[showBalance,setShowBalance]=useState(false);const[detailsRevealed,setDetailsRevealed]=useState(false);const[standardSide,setStandardSide]=useState<'front'|'back'>('front');const[localCard,setLocalCard]=useState<InternalCardSummary|null>(kind==='local'?(cachedLocal?.find(c=>!cardId||c.cardId===cardId)||cachedLocal?.[0]||null):null);const[localSecure,setLocalSecure]=useState<LocalCardSecureData|null>(null);const[visaCard,setVisaCard]=useState<VisaCardSummary|null>(null);const[visaSecure,setVisaSecure]=useState<VisaSecureData|null>(null);const[transactions,setTransactions]=useState<any[]>(cachedHistory||[]);const[loading,setLoading]=useState(kind==='local'&&!cachedLocal);const[securityAction,setSecurityAction]=useState<SecurityAction>(null);const[securityBusy,setSecurityBusy]=useState(false);const[actionBusy,setActionBusy]=useState(false);

  const refreshLocal=async()=>{const cards=await agentWalletService.getMyInternalCards();setLocalCard(cards.find(c=>!cardId||c.cardId===cardId)||cards[0]||null);if(uid)cardCache.set(cardCacheKeys.local(uid),cards)};
  useEffect(()=>{let active=true;(async()=>{if(!uid)return;if(!localCard)setLoading(true);try{const historyPromise=agentWalletService.getMyWalletHistory().catch(()=>[]as any[]);if(kind==='local'){const cards=await agentWalletService.getMyInternalCards();if(active){setLocalCard(cards.find(c=>!cardId||c.cardId===cardId)||cards[0]||null);cardCache.set(cardCacheKeys.local(uid),cards)}}else if(cardId){const cards=await cardSecurityService.getMyVisaCards();if(active)setVisaCard(cards.find(c=>c.cardId===cardId&&c.tier===(kind==='gold'?'gold':'standard'))||null)}const history=await historyPromise;if(active){setTransactions(history);cardCache.set(cardCacheKeys.history(uid),history)}}catch(error){console.warn('[CARD_DETAIL_LOAD_ERROR]',error)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[uid,kind,cardId]);

  const activeCardId=kind==='local'?localCard?.cardId:visaCard?.cardId||cardId||null;const cardHistory=useMemo(()=>transactions.filter(tx=>belongsToCard(tx,activeCardId)).slice(0,30),[transactions,activeCardId]);const localBalance=Number(localCard?.balances?.[currency]||0);const visaBalance=visaSecure?.balances?.[currency];const holder=kind==='local'?localSecure?.cardHolder||localCard?.cardHolder||user?.displayName:visaSecure?.cardHolder||visaCard?.cardHolder||user?.displayName;const number=kind==='local'?localSecure?.cardNumber||localCard?.maskedNumber:visaSecure?.cardNumber||visaCard?.maskedNumber;const expiryStart=kind==='local'?localSecure?.expiryStart||localCard?.expiryStart:visaSecure?.expiryStart;const expiryEnd=kind==='local'?localSecure?.expiryEnd||localCard?.expiryEnd:visaSecure?.expiryEnd;const cvv=kind==='local'?localSecure?.cvv:visaSecure?.cvv;const qrData=kind==='local'?localCard?.qrData:undefined;const cardExists=kind==='local'?!!localCard:!!visaCard;const blocked=kind==='local'&&localCard?.status==='blocked';
  const requestBalance=()=>{if(showBalance){setShowBalance(false);return}setSecurityAction('balance')};const requestDetails=()=>{if(detailsRevealed){setDetailsRevealed(false);setLocalSecure(null);setVisaSecure(null);return}setSecurityAction('details')};const confirmSecurity=async(pin:string)=>{if(!securityAction)return;setSecurityBusy(true);try{if(kind==='local')setLocalSecure(await agentWalletService.revealLocalCardSecureData(pin));else if(cardId)setVisaSecure(await cardSecurityService.revealVisaCard(cardId,pin));if(securityAction==='details')setDetailsRevealed(true);if(securityAction==='balance')setShowBalance(true);setSecurityAction(null)}catch(error:any){toast.error(error?.message||'Code secret incorrect.')}finally{setSecurityBusy(false)}};
  const toggleBlock=async()=>{setActionBusy(true);try{await localCardManagementService.setBlocked(!blocked);await refreshLocal();toast.success(blocked?'Carte débloquée.':'Carte bloquée.')}catch(e:any){toast.error(e?.message||'Action impossible.')}finally{setActionBusy(false)}};
  const resetCard=async()=>{if(!window.confirm('Réinitialiser la sécurité de cette carte ? Le CVV sera changé.'))return;setActionBusy(true);try{await localCardManagementService.resetSecurity();setLocalSecure(null);setDetailsRevealed(false);toast.success('Sécurité réinitialisée. Affichez la carte avec votre code secret pour voir le nouveau CVV.')}catch(e:any){toast.error(e?.message||'Réinitialisation impossible.')}finally{setActionBusy(false)}};
  const removeCard=async()=>{if(!window.confirm('Supprimer cette carte locale ? Cette action exige un solde nul.'))return;setActionBusy(true);try{await localCardManagementService.archive();if(uid)cardCache.clear(cardCacheKeys.local(uid));toast.success('Carte supprimée.');navigate('/client/cards',{replace:true})}catch(e:any){toast.error(e?.message||'Suppression impossible.')}finally{setActionBusy(false)}};

  return <div className="mx-auto max-w-4xl px-3.5 pb-28 pt-4 sm:px-6"><Link to="/client/cards" className="inline-flex items-center gap-2 text-sm font-black text-slate-500"><ArrowLeft size={17}/>Mes cartes</Link><div className="mx-auto mt-5 max-w-xl">{loading&&!cardExists?<div className="grid aspect-[1.586/1] place-items-center rounded-[1.65rem] bg-slate-100 text-slate-400"><RefreshCw className="animate-spin" size={24}/></div>:cardExists?<><CardProductFace variant={kind} holder={holder} number={number} expiryStart={expiryStart} expiryEnd={expiryEnd} cvv={cvv} qrData={qrData} revealed={detailsRevealed} side={standardSide} onToggleReveal={requestDetails} onFlip={kind==='standard'?()=>setStandardSide(s=>s==='front'?'back':'front'):undefined}/>{blocked&&<div className="mt-3 rounded-2xl bg-red-50 px-4 py-3 text-sm font-black text-red-700">Carte bloquée — paiements, retraits et recharge désactivés.</div>}</>:<div className="rounded-3xl border border-dashed bg-white p-8 text-center"><p className="font-black">Carte indisponible</p></div>}</div>
    {cardExists&&<><section className="mx-auto mt-5 max-w-xl rounded-[1.75rem] border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Solde de la carte</p><p className="mt-2 text-2xl font-black text-blue-950">{!showBalance?'••••••':kind==='local'?money(localBalance,currency):visaBalance===undefined?'Indisponible':money(visaBalance,currency)}</p></div><button onClick={requestBalance} className="grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-blue-950">{showBalance?<EyeOff size={21}/>:<Eye size={21}/>}</button></div><div className="mt-4 inline-flex rounded-2xl bg-slate-100 p-1">{(['USD','CDF']as WalletCurrency[]).map(item=><button key={item} onClick={()=>{setCurrency(item);setShowBalance(false)}} className={`rounded-xl px-5 py-2 text-xs font-black ${currency===item?'bg-white text-blue-950 shadow-sm':'text-slate-500'}`}>{item}</button>)}</div></section>
    {kind==='local'&&<><section className="mx-auto mt-5 grid max-w-xl grid-cols-3 gap-2.5">{blocked?<div className="col-span-3 rounded-2xl border bg-slate-50 p-4 text-center text-sm font-bold text-slate-500">Débloquez la carte pour effectuer des opérations financières.</div>:<><Link to={`/client/cards?card=local&action=topup&currency=${currency}`} className="rounded-2xl border bg-white px-2 py-4 text-center shadow-sm"><WalletCards className="mx-auto text-blue-700" size={22}/><span className="mt-2 block text-[11px] font-black">Recharger</span></Link><Link to={`/client/wallet/pay?currency=${currency}`} className="rounded-2xl border bg-white px-2 py-4 text-center shadow-sm"><Store className="mx-auto text-blue-700" size={22}/><span className="mt-2 block text-[11px] font-black">Payer</span></Link><Link to={`/client/wallet/withdraw?currency=${currency}`} className="rounded-2xl border bg-white px-2 py-4 text-center shadow-sm"><Banknote className="mx-auto text-blue-700" size={22}/><span className="mt-2 block text-[11px] font-black">Retrait</span></Link></>}</section><section className="mx-auto mt-5 max-w-xl"><h2 className="mb-3 text-sm font-black uppercase tracking-[.14em] text-slate-500">Gestion de la carte</h2><div className="grid grid-cols-2 gap-2.5"><button disabled={actionBusy} onClick={toggleBlock} className={`rounded-2xl border p-4 text-left font-black ${blocked?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-amber-200 bg-amber-50 text-amber-800'}`}>{blocked?<Unlock size={20}/>:<Ban size={20}/>}<span className="mt-2 block text-sm">{blocked?'Débloquer':'Bloquer'}</span></button><button disabled={actionBusy} onClick={resetCard} className="rounded-2xl border bg-white p-4 text-left font-black text-blue-950"><RotateCcw size={20}/><span className="mt-2 block text-sm">Réinitialiser</span></button><button disabled={actionBusy} onClick={removeCard} className="col-span-2 rounded-2xl border border-red-200 bg-red-50 p-4 text-left font-black text-red-700"><Trash2 size={20}/><span className="mt-2 block text-sm">Supprimer la carte</span><span className="mt-1 block text-[10px] font-medium text-red-500">Possible uniquement lorsque les soldes sont à zéro.</span></button></div></section></>}
    {kind==='standard'&&<section className="mx-auto mt-5 max-w-xl"><Link to="/client/cards?visa=buy" className="flex w-full items-center justify-center gap-2 rounded-2xl bg-blue-600 px-5 py-4 text-sm font-black text-white"><ShieldCheck size={18}/>Gérer mes Visa Standard</Link></section>}
    <section className="mx-auto mt-8 max-w-xl"><div className="mb-3"><h2 className="text-lg font-black">Historique</h2><span className="text-[10px] font-black uppercase text-slate-400">Cette carte seulement</span></div><div className="overflow-hidden rounded-3xl border bg-white shadow-sm">{cardHistory.length===0?<div className="p-8 text-center text-sm font-semibold text-slate-400">Aucune opération sur cette carte.</div>:cardHistory.map((transaction,index)=>{const debit=isDebit(transaction?.type);const txCurrency=(String(transaction?.currency||currency).toUpperCase()==='CDF'?'CDF':'USD')as WalletCurrency;const amount=Number(transaction?.amount||0);return <div key={transaction?.id||transaction?.reference||index} className="flex items-center justify-between gap-4 border-b p-4 last:border-b-0"><div><p className="text-sm font-black">{transactionLabel(transaction?.type)}</p><p className="mt-1 text-[10px] text-slate-400">{transaction?.createdAt?new Date(Number(transaction.createdAt)).toLocaleString('fr-FR'):'Market-Cash'}</p></div><p className={`text-sm font-black ${debit?'text-slate-800':'text-emerald-700'}`}>{debit?'-':'+'}{money(amount,txCurrency)}</p></div>})}</div></section></>}
    <SecurityConfirmModal open={!!securityAction} busy={securityBusy} onClose={()=>!securityBusy&&setSecurityAction(null)} onConfirm={confirmSecurity} title={securityAction==='balance'?'Afficher le solde':'Afficher les informations de la carte'} subtitle="Entrez le code secret de l’application."/>
  </div>;
}
