import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,ChevronRight,CreditCard,Plus,RefreshCw,ShieldCheck,Sparkles,WalletCards}from'lucide-react';
import{Link,useNavigate,useSearchParams}from'react-router-dom';
import toast from'react-hot-toast';
import CardProductFace,{CardProductVariant}from'../../components/CardProductFace';
import SecurityConfirmModal from'../../components/SecurityConfirmModal';
import{agentWalletService,InternalCardSummary,LocalCardSecureData}from'../../services/agentWalletService';
import{cardSecurityService,VisaCardSummary,VisaSecureData}from'../../services/cardSecurityService';
import{useAuthStore}from'../../store/authStore';
import CardDetail from'./CardDetail';
import ClientCards from'./Cards';
import LocalCardTopup from'./LocalCardTopup';

type RevealTarget={kind:CardProductVariant;id:string}|null;
const friendlyLocalError=(error:any)=>{const code=String(error?.code||'').toLowerCase();const message=String(error?.message||'');if(code.includes('internal')||/^internal\s*\[?0\]?$/i.test(message.trim())||message.toLowerCase().includes('internal [0]'))return 'Le service de carte locale est momentanément en cours de synchronisation.';if(code.includes('failed-precondition')&&message.toLowerCase().includes('kyc'))return 'La validation KYC n’est pas encore synchronisée avec le service de carte.';return message||'Impossible de synchroniser la carte locale pour le moment.';};

export default function CardsHub(){
  const{user}=useAuthStore();const navigate=useNavigate();const[searchParams]=useSearchParams();
  const visaMode=searchParams.get('visa')==='buy';const selectedKind=searchParams.get('card')as CardProductVariant|null;const selectedCardId=searchParams.get('cardId');const selectedAction=searchParams.get('action');const topupChooser=selectedAction==='topup'&&!selectedKind;const requestedCurrency=searchParams.get('currency')==='CDF'?'CDF':'USD';
  const[localCard,setLocalCard]=useState<InternalCardSummary|null>(null);const[localSecure,setLocalSecure]=useState<LocalCardSecureData|null>(null);const[visaCards,setVisaCards]=useState<VisaCardSummary[]>([]);const[visaSecure,setVisaSecure]=useState<Record<string,VisaSecureData>>({});const[loadingLocal,setLoadingLocal]=useState(true);const[loadingVisa,setLoadingVisa]=useState(true);const[localError,setLocalError]=useState('');const[localRetry,setLocalRetry]=useState(0);const[revealed,setRevealed]=useState<Record<string,boolean>>({});const[pendingReveal,setPendingReveal]=useState<RevealTarget>(null);const[securityBusy,setSecurityBusy]=useState(false);

  useEffect(()=>{if(!user?.uid||visaMode||selectedKind)return;let active=true;setLoadingLocal(true);setLocalError('');(async()=>{try{await agentWalletService.ensureLocalCard();const cards=await agentWalletService.getMyInternalCards();if(active){setLocalCard(cards[0]||null);if(!cards[0])setLocalError('Votre carte n’a pas encore pu être créée. Réessayez la synchronisation.')}}catch(error:any){console.warn('[LOCAL_CARD_AUTO_READY_ERROR]',error);if(active){setLocalCard(null);setLocalError(friendlyLocalError(error));}}finally{if(active)setLoadingLocal(false)}})();return()=>{active=false}},[user?.uid,visaMode,selectedKind,localRetry]);
  useEffect(()=>{if(!user?.uid||visaMode||selectedKind)return;let active=true;setLoadingVisa(true);cardSecurityService.getMyVisaCards().then(cards=>{if(active)setVisaCards(cards)}).catch(error=>{console.warn('[VISA_SUMMARIES_ERROR]',error);if(active)setVisaCards([])}).finally(()=>{if(active)setLoadingVisa(false)});return()=>{active=false}},[user?.uid,visaMode,selectedKind]);

  const standardCards=useMemo(()=>visaCards.filter(card=>card.tier==='standard').slice(0,4),[visaCards]);const goldCard=useMemo(()=>visaCards.find(card=>card.tier==='gold')||null,[visaCards]);
  const askReveal=(kind:CardProductVariant,id:string)=>{if(revealed[id]){setRevealed(current=>({...current,[id]:false}));if(kind==='local')setLocalSecure(null);else setVisaSecure(current=>{const next={...current};delete next[id];return next});return;}setPendingReveal({kind,id});};
  const confirmReveal=async(pin:string)=>{if(!pendingReveal)return;setSecurityBusy(true);try{if(pendingReveal.kind==='local')setLocalSecure(await agentWalletService.revealLocalCardSecureData(pin));else{const secure=await cardSecurityService.revealVisaCard(pendingReveal.id,pin);setVisaSecure(current=>({...current,[pendingReveal.id]:secure}))}setRevealed(current=>({...current,[pendingReveal.id]:true}));setPendingReveal(null);}catch(error:any){toast.error(error?.message||'Code secret incorrect.')}finally{setSecurityBusy(false)}};
  const openCard=(kind:CardProductVariant,id?:string)=>navigate(`/client/cards?card=${kind}${id?`&cardId=${encodeURIComponent(id)}`:''}`);

  if(visaMode)return <div className="pb-28"><div className="mx-auto max-w-4xl px-3.5 pt-4 sm:px-6"><Link to="/client/cards" className="inline-flex items-center gap-2 text-sm font-black text-slate-500"><ArrowLeft size={17}/>Mes cartes</Link></div><ClientCards/></div>;
  if(selectedKind==='local'&&selectedAction==='topup')return <LocalCardTopup/>;
  if(selectedKind&&['local','standard','gold'].includes(selectedKind))return <CardDetail kind={selectedKind} cardId={selectedCardId}/>;

  if(topupChooser)return <div className="mx-auto max-w-xl p-4 pb-28 md:p-8"><Link to="/client/home" className="inline-flex items-center gap-2 text-sm font-black text-slate-500"><ArrowLeft size={17}/>Accueil</Link><section className="mt-5 rounded-[2rem] border bg-white p-5 shadow-sm"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-900"><WalletCards size={24}/></div><h1 className="mt-4 text-2xl font-black text-slate-950">Quelle carte voulez-vous alimenter ?</h1><p className="mt-2 text-sm leading-6 text-slate-500">Le Wallet est la source d’alimentation. Choisissez la carte à créditer.</p><div className="mt-6 space-y-3">{localCard&&<Link to={`/client/cards?card=local&action=topup&currency=${requestedCurrency}`} className="flex items-center justify-between rounded-2xl border-2 border-blue-200 bg-blue-50 p-4"><div><p className="font-black text-blue-950">Market-Cash Locale</p><p className="mt-1 font-mono text-xs text-blue-700">{localCard.maskedNumber}</p></div><ChevronRight className="text-blue-900"/></Link>}{standardCards.map(card=><div key={card.cardId} className="flex items-center justify-between rounded-2xl border p-4"><div><p className="font-black text-slate-900">Visa Standard</p><p className="mt-1 font-mono text-xs text-slate-500">{card.maskedNumber}</p><p className="mt-1 text-[10px] font-bold text-amber-700">Alimentation Wallet disponible dès connexion du flux émetteur.</p></div><CreditCard className="text-slate-400"/></div>)}{goldCard&&<div className="flex items-center justify-between rounded-2xl border border-amber-200 bg-amber-50 p-4"><div><p className="font-black text-amber-950">Visa Gold</p><p className="mt-1 font-mono text-xs text-amber-700">{goldCard.maskedNumber}</p><p className="mt-1 text-[10px] font-bold text-amber-700">Le débit Wallet sera relié à l’API de l’émetteur partenaire.</p></div><Sparkles className="text-amber-700"/></div>)}{!localCard&&!standardCards.length&&!goldCard&&!loadingLocal&&!loadingVisa&&<div className="rounded-2xl bg-slate-50 p-5 text-center text-sm font-bold text-slate-500">Aucune carte active à alimenter.</div>}</div></section></div>;

  const localKey=localCard?.cardId||'local';const kycApproved=user?.kycStatus==='approved';
  return <div className="mx-auto max-w-4xl px-3.5 pb-28 pt-4 sm:px-6"><h1 className="mb-6 text-2xl font-black tracking-tight text-slate-950">Cartes</h1>
    <section className="mb-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black uppercase tracking-[.12em] text-blue-950">Market-Cash Locale</h2>{loadingLocal&&<RefreshCw size={15} className="animate-spin text-slate-400"/>}</div>{localCard?<div role="button" tabIndex={0} onClick={()=>openCard('local',localCard.cardId)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')openCard('local',localCard.cardId)}} className="cursor-pointer rounded-[1.65rem] outline-none ring-blue-300 focus:ring-4"><CardProductFace variant="local" holder={localSecure?.cardHolder||localCard.cardHolder||user?.displayName} number={localSecure?.cardNumber||localCard.maskedNumber} expiryStart={localSecure?.expiryStart||localCard.expiryStart} expiryEnd={localSecure?.expiryEnd||localCard.expiryEnd} cvv={localSecure?.cvv} qrData={localCard.qrData} revealed={!!revealed[localKey]} onToggleReveal={()=>askReveal('local',localKey)} className="transition duration-200 active:scale-[.985]"/></div>:!loadingLocal?<div className={`rounded-3xl border border-dashed p-5 ${kycApproved?'border-blue-200 bg-blue-50':'border-amber-300 bg-amber-50'}`}><p className={`font-black ${kycApproved?'text-blue-950':'text-amber-900'}`}>{kycApproved?'Activation de la carte locale':'Carte locale non encore active'}</p><p className={`mt-1 text-sm leading-6 ${kycApproved?'text-blue-800':'text-amber-800'}`}>{kycApproved?(localError||'Votre KYC est vérifié. La carte gratuite doit être créée automatiquement.'):(localError||"La carte gratuite devient disponible après l'approbation du KYC.")}</p><button onClick={()=>setLocalRetry(value=>value+1)} className={`mt-4 inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-black ${kycApproved?'bg-blue-950 text-white':'bg-white text-amber-900'}`}><RefreshCw size={14}/>Réessayer la synchronisation</button></div>:null}{localCard&&<div className="mt-3 grid grid-cols-2 gap-2"><Link to={`/client/cards?card=local&cardId=${encodeURIComponent(localCard.cardId)}`} className="flex items-center justify-center gap-2 rounded-2xl border bg-white px-4 py-3 text-sm font-black text-blue-950"><ShieldCheck size={16}/>Détails</Link><Link to={`/client/cards?card=local&action=topup&currency=${requestedCurrency}`} className="flex items-center justify-center gap-2 rounded-2xl bg-blue-950 px-4 py-3 text-sm font-black text-white"><Plus size={16}/>Recharger</Link></div>}</section>
    <section className="mb-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black uppercase tracking-[.12em] text-slate-700">Market-Cash Visa Standard</h2>{loadingVisa?<RefreshCw size={15} className="animate-spin text-slate-400"/>:standardCards.length>0&&standardCards.length<4?<Link to="/client/cards?visa=buy" className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 text-slate-700"><Plus size={16}/></Link>:null}</div>{standardCards.length>0?<div className="flex snap-x snap-mandatory gap-3 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{standardCards.map(card=>{const secure=visaSecure[card.cardId];return <div key={card.cardId} role="button" tabIndex={0} onClick={()=>openCard('standard',card.cardId)} className="w-[88%] shrink-0 snap-center cursor-pointer rounded-[1.65rem]"><CardProductFace variant="standard" holder={secure?.cardHolder||card.cardHolder||user?.displayName} number={secure?.cardNumber||card.maskedNumber} expiryStart={secure?.expiryStart} expiryEnd={secure?.expiryEnd} cvv={secure?.cvv} revealed={!!revealed[card.cardId]} onToggleReveal={()=>askReveal('standard',card.cardId)}/></div>})}</div>:!loadingVisa?<ProductEmptyState icon={<CreditCard size={24}/>} title="Aucune Visa Standard active" text="Une Visa apparaît ici uniquement après approbation et attribution réelle. Vous pouvez en posséder jusqu'à quatre." action="Obtenir une Visa Standard" to="/client/cards?visa=buy"/>:null}</section>
    <section><div className="mb-3"><h2 className="text-sm font-black uppercase tracking-[.12em] text-amber-800">Market-Cash Visa Gold</h2></div>{goldCard?(()=>{const secure=visaSecure[goldCard.cardId];return <div role="button" tabIndex={0} onClick={()=>openCard('gold',goldCard.cardId)} className="cursor-pointer rounded-[1.65rem]"><CardProductFace variant="gold" holder={secure?.cardHolder||goldCard.cardHolder||user?.displayName} number={secure?.cardNumber||goldCard.maskedNumber} expiryStart={secure?.expiryStart} expiryEnd={secure?.expiryEnd} cvv={secure?.cvv} revealed={!!revealed[goldCard.cardId]} onToggleReveal={()=>askReveal('gold',goldCard.cardId)}/></div>})():!loadingVisa?<ProductEmptyState icon={<Sparkles size={24}/>} title="Visa Gold non émise" text="Cette gamme est réservée aux cartes réellement émises par un partenaire connecté. Aucune donnée de démonstration n'est générée." action="Voir les cartes Visa" to="/client/cards?visa=buy" gold/>:null}</section>
    <SecurityConfirmModal open={!!pendingReveal} busy={securityBusy} onClose={()=>!securityBusy&&setPendingReveal(null)} onConfirm={confirmReveal} title="Afficher les informations de la carte" subtitle="Entrez le code secret de l’application."/>
  </div>;
}

function ProductEmptyState({icon,title,text,action,to,gold=false}:{icon:React.ReactNode;title:string;text:string;action:string;to:string;gold?:boolean}){return <div className={`rounded-[1.75rem] border p-5 ${gold?'border-amber-200 bg-amber-50/70':'border-slate-200 bg-white'} shadow-sm`}><div className={`grid h-12 w-12 place-items-center rounded-2xl ${gold?'bg-amber-100 text-amber-800':'bg-slate-100 text-blue-950'}`}>{icon}</div><h3 className="mt-4 text-lg font-black text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><Link to={to} className={`mt-4 flex items-center justify-between rounded-2xl px-4 py-3 text-sm font-black ${gold?'bg-amber-400 text-blue-950':'bg-blue-950 text-white'}`}><span>{action}</span><ChevronRight size={17}/></Link></div>}
