import React,{useEffect,useRef,useState}from'react';
import{doc,getDoc,setDoc}from'firebase/firestore';
import{getDownloadURL,ref,uploadBytes}from'firebase/storage';
import{ArrowLeft,Camera,FileImage,Images,ShieldCheck,UserRound,X,Check,Crop as CropIcon}from'lucide-react';
import{Link}from'react-router-dom';
import toast from'react-hot-toast';
import{db,storage}from'../../firebase/config';
import{useAuthStore}from'../../store/authStore';

const MAX_FILE_SIZE=12*1024*1024;
const ACCEPTED=['image/jpeg','image/png','image/webp'];
type PhotoType='document'|'portrait';
type CropDraft={file:File;url:string;type:PhotoType};

async function optimizeImage(file:File,maxSide=1800,quality=.86):Promise<File>{
  if(!ACCEPTED.includes(file.type))throw new Error('FORMAT');
  if(file.size>MAX_FILE_SIZE)throw new Error('SIZE');
  try{
    const bitmap=await createImageBitmap(file);
    const ratio=Math.min(1,maxSide/Math.max(bitmap.width,bitmap.height));
    const w=Math.max(1,Math.round(bitmap.width*ratio));
    const h=Math.max(1,Math.round(bitmap.height*ratio));
    const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;
    const ctx=canvas.getContext('2d');if(!ctx)throw new Error('CANVAS');
    ctx.drawImage(bitmap,0,0,w,h);bitmap.close();
    const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('BLOB')),'image/jpeg',quality));
    return new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg',lastModified:Date.now()});
  }catch(err){
    console.warn('[KYC_IMAGE_OPTIMIZE_FALLBACK]',err);
    return file;
  }
}

export default function ClientKyc(){
 const{user,setUser}=useAuthStore();
 const[status,setStatus]=useState('not_started');
 const[busy,setBusy]=useState(false);
 const[documentFile,setDocumentFile]=useState<File|null>(null);
 const[portraitFile,setPortraitFile]=useState<File|null>(null);
 const[documentPreview,setDocumentPreview]=useState('');
 const[portraitPreview,setPortraitPreview]=useState(user?.avatar||'');
 const[cropDraft,setCropDraft]=useState<CropDraft|null>(null);
 const[form,setForm]=useState({fullName:user?.displayName||'',phone:user?.phone||'',country:'RDC',city:'',address:'',documentType:'national_id',documentNumber:''});

 useEffect(()=>{if(!user?.uid)return;getDoc(doc(db,'kyc_requests',user.uid)).then(s=>{if(s.exists()){const d=s.data();setStatus(d.status||'pending');setForm(f=>({...f,fullName:d.fullName||f.fullName,phone:d.phone||f.phone,country:d.country||f.country,city:d.city||'',address:d.address||'',documentType:d.documentType||'national_id',documentNumber:d.documentNumber||''}));setDocumentPreview(d.documentFrontUrl||'');setPortraitPreview(d.selfieUrl||user.avatar||'')}}).catch(err=>console.error('[KYC_LOAD_ERROR]',err))},[user?.uid]);

 const prepareFile=async(file:File|undefined,type:PhotoType)=>{if(!file)return;try{toast.loading('Préparation de la photo...',{id:'kyc-image'});const optimized=await optimizeImage(file);const url=URL.createObjectURL(optimized);setCropDraft({file:optimized,url,type});toast.dismiss('kyc-image')}catch(err:any){toast.dismiss('kyc-image');toast.error(err?.message==='SIZE'?'Image trop lourde. Maximum 12 Mo.':'Format non accepté. Utilisez JPG, PNG ou WEBP.')}};
 const acceptCrop=(file:File,url:string,type:PhotoType)=>{if(type==='document'){if(documentPreview.startsWith('blob:'))URL.revokeObjectURL(documentPreview);setDocumentFile(file);setDocumentPreview(url)}else{if(portraitPreview.startsWith('blob:'))URL.revokeObjectURL(portraitPreview);setPortraitFile(file);setPortraitPreview(url)}setCropDraft(null)};
 const upload=async(file:File,path:string)=>{const fileRef=ref(storage,path);await uploadBytes(fileRef,file,{contentType:file.type});return getDownloadURL(fileRef)};

 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!user)return;if(!documentFile&&!documentPreview){toast.error("Ajoutez une photo de votre pièce d'identité.");return}if(!portraitFile&&!portraitPreview){toast.error('Ajoutez votre photo portrait.');return}setBusy(true);try{const now=Date.now();let documentFrontUrl=documentPreview;let selfieUrl=portraitPreview;if(documentFile)documentFrontUrl=await upload(documentFile,`kyc/${user.uid}/document-${now}.jpg`);if(portraitFile)selfieUrl=await upload(portraitFile,`avatars/${user.uid}/profile-${now}.jpg`);const existing=await getDoc(doc(db,'kyc_requests',user.uid));await setDoc(doc(db,'kyc_requests',user.uid),{userId:user.uid,...form,documentFrontUrl,selfieUrl,status:'pending',updatedAt:now,...(!existing.exists()?{createdAt:now}:{})},{merge:true});if(selfieUrl&&selfieUrl!==user.avatar){await setDoc(doc(db,'users',user.uid),{avatar:selfieUrl,updatedAt:now},{merge:true});setUser({...user,avatar:selfieUrl,updatedAt:now})}setStatus('pending');toast.success('Dossier KYC envoyé pour vérification.')}catch(err:any){console.error('[KYC_SUBMIT_ERROR]',err);toast.error(err?.code==='storage/unauthorized'||err?.code==='permission-denied'?"Autorisation Firebase refusée. Vérifiez le déploiement des règles KYC.":"Impossible d'envoyer le dossier KYC. Réessayez.")}finally{setBusy(false)}};
 if(!user)return null;
 return <div className="mx-auto max-w-xl p-4 md:p-8 pb-28"><Link to="/client/profile" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Retour au profil</Link><div className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-950"><ShieldCheck/></div><h1 className="mt-4 text-2xl font-black">Vérification d'identité KYC</h1><p className="mt-2 text-sm text-slate-500">Vérifiez votre identité une seule fois pour sécuriser votre compte et débloquer les services sensibles.</p><div className={`mt-4 rounded-2xl p-3 text-sm font-bold ${status==='approved'?'bg-emerald-50 text-emerald-700':status==='rejected'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>Statut : {status==='approved'?'Vérifié':status==='rejected'?'À corriger':'En attente / non complété'}</div>{status!=='approved'&&<form onSubmit={submit} className="mt-5 space-y-3"><input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="Nom complet" className="w-full rounded-2xl border p-4"/><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Téléphone" className="w-full rounded-2xl border p-4"/><div className="grid grid-cols-2 gap-3"><input required value={form.country} onChange={e=>setForm({...form,country:e.target.value})} placeholder="Pays" className="w-full rounded-2xl border p-4"/><input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="Ville" className="w-full rounded-2xl border p-4"/></div><input required value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Adresse" className="w-full rounded-2xl border p-4"/><select value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})} className="w-full rounded-2xl border p-4"><option value="national_id">Carte d'identité</option><option value="passport">Passeport</option><option value="driving_licence">Permis de conduire</option><option value="other">Autre document officiel</option></select><input required value={form.documentNumber} onChange={e=>setForm({...form,documentNumber:e.target.value})} placeholder="Numéro du document" className="w-full rounded-2xl border p-4"/>
 <UploadBox title="Pièce d'identité" text="Photographiez ou importez une image claire et lisible." icon={<FileImage size={22}/>} preview={documentPreview} type="document" onFile={f=>prepareFile(f,'document')}/>
 <UploadBox title="Portrait photographique" text="Photo nette du visage. Elle deviendra aussi votre photo de profil Market-Cash." icon={<UserRound size={22}/>} preview={portraitPreview} type="portrait" onFile={f=>prepareFile(f,'portrait')}/>
 <div className="rounded-2xl bg-blue-50 p-4 text-xs leading-5 text-blue-950"><b>Protection mémoire :</b> Market-Cash réduit automatiquement les photos haute résolution avant affichage et envoi.</div><button disabled={busy} className="w-full rounded-2xl bg-blue-950 py-4 font-black text-white disabled:opacity-50">{busy?'Envoi sécurisé...':'Envoyer mon dossier KYC'}</button></form>}</div>{cropDraft&&<CropModal draft={cropDraft} onCancel={()=>{URL.revokeObjectURL(cropDraft.url);setCropDraft(null)}} onConfirm={acceptCrop}/>}</div>
}

function UploadBox({title,text,icon,preview,type,onFile}:{title:string;text:string;icon:React.ReactNode;preview:string;type:PhotoType;onFile:(file:File|undefined)=>void}){
 const cameraRef=useRef<HTMLInputElement>(null);const galleryRef=useRef<HTMLInputElement>(null);const[chooser,setChooser]=useState(false);
 return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white text-blue-950 shadow-sm">{icon}</div><div><div className="font-black text-slate-900">{title}</div><div className="text-xs leading-5 text-slate-500">{text}</div></div></div>{preview&&<img src={preview} alt={title} className={`mt-3 w-full rounded-2xl border bg-white ${type==='portrait'?'h-52 object-contain':'h-40 object-contain'}`}/>}<button type="button" onClick={()=>setChooser(true)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-white border border-blue-200 px-4 py-3 text-sm font-black text-blue-950"><Camera size={18}/> Ajouter / remplacer la photo</button><input ref={cameraRef} type="file" accept="image/jpeg,image/png,image/webp" capture={type==='portrait'?'user':'environment'} className="hidden" onChange={e=>{setChooser(false);onFile(e.target.files?.[0]);e.currentTarget.value=''}}/><input ref={galleryRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>{setChooser(false);onFile(e.target.files?.[0]);e.currentTarget.value=''}}/>{chooser&&<div className="fixed inset-0 z-50 flex items-end bg-black/50" onClick={()=>setChooser(false)}><div className="w-full rounded-t-3xl bg-white p-5 pb-8" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-5 h-1.5 w-12 rounded-full bg-slate-200"/><h3 className="text-lg font-black">Choisir la source</h3><p className="mt-1 text-sm text-slate-500">Vous pourrez rogner la photo avant de la confirmer.</p><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={()=>cameraRef.current?.click()} className="rounded-2xl border p-5 font-bold"><Camera className="mx-auto mb-2"/>Prendre une photo</button><button type="button" onClick={()=>galleryRef.current?.click()} className="rounded-2xl border p-5 font-bold"><Images className="mx-auto mb-2"/>Téléverser</button></div><button type="button" onClick={()=>setChooser(false)} className="mt-3 w-full rounded-2xl bg-slate-100 py-3 font-bold">Annuler</button></div></div>}</div>
}

function CropModal({draft,onCancel,onConfirm}:{draft:CropDraft;onCancel:()=>void;onConfirm:(file:File,url:string,type:PhotoType)=>void}){
 const imgRef=useRef<HTMLImageElement>(null);const frameRef=useRef<HTMLDivElement>(null);const[zoom,setZoom]=useState(1);const[offset,setOffset]=useState({x:0,y:0});const drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);const[working,setWorking]=useState(false);
 const aspect=draft.type==='portrait'?1:1.586;
 const start=(e:React.PointerEvent)=>{drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)};
 const move=(e:React.PointerEvent)=>{if(!drag.current)return;setOffset({x:drag.current.ox+e.clientX-drag.current.x,y:drag.current.oy+e.clientY-drag.current.y})};
 const finish=()=>{drag.current=null};
 const confirm=async()=>{const img=imgRef.current,frame=frameRef.current;if(!img||!frame)return;setWorking(true);try{const cw=frame.clientWidth,ch=frame.clientHeight;const base=Math.max(cw/img.naturalWidth,ch/img.naturalHeight);const scale=base*zoom;const dw=img.naturalWidth*scale,dh=img.naturalHeight*scale;const dx=(cw-dw)/2+offset.x,dy=(ch-dh)/2+offset.y;const outW=draft.type==='portrait'?1000:1400;const outH=Math.round(outW/aspect);const sx=(-dx)/scale,sy=(-dy)/scale,sw=cw/scale,sh=ch/scale;const canvas=document.createElement('canvas');canvas.width=outW;canvas.height=outH;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('CANVAS');ctx.drawImage(img,Math.max(0,sx),Math.max(0,sy),Math.min(sw,img.naturalWidth-Math.max(0,sx)),Math.min(sh,img.naturalHeight-Math.max(0,sy)),0,0,outW,outH);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('BLOB')),'image/jpeg',.86));const file=new File([blob],`${draft.type}-${Date.now()}.jpg`,{type:'image/jpeg'});const url=URL.createObjectURL(file);URL.revokeObjectURL(draft.url);onConfirm(file,url,draft.type)}catch(err){console.error('[KYC_CROP_ERROR]',err);toast.error('Impossible de rogner cette image.')}finally{setWorking(false)}};
 return <div className="fixed inset-0 z-[60] flex items-end bg-black/70"><div className="w-full rounded-t-3xl bg-white p-4 pb-7"><div className="flex items-center justify-between"><div><h3 className="text-lg font-black">Recadrer la photo</h3><p className="text-xs text-slate-500">Glissez l'image puis utilisez le zoom.</p></div><button type="button" onClick={onCancel} className="rounded-full bg-slate-100 p-2"><X/></button></div><div ref={frameRef} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} className="relative mx-auto mt-4 w-full max-w-md touch-none overflow-hidden rounded-2xl bg-black" style={{aspectRatio:String(aspect)}}><img ref={imgRef} src={draft.url} alt="Recadrage" draggable={false} className="absolute inset-0 h-full w-full select-none object-cover" style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${zoom})`,transformOrigin:'center'}}/><div className="pointer-events-none absolute inset-3 rounded-xl border-2 border-white/80"/></div><div className="mt-4 flex items-center gap-3"><CropIcon size={20}/><input className="w-full" type="range" min="1" max="2.5" step="0.05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><span className="w-12 text-right text-sm font-bold">{Math.round(zoom*100)}%</span></div><div className="mt-4 grid grid-cols-2 gap-3"><button type="button" onClick={onCancel} className="rounded-2xl bg-slate-100 py-4 font-black">Reprendre</button><button type="button" disabled={working} onClick={confirm} className="flex items-center justify-center gap-2 rounded-2xl bg-blue-950 py-4 font-black text-white disabled:opacity-50"><Check size={18}/>{working?'Traitement...':'Valider'}</button></div></div></div>
}
