import React,{useEffect,useState}from'react';
import{doc,getDoc,setDoc}from'firebase/firestore';
import{getDownloadURL,ref,uploadBytes}from'firebase/storage';
import{ArrowLeft,Camera,FileImage,ShieldCheck,UserRound}from'lucide-react';
import{Link}from'react-router-dom';
import toast from'react-hot-toast';
import{db,storage}from'../../firebase/config';
import{useAuthStore}from'../../store/authStore';

const MAX_FILE_SIZE=5*1024*1024;
const ACCEPTED=['image/jpeg','image/png','image/webp'];

export default function ClientKyc(){
 const{user,setUser}=useAuthStore();
 const[status,setStatus]=useState('not_started');
 const[busy,setBusy]=useState(false);
 const[documentFile,setDocumentFile]=useState<File|null>(null);
 const[portraitFile,setPortraitFile]=useState<File|null>(null);
 const[documentPreview,setDocumentPreview]=useState('');
 const[portraitPreview,setPortraitPreview]=useState(user?.avatar||'');
 const[form,setForm]=useState({fullName:user?.displayName||'',phone:user?.phone||'',country:'RDC',city:'',address:'',documentType:'national_id',documentNumber:''});

 useEffect(()=>{if(!user?.uid)return;getDoc(doc(db,'kyc_requests',user.uid)).then(s=>{if(s.exists()){const d=s.data();setStatus(d.status||'pending');setForm(f=>({...f,fullName:d.fullName||f.fullName,phone:d.phone||f.phone,country:d.country||f.country,city:d.city||'',address:d.address||'',documentType:d.documentType||'national_id',documentNumber:d.documentNumber||''}));setDocumentPreview(d.documentFrontUrl||'');setPortraitPreview(d.selfieUrl||user.avatar||'')}}).catch(err=>console.error('[KYC_LOAD_ERROR]',err))},[user?.uid]);

 const chooseFile=(file:File|undefined,type:'document'|'portrait')=>{if(!file)return;if(!ACCEPTED.includes(file.type)){toast.error('Format non accepté. Utilisez JPG, PNG ou WEBP.');return}if(file.size>MAX_FILE_SIZE){toast.error('La photo ne doit pas dépasser 5 Mo.');return}const preview=URL.createObjectURL(file);if(type==='document'){setDocumentFile(file);setDocumentPreview(preview)}else{setPortraitFile(file);setPortraitPreview(preview)}};
 const upload=async(file:File,path:string)=>{const fileRef=ref(storage,path);await uploadBytes(fileRef,file,{contentType:file.type});return getDownloadURL(fileRef)};

 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!user)return;if(!documentFile&&!documentPreview){toast.error("Ajoutez une photo de votre pièce d'identité.");return}if(!portraitFile&&!portraitPreview){toast.error('Ajoutez votre photo portrait.');return}setBusy(true);try{const now=Date.now();let documentFrontUrl=documentPreview;let selfieUrl=portraitPreview;if(documentFile)documentFrontUrl=await upload(documentFile,`kyc/${user.uid}/document-${now}`);if(portraitFile)selfieUrl=await upload(portraitFile,`avatars/${user.uid}/profile-${now}`);const existing=await getDoc(doc(db,'kyc_requests',user.uid));const payload={userId:user.uid,...form,documentFrontUrl,selfieUrl,status:'pending',updatedAt:now,...(!existing.exists()?{createdAt:now}:{})};await setDoc(doc(db,'kyc_requests',user.uid),payload,{merge:true});if(selfieUrl&&selfieUrl!==user.avatar){await setDoc(doc(db,'users',user.uid),{avatar:selfieUrl,updatedAt:now},{merge:true});setUser({...user,avatar:selfieUrl,updatedAt:now})}setStatus('pending');toast.success('Dossier KYC envoyé pour vérification.')}catch(err:any){console.error('[KYC_SUBMIT_ERROR]',err);toast.error(err?.code==='storage/unauthorized'||err?.code==='permission-denied'?"Autorisation Firebase refusée. Les règles KYC doivent être déployées.":"Impossible d'envoyer le dossier KYC. Réessayez.")}finally{setBusy(false)}};
 if(!user)return null;
 return <div className="mx-auto max-w-xl p-4 md:p-8 pb-28"><Link to="/client/profile" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Retour au profil</Link><div className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-950"><ShieldCheck/></div><h1 className="mt-4 text-2xl font-black">Vérification d'identité KYC</h1><p className="mt-2 text-sm text-slate-500">Vérifiez votre identité une seule fois pour sécuriser votre compte et débloquer les services sensibles.</p><div className={`mt-4 rounded-2xl p-3 text-sm font-bold ${status==='approved'?'bg-emerald-50 text-emerald-700':status==='rejected'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>Statut : {status==='approved'?'Vérifié':status==='rejected'?'À corriger':'En attente / non complété'}</div>{status!=='approved'&&<form onSubmit={submit} className="mt-5 space-y-3"><input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="Nom complet" className="w-full rounded-2xl border p-4"/><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Téléphone" className="w-full rounded-2xl border p-4"/><div className="grid grid-cols-2 gap-3"><input required value={form.country} onChange={e=>setForm({...form,country:e.target.value})} placeholder="Pays" className="w-full rounded-2xl border p-4"/><input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="Ville" className="w-full rounded-2xl border p-4"/></div><input required value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Adresse" className="w-full rounded-2xl border p-4"/><select value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})} className="w-full rounded-2xl border p-4"><option value="national_id">Carte d'identité</option><option value="passport">Passeport</option><option value="driving_licence">Permis de conduire</option><option value="other">Autre document officiel</option></select><input required value={form.documentNumber} onChange={e=>setForm({...form,documentNumber:e.target.value})} placeholder="Numéro du document" className="w-full rounded-2xl border p-4"/>
 <UploadBox title="Pièce d'identité" text="Photographiez ou importez une image claire et lisible." icon={<FileImage size={22}/>} preview={documentPreview} capture="environment" onFile={f=>chooseFile(f,'document')}/>
 <UploadBox title="Photo portrait" text="Prenez une photo nette de votre visage. Elle deviendra aussi votre photo de profil Market-Cash." icon={<UserRound size={22}/>} preview={portraitPreview} capture="user" onFile={f=>chooseFile(f,'portrait')}/>
 <div className="rounded-2xl bg-blue-50 p-4 text-xs leading-5 text-blue-950"><b>Conseil :</b> utilisez une bonne lumière, évitez les reflets sur la pièce et gardez votre visage entièrement visible sur le portrait.</div><button disabled={busy} className="w-full rounded-2xl bg-blue-950 py-4 font-black text-white disabled:opacity-50">{busy?'Envoi sécurisé...':'Envoyer mon dossier KYC'}</button></form>}</div></div>
}

function UploadBox({title,text,icon,preview,capture,onFile}:{title:string;text:string;icon:React.ReactNode;preview:string;capture:'user'|'environment';onFile:(file:File|undefined)=>void}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white text-blue-950 shadow-sm">{icon}</div><div><div className="font-black text-slate-900">{title}</div><div className="text-xs leading-5 text-slate-500">{text}</div></div></div>{preview&&<img src={preview} alt={title} className="mt-3 h-40 w-full rounded-2xl border bg-white object-contain"/>}<label className="mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-white border border-blue-200 px-4 py-3 text-sm font-black text-blue-950"><Camera size={18}/> Capturer ou importer<input type="file" accept="image/jpeg,image/png,image/webp" capture={capture} className="hidden" onChange={e=>onFile(e.target.files?.[0])}/></label></div>}
