import React,{useEffect,useState}from'react';
import{doc,getDoc,setDoc}from'firebase/firestore';
import{ArrowLeft,ShieldCheck}from'lucide-react';
import{Link}from'react-router-dom';
import toast from'react-hot-toast';
import{db}from'../../firebase/config';
import{useAuthStore}from'../../store/authStore';

export default function ClientKyc(){
 const{user}=useAuthStore();
 const[status,setStatus]=useState('not_started');
 const[busy,setBusy]=useState(false);
 const[form,setForm]=useState({fullName:user?.displayName||'',phone:user?.phone||'',birthDate:'',country:'RDC',city:'',address:'',documentType:'national_id',documentNumber:''});
 useEffect(()=>{if(!user?.uid)return;getDoc(doc(db,'kyc_requests',user.uid)).then(s=>{if(s.exists()){const d=s.data();setStatus(d.status||'pending');setForm(f=>({...f,...d}))}}).catch(()=>{})},[user?.uid]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!user)return;setBusy(true);try{const now=Date.now();await setDoc(doc(db,'kyc_requests',user.uid),{userId:user.uid,...form,status:'pending',createdAt:now,updatedAt:now},{merge:true});setStatus('pending');toast.success("Dossier KYC envoyé pour vérification.")}catch(err){console.error(err);toast.error("Impossible d'envoyer le dossier KYC.")}finally{setBusy(false)}};
 if(!user)return null;
 return <div className="mx-auto max-w-xl p-4 md:p-8 pb-28"><Link to="/client/profile" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Retour au profil</Link><div className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-950"><ShieldCheck/></div><h1 className="mt-4 text-2xl font-black">Vérification d'identité KYC</h1><p className="mt-2 text-sm text-slate-500">Une seule vérification d'identité débloque les transferts, dépôts, cartes et autres services sensibles.</p><div className={`mt-4 rounded-2xl p-3 text-sm font-bold ${status==='approved'?'bg-emerald-50 text-emerald-700':status==='rejected'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>Statut : {status==='approved'?'Vérifié':status==='rejected'?'À corriger':'En attente / non complété'}</div>{status!=='approved'&&<form onSubmit={submit} className="mt-5 space-y-3"><input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="Nom complet" className="w-full rounded-2xl border p-4"/><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Téléphone" className="w-full rounded-2xl border p-4"/><input required type="date" value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})} className="w-full rounded-2xl border p-4"/><div className="grid grid-cols-2 gap-3"><input required value={form.country} onChange={e=>setForm({...form,country:e.target.value})} placeholder="Pays" className="w-full rounded-2xl border p-4"/><input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="Ville" className="w-full rounded-2xl border p-4"/></div><input required value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Adresse" className="w-full rounded-2xl border p-4"/><select value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})} className="w-full rounded-2xl border p-4"><option value="national_id">Carte d'identité</option><option value="passport">Passeport</option><option value="driving_licence">Permis de conduire</option><option value="other">Autre document officiel</option></select><input required value={form.documentNumber} onChange={e=>setForm({...form,documentNumber:e.target.value})} placeholder="Numéro du document" className="w-full rounded-2xl border p-4"/><div className="rounded-2xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">Les uploads photo du document et selfie seront branchés sur Firebase Storage dans l'étape KYC avancée. Ce formulaire prépare déjà le dossier administratif et son statut.</div><button disabled={busy} className="w-full rounded-2xl bg-blue-950 py-4 font-black text-white disabled:opacity-50">{busy?'Envoi...':'Envoyer mon dossier KYC'}</button></form>}</div></div>
}
