import{useEffect,useMemo,useState}from'react';
import{collection,doc,getDoc,getDocs,query,setDoc,updateDoc,where}from'firebase/firestore';
import{Building2,Edit3,Fingerprint,Key,LogOut,Shield,ShieldCheck,Store,User,X}from'lucide-react';
import{Link}from'react-router-dom';
import toast from'react-hot-toast';
import{useAuthStore}from'../../store/authStore';
import{db}from'../../firebase/config';
import LogoutModal from'../../components/LogoutModal';

export default function ClientProfile(){
 const{user,setUser}=useAuthStore();const[cardCount,setCardCount]=useState(0);const[showLogout,setShowLogout]=useState(false);const[kycStatus,setKycStatus]=useState('not_started');const[upgradeStatus,setUpgradeStatus]=useState('');const[showUpgrade,setShowUpgrade]=useState(false);const[accountType,setAccountType]=useState<'agent'|'marchand'>('marchand');const[activity,setActivity]=useState('');const[city,setCity]=useState('');const[address,setAddress]=useState('');const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);const[showEdit,setShowEdit]=useState(false);const[name,setName]=useState(user?.displayName||'');const[phone,setPhone]=useState(user?.phone||'');const[useBiometrics,setUseBiometrics]=useState(!!user?.useBiometrics);
 useEffect(()=>{if(!user)return;(async()=>{try{const q=query(collection(db,'cards'),where('userId','==',user.uid));setCardCount((await getDocs(q)).size)}catch{}try{const k=await getDoc(doc(db,'kyc_requests',user.uid));setKycStatus(k.exists()?k.data().status||'pending':'not_started')}catch{}try{const r=await getDoc(doc(db,'account_upgrade_requests',user.uid));setUpgradeStatus(r.exists()?r.data().status||'pending':'')}catch{}})();setName(user.displayName||'');setPhone(user.phone||'');setUseBiometrics(!!user.useBiometrics)},[user?.uid]);
 const since=useMemo(()=>user?.createdAt&&!Number.isNaN(new Date(user.createdAt).getTime())?new Date(user.createdAt).toLocaleDateString('fr-FR'):'Date non disponible',[user?.createdAt]);
 if(!user)return null;
 const saveProfile=async(e:any)=>{e.preventDefault();setBusy(true);try{await updateDoc(doc(db,'users',user.uid),{displayName:name.trim(),phone:phone.trim(),updatedAt:Date.now()});setUser({...user,displayName:name.trim(),phone:phone.trim()});setShowEdit(false);toast.success('Profil mis à jour.')}catch{toast.error('Modification impossible.')}finally{setBusy(false)}};
 const toggleBio=async()=>{const next=!useBiometrics;try{await updateDoc(doc(db,'users',user.uid),{useBiometrics:next,updatedAt:Date.now()});setUseBiometrics(next);setUser({...user,useBiometrics:next})}catch{toast.error('Modification impossible.')}};
 const submitUpgrade=async(e:any)=>{e.preventDefault();if(kycStatus!=='approved')return toast.error("Complétez d'abord votre identité KYC.");setBusy(true);try{const now=Date.now();await setDoc(doc(db,'account_upgrade_requests',user.uid),{userId:user.uid,requestedType:accountType,legalName:user.displayName,activity:activity.trim(),phone:user.phone||'',city:city.trim(),address:address.trim(),reason:reason.trim(),status:'pending',createdAt:now,updatedAt:now});setUpgradeStatus('pending');setShowUpgrade(false);toast.success('Demande envoyée à l’administration.')}catch{toast.error("Impossible d'envoyer la demande.")}finally{setBusy(false)}};
 return <div className="mx-auto max-w-2xl p-4 md:p-8 pb-28 space-y-5"><header><p className="text-sm font-semibold text-slate-500">Compte Market-Cash</p><h1 className="mt-1 text-3xl font-black text-slate-950">Mon profil</h1></header>
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex gap-4 items-center"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-blue-950 text-white">{user.avatar?<img src={user.avatar} className="h-full w-full rounded-2xl object-cover"/>:<User/>}</div><div className="min-w-0"><h2 className="truncate text-xl font-black">{user.displayName}</h2><p className="truncate text-sm text-slate-500">{user.email}</p><span className="mt-2 inline-block rounded-full bg-slate-100 px-3 py-1 text-[11px] font-black uppercase text-slate-600">{user.role==='marchand'?'Marchand':user.role==='agent'?'Agent':'Client'}</span></div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-50 p-4"><b className="text-2xl text-blue-950">{cardCount}</b><p className="text-xs text-slate-500">Cartes</p></div><div className="rounded-2xl bg-slate-50 p-4"><b className="text-sm">{since}</b><p className="text-xs text-slate-500">Membre depuis</p></div></div></section>
 <section className={`rounded-3xl border p-5 shadow-sm ${kycStatus==='approved'?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className="flex gap-3"><ShieldCheck className={kycStatus==='approved'?'text-emerald-700':'text-amber-700'}/><div><h2 className="font-black">Identité KYC</h2><p className="text-sm text-slate-600">{kycStatus==='approved'?'Votre identité est vérifiée. Tous les services KYC sont accessibles.':kycStatus==='pending'?'Votre dossier est en cours de vérification.':'Complétez votre identité pour utiliser les services financiers sensibles.'}</p></div></div>{kycStatus!=='approved'&&<Link to="/client/kyc" className="mt-4 inline-flex rounded-2xl bg-blue-950 px-4 py-3 text-sm font-black text-white">Compléter mon identité</Link>}</section>
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex gap-3"><Store className="text-blue-800"/><div><h2 className="font-black">Changer de type de compte</h2><p className="text-sm text-slate-500">Un client vérifié peut demander un compte Agent ou Marchand. L’administration valide chaque demande.</p></div></div>{upgradeStatus&&<div className="mt-4 rounded-2xl bg-slate-50 p-3 text-sm font-bold">Demande actuelle : {upgradeStatus==='pending'?'en attente':upgradeStatus==='approved'?'approuvée':'rejetée'}</div>}{user.role==='client'&&<button onClick={()=>setShowUpgrade(true)} className="mt-4 rounded-2xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-black text-blue-900">Créer un compte Agent / Business</button>}</section>
 <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex gap-3"><Shield className="text-blue-900"/><div><h2 className="font-black">Sécurité du compte</h2><p className="text-xs text-slate-500">La connexion protège votre compte. Le PIN confirme les opérations sensibles.</p></div></div><button onClick={toggleBio} className="mt-4 flex w-full items-center justify-between rounded-2xl bg-slate-50 p-4"><span className="flex gap-3 items-center"><Fingerprint className="text-blue-800"/><span className="text-sm font-bold">Empreinte digitale</span></span><span className={`h-7 w-12 rounded-full p-1 ${useBiometrics?'bg-blue-950':'bg-slate-300'}`}><span className={`block h-5 w-5 rounded-full bg-white transition ${useBiometrics?'translate-x-5':''}`}/></span></button></section>
 <section className="overflow-hidden rounded-3xl border bg-white shadow-sm divide-y"><button onClick={()=>setShowEdit(true)} className="flex w-full gap-3 p-5 text-left"><Edit3 className="text-blue-800"/><span><b>Modifier mon profil</b><small className="block text-slate-500">Nom et téléphone</small></span></button><button className="flex w-full gap-3 p-5 text-left"><Key className="text-amber-700"/><span><b>Code PIN</b><small className="block text-slate-500">Utilisé uniquement pour confirmer les opérations sensibles</small></span></button><button onClick={()=>setShowLogout(true)} className="flex w-full gap-3 p-5 text-left text-red-600"><LogOut/><b>Se déconnecter</b></button></section>
 {showEdit&&<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={saveProfile} className="w-full max-w-md space-y-4 rounded-3xl bg-white p-6"><div className="flex justify-between"><h3 className="text-xl font-black">Modifier mon profil</h3><button type="button" onClick={()=>setShowEdit(false)}><X/></button></div><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nom complet" className="w-full rounded-2xl border p-4"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Téléphone" className="w-full rounded-2xl border p-4"/><button disabled={busy} className="w-full rounded-2xl bg-blue-950 py-4 font-black text-white">Enregistrer</button></form></div>}
 {showUpgrade&&<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={submitUpgrade} className="w-full max-w-md space-y-3 rounded-3xl bg-white p-6"><div className="flex justify-between"><div><h3 className="text-xl font-black">Demande de compte</h3><p className="text-xs text-slate-500">Validation administrative obligatoire.</p></div><button type="button" onClick={()=>setShowUpgrade(false)}><X/></button></div><select value={accountType} onChange={e=>setAccountType(e.target.value as any)} className="w-full rounded-2xl border p-4"><option value="marchand">Marchand / Business</option><option value="agent">Agent Market-Cash</option></select><input required value={activity} onChange={e=>setActivity(e.target.value)} placeholder="Activité / secteur" className="w-full rounded-2xl border p-4"/><input required value={city} onChange={e=>setCity(e.target.value)} placeholder="Ville" className="w-full rounded-2xl border p-4"/><input required value={address} onChange={e=>setAddress(e.target.value)} placeholder="Adresse" className="w-full rounded-2xl border p-4"/><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Pourquoi souhaitez-vous ce compte ?" className="w-full rounded-2xl border p-4"/><button disabled={busy||kycStatus!=='approved'} className="w-full rounded-2xl bg-blue-950 py-4 font-black text-white disabled:opacity-40">Envoyer la demande</button>{kycStatus!=='approved'&&<p className="text-center text-xs font-bold text-amber-700">KYC approuvé obligatoire.</p>}</form></div>}
 <LogoutModal isOpen={showLogout} onClose={()=>setShowLogout(false)}/></div>
}
