import React,{useMemo,useState}from'react';
import{Edit3,LogOut,Settings,ShieldCheck,Store,User}from'lucide-react';
import{doc,updateDoc}from'firebase/firestore';
import{Link}from'react-router-dom';
import toast from'react-hot-toast';
import{db}from'../../firebase/config';
import{useAuthStore}from'../../store/authStore';
import LogoutModal from'../../components/LogoutModal';

const roleLabel=(role:string,businessType?:string)=>businessType==='api_provider'?'Partenaire API':businessType==='direct_developer'?"Développeur d’application":businessType==='merchant'?'Marchand / Business':businessType==='agent'||role==='agent'?'Agent Market-Cash':role==='marchand'?'Business Market-Cash':role==='admin_general'?'Administrateur général':'Client MC';
export default function ClientProfile(){
 const{user,setUser}=useAuthStore();const[showEdit,setShowEdit]=useState(false);const[showLogout,setShowLogout]=useState(false);const[busy,setBusy]=useState(false);const[name,setName]=useState(user?.displayName||'');const[phone,setPhone]=useState(user?.phone||'');
 const since=useMemo(()=>user?.createdAt?new Date(user.createdAt).toLocaleDateString('fr-FR'):'—',[user?.createdAt]);if(!user)return null;
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await updateDoc(doc(db,'users',user.uid),{displayName:name.trim(),phone:phone.trim(),updatedAt:Date.now()});setUser({...user,displayName:name.trim(),phone:phone.trim()});setShowEdit(false);toast.success('Profil mis à jour.')}catch{toast.error('Modification impossible.')}finally{setBusy(false)}};
 return <div className="mx-auto max-w-2xl space-y-5 p-4 pb-28 md:p-8"><header className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-500">Mon compte</p><h1 className="mt-1 text-3xl font-black">Profil</h1></div><Link to="/client/settings" className="grid h-11 w-11 place-items-center rounded-2xl border bg-white text-blue-950 shadow-sm" aria-label="Paramètres"><Settings size={20}/></Link></header>
 <section className="overflow-hidden rounded-[2rem] border bg-white shadow-sm"><div className="bg-gradient-to-br from-blue-950 via-blue-900 to-blue-800 p-5 text-white"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center overflow-hidden rounded-2xl bg-white/10 ring-1 ring-white/20">{user.avatar?<img src={user.avatar} alt="Profil" className="h-full w-full object-cover"/>:<User/>}</div><div className="min-w-0"><h2 className="truncate text-xl font-black">{user.displayName}</h2><p className="truncate text-sm text-blue-200">{user.email}</p><span className="mt-2 inline-block rounded-full bg-white/10 px-3 py-1 text-[10px] font-black uppercase tracking-wide">{roleLabel(user.role,user.businessAccountType)}</span></div></div></div><div className="grid grid-cols-3 gap-px bg-slate-100"><Metric value={user.kycStatus==='approved'?'Vérifié':'À faire'} label="KYC"/><Metric value={user.accountStatus||'active'} label="Statut"/><Metric value={since} label="Membre"/></div><button onClick={()=>setShowEdit(true)} className="flex w-full items-center gap-3 border-t p-4 text-left"><Edit3 size={18} className="text-blue-800"/><span className="text-sm font-black">Modifier mes informations</span></button></section>
 <section className={`rounded-[2rem] border p-5 ${user.kycStatus==='approved'?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className="flex gap-3"><ShieldCheck className={user.kycStatus==='approved'?'text-emerald-700':'text-amber-700'}/><div><h2 className="font-black">Identité KYC</h2><p className="mt-1 text-sm text-slate-600">{user.kycStatus==='approved'?'Votre identité est vérifiée.':'Complétez votre KYC pour accéder aux fonctions professionnelles.'}</p>{user.kycStatus!=='approved'&&<Link to="/client/kyc" className="mt-3 inline-block rounded-xl bg-white px-4 py-2 text-xs font-black text-blue-900">Compléter le KYC</Link>}</div></div></section>
 {user.role==='client'&&<section className="rounded-[2rem] border bg-white p-5 shadow-sm"><div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-50 text-blue-900"><Store/></div><div><h2 className="text-lg font-black">Compte professionnel</h2><p className="mt-1 text-sm text-slate-500">Agent, Marchand / Business, Développeur d’application ou Partenaire API.</p></div></div><Link to="/client/professional-account" className="mt-4 block rounded-2xl bg-blue-950 p-4 text-center font-black text-white">Passer au compte professionnel</Link></section>}
 <section className="rounded-[2rem] border bg-white p-3 shadow-sm"><Link to="/client/settings" className="flex items-center gap-3 rounded-2xl p-3 font-black"><Settings className="text-blue-800"/>Paramètres</Link></section>
 <button onClick={()=>setShowLogout(true)} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-red-100 bg-white p-4 font-black text-red-600 shadow-sm"><LogOut size={19}/>Se déconnecter</button>
 {showEdit&&<div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/45 p-4"><form onSubmit={save} className="w-full max-w-md rounded-3xl bg-white p-5 shadow-2xl"><h2 className="text-xl font-black">Modifier mon profil</h2><div className="mt-4 space-y-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom complet" className="w-full rounded-2xl border p-4"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Téléphone" className="w-full rounded-2xl border p-4"/><div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">{user.email}</div></div><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setShowEdit(false)} className="rounded-2xl bg-slate-100 p-3 font-black">Annuler</button><button disabled={busy} className="rounded-2xl bg-blue-950 p-3 font-black text-white disabled:opacity-40">Enregistrer</button></div></form></div>}
 <LogoutModal isOpen={showLogout} onClose={()=>setShowLogout(false)}/></div>;
}
function Metric({value,label}:{value:string;label:string}){return <div className="bg-white p-4 text-center"><div className="text-sm font-black text-blue-950">{value}</div><div className="mt-1 text-[10px] font-black uppercase text-slate-400">{label}</div></div>}
