import React,{useEffect,useState}from'react';
import{collection,doc,getDocs,query,setDoc,updateDoc,where}from'firebase/firestore';
import{BadgeCheck,Building2,ExternalLink,ShieldCheck,UserCog}from'lucide-react';
import toast from'react-hot-toast';
import{db}from'../../firebase/config';

export default function AccountRequests(){const[kyc,setKyc]=useState<any[]>([]);const[upgrades,setUpgrades]=useState<any[]>([]);const[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{const[k,u]=await Promise.all([getDocs(query(collection(db,'kyc_requests'),where('status','==','pending'))),getDocs(query(collection(db,'account_upgrade_requests'),where('status','==','pending')))]);setKyc(k.docs.map(d=>({id:d.id,...d.data()})));setUpgrades(u.docs.map(d=>({id:d.id,...d.data()})))}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const reviewKyc=async(r:any,status:'approved'|'rejected')=>{try{await updateDoc(doc(db,'kyc_requests',r.id),{status,reviewedAt:Date.now(),updatedAt:Date.now()});await updateDoc(doc(db,'users',r.userId),{kycStatus:status,updatedAt:Date.now()});toast.success(status==='approved'?'KYC approuvé.':'KYC rejeté.');await load()}catch(e){console.error(e);toast.error('Action impossible.')}};
 const reviewUpgrade=async(r:any,status:'approved'|'rejected')=>{try{const now=Date.now();await updateDoc(doc(db,'account_upgrade_requests',r.id),{status,reviewedAt:now,updatedAt:now});if(status==='approved'){const nextRole=r.requestedType==='marchand'?'marchand':'agent';await updateDoc(doc(db,'users',r.userId),{role:nextRole,updatedAt:now});if(nextRole==='agent')await setDoc(doc(db,'agent_profiles',r.userId),{userId:r.userId,status:'active',createdAt:now,updatedAt:now},{merge:true})}toast.success(status==='approved'?'Type de compte approuvé.':'Demande rejetée.');await load()}catch(e){console.error(e);toast.error('Action impossible.')}};
 return <div className="space-y-6 pb-20"><header><p className="text-sm font-semibold text-slate-500">Conformité et comptes</p><h1 className="text-2xl font-black text-blue-950">KYC & types de comptes</h1><p className="mt-1 text-sm text-slate-500">Validez l’identité avant d’autoriser un compte Agent ou Marchand.</p></header>{loading?<div className="rounded-2xl bg-white p-6">Chargement...</div>:<><section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><ShieldCheck className="text-blue-800"/><div><h2 className="font-black">KYC en attente</h2><p className="text-xs text-slate-500">{kyc.length} dossier(s)</p></div></div><div className="mt-4 space-y-3">{kyc.length===0?<Empty/>:kyc.map(r=><article key={r.id} className="rounded-2xl border p-4"><div className="flex flex-col gap-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-black">{r.fullName}</h3><p className="text-sm text-slate-500">{r.phone} · {r.city}, {r.country}</p><p className="mt-2 text-xs text-slate-500">{r.documentType} · {r.documentNumber}</p></div><div className="flex gap-2"><button onClick={()=>reviewKyc(r,'rejected')} className="rounded-xl bg-red-50 px-3 py-2 text-xs font-black text-red-700">Rejeter</button><button onClick={()=>reviewKyc(r,'approved')} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white">Approuver</button></div></div><div className="grid gap-3 sm:grid-cols-2"><Evidence title="Pièce d'identité" url={r.documentFrontUrl}/><Evidence title="Portrait" url={r.selfieUrl}/></div></div></article>)}</div></section><section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><UserCog className="text-blue-800"/><div><h2 className="font-black">Demandes Agent / Marchand</h2><p className="text-xs text-slate-500">{upgrades.length} demande(s)</p></div></div><div className="mt-4 space-y-3">{upgrades.length===0?<Empty/>:upgrades.map(r=><article key={r.id} className="rounded-2xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><Building2 size={17}/><h3 className="font-black">{r.legalName}</h3></div><p className="text-sm text-slate-500">Demande : <b>{r.requestedType==='marchand'?'Marchand / Business':'Agent Market-Cash'}</b></p><p className="mt-1 text-xs text-slate-500">{r.activity} · {r.city} · {r.address}</p>{r.reason&&<p className="mt-2 text-xs text-slate-500">Motif : {r.reason}</p>}</div><div className="flex gap-2"><button onClick={()=>reviewUpgrade(r,'rejected')} className="rounded-xl bg-red-50 px-3 py-2 text-xs font-black text-red-700">Rejeter</button><button onClick={()=>reviewUpgrade(r,'approved')} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white">Approuver</button></div></div></article>)}</div></section></>}</div>}
function Evidence({title,url}:{title:string;url?:string}){return <div className="rounded-2xl bg-slate-50 p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{title}</p>{url&&<a href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-black text-blue-800">Ouvrir <ExternalLink size={13}/></a>}</div>{url?<img src={url} alt={title} className="mt-3 h-48 w-full rounded-xl border bg-white object-contain"/>:<p className="mt-3 text-xs font-bold text-red-600">Image manquante</p>}</div>}
function Empty(){return <div className="rounded-2xl bg-slate-50 p-5 text-center text-sm text-slate-500"><BadgeCheck className="mx-auto mb-2 text-slate-400"/>Aucune demande en attente.</div>}
