import React,{useEffect,useState}from'react';
import{ArrowDownLeft,ArrowUpRight,History,LockKeyhole,ChevronRight}from'lucide-react';
import SecurityConfirmModal from'../../components/SecurityConfirmModal';
import TransactionDetailsModal from'../../components/TransactionDetailsModal';
import{useSensitiveReveal}from'../../hooks/useSensitiveReveal';
import{agentWalletService}from'../../services/agentWalletService';

export default function AgentHistory(){
  const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[selected,setSelected]=useState<any|null>(null);const secure=useSensitiveReveal(90000);
  useEffect(()=>{agentWalletService.getHistory().then(setItems).catch(()=>setItems([])).finally(()=>setLoading(false))},[]);
  return <div className="max-w-xl mx-auto p-4 md:p-8"><h1 className="text-2xl font-black text-blue-950">Transactions agent</h1><p className="text-sm text-slate-500 mt-1">Les opérations du terminal sont protégées par votre code secret d'application. Touchez une transaction pour ouvrir ses détails.</p>{!secure.revealed?<button onClick={secure.request} className="mt-5 w-full rounded-3xl border bg-white p-8 text-center shadow-sm"><LockKeyhole className="mx-auto text-blue-800"/><b className="mt-3 block text-blue-950">Afficher les transactions</b><span className="mt-1 block text-xs text-slate-500">Code secret de l'application requis.</span></button>:<div className="mt-4 space-y-2">{loading?<div className="rounded-3xl bg-white border p-8 text-center text-slate-500">Chargement…</div>:items.length===0?<div className="rounded-3xl bg-white border p-8 text-center text-slate-500"><History className="mx-auto mb-2"/>Aucune transaction pour le moment.</div>:items.map(t=><button key={t.id} onClick={()=>setSelected(t)} className="w-full rounded-2xl bg-white border p-4 text-left shadow-sm transition active:scale-[.995]"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className={`w-10 h-10 rounded-xl grid place-items-center ${t.type==='cash_in'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{t.type==='cash_in'?<ArrowDownLeft size={18}/>:<ArrowUpRight size={18}/>}</div><div><p className="font-black text-slate-900">{t.type==='cash_in'?'Dépôt client':t.type==='cash_out'?'Retrait client':'Crédit agent'}</p><p className="text-[10px] font-mono text-slate-400">{t.reference}</p></div></div><div className="flex items-center gap-2"><div className="text-right"><p className="font-black text-blue-950">{Number(t.amount||0).toLocaleString('fr-FR')} {t.currency}</p><p className="text-[10px] text-slate-400">{new Date(t.createdAt).toLocaleString('fr-FR')}</p></div><ChevronRight size={16} className="text-slate-300"/></div></div></button>)}</div>}<SecurityConfirmModal open={secure.open} busy={secure.busy} onClose={secure.close} onConfirm={secure.confirm} title="Afficher les transactions Agent" subtitle="Entrez votre code secret d'application pour consulter les opérations du terminal."/>{secure.revealed&&selected&&<TransactionDetailsModal transaction={selected} onClose={()=>setSelected(null)}/>}</div>
}
